>Chlamydomonas_reinhardtii_gnl|BL_ORD_ID|9070 _17.g729800.t1.1|PACid:19867375

MAL-QMKQSPSM------------------------------------------------
-------GVRRASQPVLPPRPIVHR---GVGSVS------------RRPAVVVKASLLDA
ASAASA----------------VDAVHHATQLYTLAEGGPIDVLAQFFEFVLQTLDEGLE
SAKIPYSYGF--AIIALTVLVKVATFPLTQKQVESTLSL--------QALQPRVKELQAK
Y-ADDPEN--------LQLETARLYKEAGVNPLAGCFPT------LATIPVFIGLYNALS
NAAKEGLL-TEGFFWIPSLGGPTTI-----GGGLEW------LVPF-ENGA-------PP
VGWANAAAYLVMPVLLVASQYASQK----IISSQ----NNQDPSQQQAQAILKFLPLMIG
WFSLNVPSGLTLYWFVNNLLSTGQQLYLK-----ATVKVNIPE------AIKAPATAGSS
TPIVKPKEERVKK----VTGKEL---------------------GS--------------
--------------------RKKRR---------------------NDDGEEVEDVEVEV
VS--------SGSSSSSGSNGASGRKGEKFRALKAREAAAKAASTVSAGAGGSEEGKDNS
A----------------
>Volvox_carteri_gnl|BL_ORD_ID|5658 _Vocar20010438m|PACid:23129534

MAL-AMKQYPSAL-----------------------------------------------
-------GARKPCQPLLPPRPSVRRPGAGIGSGS------------RRAAVCVKASLLDP
STAAST----------------VEAVQHAQNLYTLADGGPIDLLAQFFTSVLRTLDDGLE
NAHVPYSYGF--AIITLTVLVKLATFPLTQKQVESTLSL--------QALQPRVKELQAK
H-ADDPET--------LQLETARMYKEAGVNPLAGCLPT------LATIPVFIGLYNALS
NAAKAGLL-TEGFFWIPSLSGPTTI-----GGGLEW------LFPF-QDGA-------PP
VGWANAAAYLVMPVLLVASQYASQK----IISTTQ---NSNDPAQQQSQAILKFLPLMIG
WFSLNVPSGLTLYWFVNNLLSTAQQLYLK-----ATVKVNVPE------SIKAPVAATSA
T-VVKPKEERVKR----ITGKEL---------------------GA--------------
--------------------RKKRR---------------------NEAGEEVEEVDVEI
VSTSGSNGAASASPAVNGNGSGSSRKGEKFRALKAREAAAKAAA----------------
-----------------
>Coccomyxa_subellipsoidea_gnl|BL_ORD_ID|1260 15426|PACid:27386896

MTL---------------------------------------------------------
----------------------------------------------ADTAASSAAQAVGD
KAADAIVSSATA----------VQSATDAAAEAVQRDNGWFGFFTGPFETVLKVLDTGLD
KLHVPYSYGF--SIILLTIFVKALTFPLSKKQVESTVAI--------QALQPRVKEIQEK
YKGRDPQE--------AQIEVAKLYQEAKVNPLAGCLPT------LITLPVWIGLYRALS
NVADEGLL-SEGFFWIPSLAGPTTLAAQKAGAG-SW------LFPL-VNGA-------PP
IGWHDASAYLVLPVLLIVSQYVSQK----IISPPS-----EDPSQQSAQWILKFLPLMIG
WFSLNVPSGLTIYWFINNVLSTAQQLWLK-----KTIQPPALASAGTGTVV---------
------------------------------------------------------------
-----------------------------------------------NARSSVEDLRPTG
ETGCPFSLAASAPCK---------------------------------------------
-----------------
>Micromonas_pusilla_CCMP1545_gnl|BL_ORD_ID|10331 52221|PACid:27348985

MQA-TSATGAGAVARGAVAVAGARASSIRGVAA--L------------------------
-------PARRASRALAPRRRVAPRRAAVAARASI-GGEFPVFDVINDAVINAHASAMTS
DALGSIFQVADA----------A-AVDVEEIP-GLQKGGWLGPITDFLEASLGVIDQGLE
GLNVPYSYGY--AILVLTVVVKLVTFPLTKKQVEGSIAM--------QALQPRVKELQAM
Y-ANDPER--------LQMETARLYKEANFNPLAGCLPT------FATLPVFIGLYRALS
NAATEGML-EDGFYWIPSLGGPTSIAARNDGSGFSW------LWPF-VDGA-------PP
LGWHDTAAYLALPVLLVVSQFASQK----IMTPDQ--GKDVDPSQASSQAILKFLPFMIG
FFSLNVPAGLTLYWFANNIFSTAQTVYLR-----KTTKAPDSIQNVGGGSAAMPMPGTTP
AATQPVRVEYVPK----SQRKSG---------------------GA--------------
----------------------APKPPPPRVEAMPAAVASEFADFDDGPARVTETVEGVV
VGGDGADATESAGGGGGGDARGKGSKKSKKAAGSRKRRNKSR------------------
-----------------
>gnl|BL_ORD_ID|4751 96326|PACid:27400020
MAA-CVANLGGIARSNALTPVGARGASSSRTAGGLL------------------------
-------PLRRAGSSGRAVRRV---RSSVAVRASMAGAEFPSFDQVQGAVANVHASFIGN
DAVASLFQVADA----------ADAAAPEELK-GLQKGGWLGPITDLLESILKGIDSGFV
GLGVPYSYGY--AILALTVLVKVVTFPLTKKQVEGSLQM--------QAIQPRVKELQAM
Y-ANDPER--------LQMETARLYKEANFNPLAGCLPT------FATLPVFIGLYRALS
NAAVEGEL-TDGFYWIPSLGGPTSIEARNDGNGFAW------LFPF-VDGA-------PP
LGWHDTIAYLVLPVLLVASQLISQK----VMTPDQ--PKSDDPAQQQSQAILKFLPFMIG
FFSLNVPAGLTLYWFANNIFSTAQTVYLR-----KTTKAPEMPAAVAGG---MPMPG-TP
ASAQPVRVEYVPK----SQRKAQ---------------------GS--------------
--------------------VPAPKPAPPKVEPMPESLAAEFGDFDDGPAKIVEPV--VV
EAKVVADTTGAAAAAAAGEAGGKKGGSRKGSKGSRKRKGSRK------------------
-----------------
>Ostreococcus_lucimarinus_gnl|BL_ORD_ID|557 3334|PACid:27413422

------------------------------------------------------------
------------------------------------------------------------
---------------------------EALKAAGLQKGGWLGPITDGLESALEGIDSVLD
G-RVPYSYGF--SIIVLTVLVKLATFPLSKKQVESSMQM--------QAMQPRIKELQAM
Y-ANDPER--------LQMEQARLYKEAGFNPLAGCLPV------FATLPVFIGLYRALS
NAASEGLL-TDGFYWIPSLGGPTSIASRNAGSGFAW------LWPF-VDGH-------PP
LGWHDTTAYLVLPVLLVASQYVSQQ----IVSPQP---KTDDPAQQQSQAILKFLPLMIG
FFSLNVPAGLTLYWFANNIITTAQTLILR-----KTTTAPEPPVAKSGAAG---------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------
>Coccomyxa_subellipsoidea_gnl|BL_ORD_ID|5045 12888|PACid:27390681

MSRV--------------------------------------------------------
------------------------------------------------------------
----------------------LHHWRCSALQAAAQDDGWLAPISSGLNYSLQQIQTGLD
QLHVPYSYGW--AIIVLTVGTKILTFPFTK--VESALAV--------QKLKPTIDAIKRQ
Y-GEDKNS--------IQRETSALYEASGVNPAAGCLPT------LATIPIFWGLYRTLS
NVASAGLL-TEGFYWIPSLSGPTSLAAQRAGTGTAW------LFPF-VDGA-------PP
VGWEDAARYLALPIALVAAQFASSA----VISPPI---DDEDKNAAFSKGLLIAVPFMVG
WFALNVPSGLSLYYFSNTIITSGIQIWLR-----KLGGAYSPLLLLT--FIHWPTVRACS
SFLCCPRQANSCASLFLVPGNHL---------------------FA--------------
--------------------CWARRDFYVQLSW---------------------------
------------------------------------------------------------
-----------------
>Chlamydomonas_reinhardtii_gnl|BL_ORD_ID|5308 _06.g251900.t1.1|PACid:19863606

M-----------------------------------------------------------
--------------------------------------------------------YVLA
DASASTAAAAVM----------PTAVDSAAGAAPQRAGGWVAPVADALEQVLYALQEGLD
KLHVPYSYGY--SIILLTLIVKLLTYPLTKQQVESAMAV--------QALKPRIDLIKDR
F-GEDKDK--------IQKETSVLYEQAGVNPLAGCLPT------LATIPIFIGLFSSLT
NVANDGLLDTQGFYFVPSLAGPTTMAMRQSGLGTSW------LWPLGPDGA-------PP
IGWEDAAAYLTLPLLLVAVQYASSS----VTSPPI---DPKDENANTQRALLVFLPLMVG
WFSLNVPAGLSLYYLANTVLSSAIQIYLK-----KLGGANVVMNELG--PVTKPGSGRRN
GVAAGEWSVWKPA----TVL-TT---------------------AE--------------
--------------------AAKAR---------------------AEAEEAVERAREAA
EEAAAAAAFDNASVSLSVDDSTAAIAGTATMAVTAGATAAAMDPSKVNRRCKRRRLTSLV
QDGSTASAAVAGASA--
>Volvox_carteri_gnl|BL_ORD_ID|4166 _Vocar20003543m|PACid:23128036

MATLRYRPVAQRVKRNAHFRYAIRYAARNVLV----------------------------
------------DLPCPGRLRGSSYRAGSEITLLTSHLSAGIPDYLDRADLLPTFSFPLA
NAGAASESVAAA----------VTANILSASPTDQRAGGWVAPLADVLEQVLYVLKDCLD
LLHVPYSYGY--SIILLTLIVKIVTYPLTKQQVESTLAV--------QALKPRVDLIKDR
F-GDDKEK--------IQKETSILYEQAGVNPLAGCLPT------LATTPIFIGLYSSLT
NVANEGLLDTQGFYWIPSL-----------------------------------------
-----------------AVQYASLY----STGPTS---DATDVNARLQRALLLGLPVMIG
WFALNVPSGLSLYYLSNTILSTAQQVYLK-----KLGGAKVAIKKLG--PIMKPGSGRRS
GAPEAELKLWVSA----TTFKST---------------------AE--------------
--------------------RGKNS---------------------LNMEGPVELARNA-
---------------LDTDLPETTAALTDVIKSSQTDSSPLVDLSNVNRFCKRRRLSSLV
QDGANGAQIFPAATTSV
>Micromonas_pusilla_CCMP1545_gnl|BL_ORD_ID|3956 31798|PACid:27342602

MTS-QGCSSGSLVCRGARGLYRCGRQT---------------------------------
-------GCPRRDTSLLSRRTRPRSFDASCGAISATDIGESITIVPDVITAAIFASEQIA
DLSESTFTVGATVVDSSHATLFAELSALTEITGPQRMEGILSPVSDLLEEFVLATQRYFS
DAGVRYPLGS--SIIFTTFVVKALTYPFTKVQVESALNM--------QNLQPQVNAVREK
Y-RDDQEQ--------MNIEINRLYEDNQVSPLAGCGPL------LLTLPVVWGLYRAFN
NASIDGSF-DEPWFFIPSLAGPTP------DRSLAW------LLPLDDNYQ-------PP
LGWHDASLYLVVPILTVASQYVSMS----ILSPVKDLNDPNTAETEQQSFLLNFLPLFIG
YISLTVPAGLTLYWLFNNIFTTATQVYLR-----QGGGAVAKVEKIK--DVKLKVPLGCA
IVDQNSTDQLSVHDVFEGPYVLVTDSGEIDLAYSGEIDLAYSALPD--------------
--------------------HDKAYGFYLSPELRSAKTDKWRLHMEKRGKRSLDPAERYN
ATPEELRLLISEYLKLGMVAEAEEISVELGRLGSETERSDPL------------------
-----------------
>Ostreococcus_lucimarinus_gnl|BL_ORD_ID|3977 3329|PACid:27416850

------------------------------------------------------------
------------------------------------------------------------
----------------------AAKIASGEIAAPQRMEGWLAPVSDALEDLLFAIQGQLQ
GLGVPYSTGN--AIIIVTILVKFVTYPLTRDQVVSSLNM--------KNLQPQIAAIREK
Y-EDDQER--------MNKEINRVYEENGVNPLAGCGPA------LLTFPVLAGLYRAFN
NAGIDGAF-DEAWFFLPSLAGPTD------ARDLSW------LLPLDSDYA-------PP
IGWEEASLYLIFPVLTTISQFVSME----VLKPEE---TEKTDEMKNQSVLLKLLPLFIG
YISLTVPAGLALYWFWNNVFTTGIQVFLR-----N-GGAKATVE----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------
>Coccomyxa_subellipsoidea_gnl|BL_ORD_ID|7951 39658|PACid:27393587

M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------KLRRWLTIIYTTIGARLLTLPLVVKQQRNTANM--------TMARPEMMALKDW
Y-TEETARGNPKATTEYQQRLANLWQKYDCNPFKSMLGI------LAQAPLFIGFFSALR
ALSAAK---------VPSMT----------EGGVAW------FTDL-TLAD-------P-
--------YYALPIMSSAVFLLTVE----LGAADGMQGQDEA-MLRRMKNIFRAIGVAMV
PLTASFPQGVFLYWVTSNIFSLGQSVLFKLPAVRKTLKLPDLAKM---------------
------------------------------------------------------------
------------------------------------------------------------
-----RATATGLPIT---------EAGKPLVTFAQPPKQRKAKTT---------------
-----------------
>Micromonas_pusilla_CCMP1545_gnl|BL_ORD_ID|9618 3586|PACid:27348271

------------------------------------------------------------
------------------------------------------------------------
---------------------------------------EVIAIAADSWITTAGLMYVIE
YFHLAHGMEWYAAIAAATCVMRVCAFPLTIMQQKSAGKM--------HLAKPEMTALQES
I--NEARRAGEHERAARLGRVFAIWSKHDVHPAKMLAPL------LFQAPVFISFYFAIS
RMAEG----------LPSMR----------DGGFAW------FQDL-SIAD-------P-
--------TFALPIISSLTFLAAVE----FAPQNP---AVKSSQREMTKWGLRALGVAMV
PLTASFPSGVFVYWITSNVFSFAQTVLLRVPFAKRAMGIPEDPPP---------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------
>Ostreococcus_lucimarinus_gnl|BL_ORD_ID|5645 40894|PACid:27418518

MTT-AGGAAE--------------------------------------------------
------------------------------------------------------------
----------------------TLTSASDLAPVVGSLASEVVPVASQSWPTTAALMYAME
YFHVAHGLEWWLAIVGATVFMRTITFPLIVMQMRNTAKM--------QLCKPELEALQAK
M--KSNPQQDPELANAYYKEMQKVWKKYDVNPVKSFAPI------LINAPVFISFFFAIS
KMAQG----------VPSFE----------SGGPSM------YPDL-SMAD-------P-
--------TYSLPILSSLTFLASVE----LGAVEGMQTSQSA----QMKWFLRALAVAMV
PLTASFPQGVFVYWITSNIFSGFQTSITRTKAFKSTMGIPDVSAV---------------
------------------------------------------------------------
------------------------------------------------------------
-----AEAPAEAALGRVQLDRFQKKYGATPTLHKRPPTQKQRKK----------------
-----------------
>gnl|BL_ORD_ID|3407 69262|PACid:27398672
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--HLAHDMEWWAAIMATTAIMRVFVMPFMVMQQRVAARM--------HIAKPEIEALNAR
I---KGMGGDQQVMAEAQKEIFAIWKKHNCNPAYMMLPI------AVQAPLFISFYFAIS
EMAKG----------VPSFA----------SGGPDWPLGPISMHDL-TAAD-------P-
--------TYIMPVLSSATFLATVE----LGGAGNPETSGAAQQTMMTKWGLRALSVALI
PMTAGFSKGVFVYWITTNMFSLGQTLAFKVPLIKKIVAIPEIP-----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------
>Chlamydomonas_reinhardtii_gnl|BL_ORD_ID|3384 _16.g690200.t1.1|PACid:19861677

MAQ-RWRALQRGAALLAHHTE-SAASTQVLSACSTSASSLLQQITLD--QRGSGGSWQQH
QHAWGSSSHRTFFSFARKKPDAGAVAAASTG---DETSISGSEPVADPTPVGPPEFFPLP
ESAPDAIEVASA----------IHQAC------SALERASIMSAKADAFFSASWCISGLQ
AVHDLLDTPWFLSIAIFNITLRLLTFPLMVVAQKGSAKMMEFNHNLIHAKKLQEAAMKAT
S-QEEHQR----LFQAFRNEYNVQTAKHG-DPVKTALVVPGVM--ILNGAIFLSIFNGVS
KLMAAK---------VPSLT----------TGGALW------FSDL-TSPD-------P-
--------YFGLPLMCTAVTLAMVEYGINLAGDAGPMPEDRAKMTNGLKNFMRVMAFMFI
PAGGYVAAGTAVLWVSNTAFGVVQGLTLRNDRFRRRVGLPTMQAL---------------
------------------------------------------------------------
----------------------------------------------RDMNAKVMAANAAG
TPASAGAAGASAAATLAAAADTSAPASAAPLLSNSPVGAKARR-----------------
-----------------
>Volvox_carteri_gnl|BL_ORD_ID|131 _Vocar20001462m|PACid:23123990

MAQ-RWRSLQRGAALLLHHAEPSASGAPGLLSAYPSASSLILNLKSDQHQHKGGASWHQN
-HAW---TGFIGVRHASTKSSSASVPSSSSGFPDDAPSNSG----MDLTP--PPEFFPLP
ESS--AAEVATA----------IHQAC------DALERASLLGAKADAFFAASWCISGLQ
AVHEMLDTPWWVSIMLFNISLRLCTFPLMVLAQRGSAKMMEFNYALLHAKKLQEAAMKAT
N-RAEHDR----LFNAFRTEYTAQVSKHG-DPVKTALMVPGVM--IFNGFVFLSIFNGIS
KLMAAKVLRRCA---VPSLT----------TGGALW------FSDL-TQPD-------P-
--------FFGLPIMCTLVTLAMVEYGINLAGDAGPMPSERQQATKTMKWVFRVLAFMFI
PAGNYVAAGTALLWVSNTAFGVVQGMLLRNDGVRQRMGLPSMQEL---------------
------------------------------------------------------------
----------------------------------------------REMNARVLEANSAN
APKPSEAPPSIFSAT-KPSLDT-APAVNVPLMSRPP-GSKGTKGP---------------
-----------------
>Ostreococcus_lucimarinus_gnl|BL_ORD_ID|1034 93298|PACid:27413900

M-----------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------SDSMT
HLHAATGAPWFVALAASAALVRAATAPISARTIKASATV--------SAASALAKSRKRG
N--SEHVG--------VRDVLDAIGELRGKAPGTGAHPAWLVAGPLAQIPFFLCAVMAVR
RLAADGA--------NNGLV----------TGGALW------FQDL-TVPAVDVAMMTAP
MGPYGG----ILPVLTAAALFANVN----ANFASA---AAQSRGMTIVKLVLEWMTLPML
VIGMQLPQAVHCYWLTSSAWALAQNRALSTTFAREALGINALAKVTREIAASQGLGGEDV
AMSPEVLELVKAAAKERAGNNNAQAVNLLLRAARGGGDVAAALRGEDLGKSHPTVLFALG
QTYAVLKEWKKSALTYEYSARAEPDPLRRSRALMGAGVARARLGDLGMASEALYEANRLN
PTDASVKVALASALKLNGDPERALEILREAAELQPDIDERYVKPLERELASRTSA-----
-----------------
