>gnl|BL_ORD_ID|9070 @Chlamydomonas_reinhardtii@_17.g729800.t1.1|PACid:19867375
MAL-------------------------------QMK-----------------------
QSPS-MGVRRASQPVLPPRPIVHR---GVG------------------SVSRRPAVVVKA
SLLDAAS-----------------------------------------------------
---------------------AASAVDAVH-HATQLYTLAEGGPIDVLAQFFEFVLQTLD
EG----------------------------------------------------------
-------------------------------------------LESAKIPY--SYGFAII
ALTVLVKVATFPLTQKQ------------VESTLSL--------QALQ------------
-PRVKELQAKY-ADDPEN--------LQLETARLYKEAGVNP------------------
----------------------LAGCFPT----LATIPVFIGLYNALSNAAKEGLL-TEG
FFWIPSLGGPTTI-----G---------GGLEW------LVPF-ENGAP------PVGWA
NAAAYLVMPVLLVASQYASQK----IIS-SQ---NNQDPSQQQAQAILKFLPLMIGWFSL
NVPSGLTLYWFVNNLLSTG--QQLYLKATV---KVNIPEAIK------APATAGSSTPIV
KPKEERVKK----VTGKELGSRKKRR--------NDDGEEVEDVEVEVVS--------SG
SSSSSGSNGASGRKGEKFRALKAREAAAKAASTVSAGAGGS-------------------
------------------------------------------------------------
-------------EEGKDNSA-----------------------
>gnl|BL_ORD_ID|5658 @Volvox_carteri@_Vocar20010438m|PACid:23129534
MAL-------------------------------AMK-----------------------
QYPSALGARKPCQPLLPPRPSVRRPGAGIG------------------SGSRRAAVCVKA
SLLDPST-----------------------------------------------------
---------------------AASTVEAVQ-HAQNLYTLADGGPIDLLAQFFTSVLRTLD
DG----------------------------------------------------------
-------------------------------------------LENAHVPY--SYGFAII
TLTVLVKLATFPLTQKQ------------VESTLSL--------QALQ------------
-PRVKELQAKH-ADDPET--------LQLETARMYKEAGVNP------------------
----------------------LAGCLPT----LATIPVFIGLYNALSNAAKAGLL-TEG
FFWIPSLSGPTTI-----G---------GGLEW------LFPF-QDGAP------PVGWA
NAAAYLVMPVLLVASQYASQK----IISTTQ---NSNDPAQQQSQAILKFLPLMIGWFSL
NVPSGLTLYWFVNNLLSTA--QQLYLKATV---KVNVPESIK------APVAATSAT-VV
KPKEERVKR----ITGKELGARKKRR--------NEAGEEVEEVDVEIVSTSGSNGAASA
SPAVNGNGSGSSRKGEKFRALKAREAAAKAAA----------------------------
------------------------------------------------------------
--------------------------------------------
>gnl|BL_ORD_ID|1260 @Coccomyxa_subellipsoidea@15426|PACid:27386896
MTL---------------------------------------------------------
---------------------------------------------ADTAASSAAQAVGDK
AADAIVS-----------------------------------------------------
---------------------SATAVQSAT-DAAAEAVQRDNGWFGFFTGPFETVLKVLD
TG----------------------------------------------------------
-------------------------------------------LDKLHVPY--SYGFSII
LLTIFVKALTFPLSKKQ------------VESTVAI--------QALQ------------
-PRVKEIQEKYKGRDPQE--------AQIEVAKLYQEAKVNP------------------
----------------------LAGCLPT----LITLPVWIGLYRALSNVADEGLL-SEG
FFWIPSLAGPTTLAAQKAG---------AG-SW------LFPL-VNGAP------PIGWH
DASAYLVLPVLLIVSQYVSQK----IISPPS-----EDPSQQSAQWILKFLPLMIGWFSL
NVPSGLTIYWFINNVLSTA--QQLWLKKTI---QPPALASAGTGTV--------------
----------------------------------VNARSSVEDLRPTGETGCPFSLAASA
PCK---------------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>gnl|BL_ORD_ID|10331 @Micromonas_pusilla_CCMP1545@52221|PACid:27348985
MQATSATGAGAVARGAVAVAGARASSIRGVAA----------------------------
-----LPARRASRALAPRRRVAPRRAAVAARASI-GGEFPVFDVINDAVINAHASAMTSD
ALGSIFQ-----------------------------------------------------
---------------------VADAA-AVDVEEIP--GLQKGGWLGPITDFLEASLGVID
QG----------------------------------------------------------
-------------------------------------------LEGLNVPY--SYGYAIL
VLTVVVKLVTFPLTKKQ------------VEGSIAM--------QALQ------------
-PRVKELQAMY-ANDPER--------LQMETARLYKEANFNP------------------
----------------------LAGCLPT----FATLPVFIGLYRALSNAATEGML-EDG
FYWIPSLGGPTSIAARNDG---------SGFSW------LWPF-VDGAP------PLGWH
DTAAYLALPVLLVVSQFASQK----IMTPDQG--KDVDPSQASSQAILKFLPFMIGFFSL
NVPAGLTLYWFANNIFSTA--QTVYLRKTT---KAPDSIQNVGGGSAAMPMPGTTPAATQ
PVRVEYVPK----SQRKSGGA--APKPPPPRVEAMPAAVASEFADFDDGPARVTETVEGV
VVGGDGADATESAGGGGGGDARGKGSKKSKKAAGSRKRRNK-------------------
------------------------------------------------------------
-------------SR-----------------------------
>gnl|BL_ORD_ID|4751 96326|PACid:27400020
MAACVANLGGIARSNALTPVGARGASSSRTAGGL--------------------------
-----LPLRRAGSSGRAVRRV---RSSVAVRASMAGAEFPSFDQVQGAVANVHASFIGND
AVASLFQ-----------------------------------------------------
---------------------VADAADAAAPEELK--GLQKGGWLGPITDLLESILKGID
SG----------------------------------------------------------
-------------------------------------------FVGLGVPY--SYGYAIL
ALTVLVKVVTFPLTKKQ------------VEGSLQM--------QAIQ------------
-PRVKELQAMY-ANDPER--------LQMETARLYKEANFNP------------------
----------------------LAGCLPT----FATLPVFIGLYRALSNAAVEGEL-TDG
FYWIPSLGGPTSIEARNDG---------NGFAW------LFPF-VDGAP------PLGWH
DTIAYLVLPVLLVASQLISQK----VMTPDQP--KSDDPAQQQSQAILKFLPFMIGFFSL
NVPAGLTLYWFANNIFSTA--QTVYLRKTT---KAPEMPAAVAGG---MPMPG-TPASAQ
PVRVEYVPK----SQRKAQGSVPAPKPAPPKVEPMPESLAAEFGDFDDGPAKIVEPV--V
VEAKVVADTTGAAAAAAAGEAGGKKGGSRKGSKGSRKRKGS-------------------
------------------------------------------------------------
-------------RK-----------------------------
>gnl|BL_ORD_ID|557 @Ostreococcus_lucimarinus@3334|PACid:27413422
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------EALKAAGLQKGGWLGPITDGLESALEGID
SV----------------------------------------------------------
-------------------------------------------LDG-RVPY--SYGFSII
VLTVLVKLATFPLSKKQ------------VESSMQM--------QAMQ------------
-PRIKELQAMY-ANDPER--------LQMEQARLYKEAGFNP------------------
----------------------LAGCLPV----FATLPVFIGLYRALSNAASEGLL-TDG
FYWIPSLGGPTSIASRNAG---------SGFAW------LWPF-VDGHP------PLGWH
DTTAYLVLPVLLVASQYVSQQ----IVSPQP---KTDDPAQQQSQAILKFLPLMIGFFSL
NVPAGLTLYWFANNIITTA--QTLILRKTT---TAPEPPVAKSGAAG-------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>gnl|BL_ORD_ID|5045 @Coccomyxa_subellipsoidea@12888|PACid:27390681
MSRVLHHWR---------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------CSALQAAAQDDGWLAPISSGLNYSLQQIQ
TG----------------------------------------------------------
-------------------------------------------LDQLHVPY--SYGWAII
VLTVGTKILTFPFTK--------------VESALAV--------QKLK------------
-PTIDAIKRQY-GEDKNS--------IQRETSALYEASGVNP------------------
----------------------AAGCLPT----LATIPIFWGLYRTLSNVASAGLL-TEG
FYWIPSLSGPTSLAAQRAG---------TGTAW------LFPF-VDGAP------PVGWE
DAARYLALPIALVAAQFASSA----VISPPI---DDEDKNAAFSKGLLIAVPFMVGWFAL
NVPSGLSLYYFSNTIITSG--IQIWLRKLG---GAYSPLLLLTFIH--WPTVRACSSFLC
CPRQANSCASLFLVPGNHLFACWARRDFYVQLSW--------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>gnl|BL_ORD_ID|5308 @Chlamydomonas_reinhardtii@_06.g251900.t1.1|PACid:19863606
M-----------------------------------------------------------
-------------------------------------------------------YVLAD
ASASTAA-----------------------------------------------------
---------------------AAVMPTAVD-SAAGAAPQRAGGWVAPVADALEQVLYALQ
EG----------------------------------------------------------
-------------------------------------------LDKLHVPY--SYGYSII
LLTLIVKLLTYPLTKQQ------------VESAMAV--------QALK------------
-PRIDLIKDRF-GEDKDK--------IQKETSVLYEQAGVNP------------------
----------------------LAGCLPT----LATIPIFIGLFSSLTNVANDGLLDTQG
FYFVPSLAGPTTMAMRQSG---------LGTSW------LWPLGPDGAP------PIGWE
DAAAYLTLPLLLVAVQYASSS----VTSPPI---DPKDENANTQRALLVFLPLMVGWFSL
NVPAGLSLYYLANTVLSSA--IQIYLKKLG---GANVVMNELGPVT--KPGSGRRNGVAA
GEWSVWKPA----TVL-TTAEAAKAR--------AEAEEAVERAREAAEEAAAAAAFDNA
SVSLSVDDSTAAIAGTATMAVTAGATAAAMDPSKVNRRCKR-------------------
------------------------------------------------------------
-------------RRLTSLVQDGSTASAAVAGASA---------
>gnl|BL_ORD_ID|4166 @Volvox_carteri@_Vocar20003543m|PACid:23128036
MAT------LRYRPVAQRVKRNAHFRYAIRYAARNV------------------------
LVDLPCPGRLRGSSYRAGSEITLLTSHLSA---------GIPDYLDRADLLPTFSFPLAN
AGAASES-----------------------------------------------------
---------------------VAAAVTANI-LSASPTDQRAGGWVAPLADVLEQVLYVLK
DC----------------------------------------------------------
-------------------------------------------LDLLHVPY--SYGYSII
LLTLIVKIVTYPLTKQQ------------VESTLAV--------QALK------------
-PRVDLIKDRF-GDDKEK--------IQKETSILYEQAGVNP------------------
----------------------LAGCLPT----LATTPIFIGLYSSLTNVANEGLLDTQG
FYWIPSL-----------------------------------------------------
-------------AVQYASLY----STGPTS---DATDVNARLQRALLLGLPVMIGWFAL
NVPSGLSLYYLSNTILSTA--QQVYLKKLG---GAKVAIKKLGPIM--KPGSGRRSGAPE
AELKLWVSA----TTFKSTAERGKNS--------LNMEGPVELARNA-------------
---LDTDLPETTAALTDVIKSSQTDSSPLVDLSNVNRFCKR-------------------
------------------------------------------------------------
-------------RRLSSLVQDGANGAQIFPAATTSV-------
>gnl|BL_ORD_ID|3956 @Micromonas_pusilla_CCMP1545@31798|PACid:27342602
MTS------QGCSSGSLVCRGARGLYRCGRQTGCPR------------------------
RDTSLLSRRTRPRSFDASCGAISATDIGESITIVPDVITAAIFASEQIADLSESTFTVGA
TVVDSSH-----------------------------------------------------
---------------------ATLFAELSA-LTEITGPQRMEGILSPVSDLLEEFVLATQ
RY----------------------------------------------------------
-------------------------------------------FSDAGVRY--PLGSSII
FTTFVVKALTYPFTKVQ------------VESALNM--------QNLQ------------
-PQVNAVREKY-RDDQEQ--------MNIEINRLYEDNQVSP------------------
----------------------LAGCGPL----LLTLPVVWGLYRAFNNASIDGSF-DEP
WFFIPSLAGPTP------D---------RSLAW------LLPLDDNYQP------PLGWH
DASLYLVVPILTVASQYVSMS----ILSPVKDLNDPNTAETEQQSFLLNFLPLFIGYISL
TVPAGLTLYWLFNNIFTTA--TQVYLRQGG---GAVAKVEKIKDVK--LKVPLGCAIVDQ
NSTDQLSVHDVFEGPYVLVTDSGEID--------LAYSGEIDLAYSALPDHDKAYGFYLS
PELRSAKTDKWRLHMEKRGKRSLDPAERYNATPEELRLLIS-------------------
------------------------------------------------------------
-------------EYLKLGMVAEAEEISVELGRLGSETERSDPL
>gnl|BL_ORD_ID|3977 @Ostreococcus_lucimarinus@3329|PACid:27416850
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------AAKIA-SGEIAAPQRMEGWLAPVSDALEDLLFAIQ
GQ----------------------------------------------------------
-------------------------------------------LQGLGVPY--STGNAII
IVTILVKFVTYPLTRDQ------------VVSSLNM--------KNLQ------------
-PQIAAIREKY-EDDQER--------MNKEINRVYEENGVNP------------------
----------------------LAGCGPA----LLTFPVLAGLYRAFNNAGIDGAF-DEA
WFFLPSLAGPTD------A---------RDLSW------LLPLDSDYAP------PIGWE
EASLYLIFPVLTTISQFVSME----VLKPEE---TEKTDEMKNQSVLLKLLPLFIGYISL
TVPAGLALYWFWNNVFTTG--IQVFLRN-G---GAKATVE--------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>gnl|BL_ORD_ID|7951 @Coccomyxa_subellipsoidea@39658|PACid:27393587
MK----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------LRRWLTII
YTTIGARLLTLPLVVKQ------------QRNTANM--------TMAR------------
-PEMMALKDWY-TEETARGNPKATTEYQQRLANLWQKYDCNP------------------
----------------------FKSMLGI----LAQAPLFIGFFSALRALSAAK------
---VPSMT----------E---------GGVAW------FTDL-TLADP-----------
----YYALPIMSSAVFLLTVE----LGAADGMQ-GQDEAMLRRMKNIFRAIGVAMVPLTA
SFPQGVFLYWVTSNIFSLG--QSVLFKLPAVRKTLKLPDLAKM-----------------
-----------------------------------------------------RATATGL
PIT---------EAGKPLVTFAQPPKQRKAKTT---------------------------
------------------------------------------------------------
--------------------------------------------
>gnl|BL_ORD_ID|9618 @Micromonas_pusilla_CCMP1545@3586|PACid:27348271
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------EVIAIAADSWITTAGLM
YV----------------------------------------------------------
-------------------------------------------IEYFHLAHGMEWYAAIA
AATCVMRVCAFPLTIMQ------------QKSAGKM--------HLAK------------
-PEMTALQESI--NEARRAGEHERAARLGRVFAIWSKHDVHP------------------
----------------------AKMLAPL----LFQAPVFISFYFAISRMAEG-------
---LPSMR----------D---------GGFAW------FQDL-SIADP-----------
----TFALPIISSLTFLAAVE----FAPQNP---AVKSSQREMTKWGLRALGVAMVPLTA
SFPSGVFVYWITSNVFSFA--QTVLLRVPFAKRAMGIPEDPPP-----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>gnl|BL_ORD_ID|5645 @Ostreococcus_lucimarinus@40894|PACid:27418518
MTT---------------------------------------------------------
----------------------------------------------------------AG
GAAETLT-----------------------------------------------------
---------------------SASDLAPVVGSLAS--------EVVPVASQSWPTTAALM
YA----------------------------------------------------------
-------------------------------------------MEYFHVAHGLEWWLAIV
GATVFMRTITFPLIVMQ------------MRNTAKM--------QLCK------------
-PELEALQAKM--KSNPQQDPELANAYYKEMQKVWKKYDVNP------------------
----------------------VKSFAPI----LINAPVFISFFFAISKMAQG-------
---VPSFE----------S---------GGPSM------YPDL-SMADP-----------
----TYSLPILSSLTFLASVE----LGAVEGMQ----TSQSAQMKWFLRALAVAMVPLTA
SFPQGVFVYWITSNIFSGF--QTSITRTKAFKSTMGIPDVSAV-----------------
-----------------------------------------------------AEAPAEA
ALGRVQLDRFQKKYGATPTLHKRPPTQKQRKK----------------------------
------------------------------------------------------------
--------------------------------------------
>gnl|BL_ORD_ID|3407 69262|PACid:27398672
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------HLAHDMEWWAAIM
ATTAIMRVFVMPFMVMQ------------QRVAARM--------HIAK------------
-PEIEALNARI---KGMGGDQQVMAEAQKEIFAIWKKHNCNP------------------
----------------------AYMMLPI----AVQAPLFISFYFAISEMAKG-------
---VPSFA----------S---------GGPDWPLGPISMHDL-TAADP-----------
----TYIMPVLSSATFLATVE----LGGAGNPETSGAAQQTMMTKWGLRALSVALIPMTA
GFSKGVFVYWITTNMFSLG--QTLAFKVPLIKKIVAIPEIP-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>gnl|BL_ORD_ID|3384 @Chlamydomonas_reinhardtii@_16.g690200.t1.1|PACid:19861677
MAQRWRALQRGAALLAHHTE-SAASTQVLSACSTSASSLLQQITLD--QRGSGGSWQQHQ
HAWGSSSHRTFFSFARKKPDAGAVAAASTG---DETSISGSEPVADPTPVGPPEFFPLPE
SAPDAIE-----------------------------------------------------
---------------------VASAIHQAC-------SALERASIMSAKADAFFSASWCI
SG----------------------------------------------------------
-------------------------------------------LQAVHDLLDTPWFLSIA
IFNITLRLLTFPLMVVA------------QKGSAKMMEFNHNLIHAKK------------
-LQEAAMKATS-QEEHQRLFQAFRNEYNVQTAK-----HGDP------------------
----------------------VKTALVVPGVMILNGAIFLSIFNGVSKLMAAK------
---VPSLT----------T---------GGALW------FSDL-TSPDP-----------
----YFGLPLMCTAVTLAMVEYGINLAGDAGPMPEDRAKMTNGLKNFMRVMAFMFIPAGG
YVAAGTAVLWVSNTAFGVV--QGLTLRNDRFRRRVGLPTMQAL-----------------
----------------------------------RDMNAKVMAANAAGTPASAGAAGASA
AATLAAAADTSAPASAAPLLSNSPVGAKARR-----------------------------
------------------------------------------------------------
--------------------------------------------
>gnl|BL_ORD_ID|131 @Volvox_carteri@_Vocar20001462m|PACid:23123990
MAQRWRSLQRGAALLLHHAEPSASGAPGLLSAYPSASSLILNLKSDQHQHKGGASWHQN-
HAW---TGFIGVRHASTKSSSASVPSSSSGFPDDAPSNSG----MDLTP--PPEFFPLPE
SS--AAE-----------------------------------------------------
---------------------VATAIHQAC-------DALERASLLGAKADAFFAASWCI
SG----------------------------------------------------------
-------------------------------------------LQAVHEMLDTPWWVSIM
LFNISLRLCTFPLMVLA------------QRGSAKMMEFNYALLHAKK------------
-LQEAAMKATN-RAEHDRLFNAFRTEYTAQVSK-----HGDP------------------
----------------------VKTALMVPGVMIFNGFVFLSIFNGISKLMAAKVLRRCA
---VPSLT----------T---------GGALW------FSDL-TQPDP-----------
----FFGLPIMCTLVTLAMVEYGINLAGDAGPMPSERQQATKTMKWVFRVLAFMFIPAGN
YVAAGTALLWVSNTAFGVV--QGMLLRNDGVRQRMGLPSMQEL-----------------
----------------------------------REMNARVLEANSANAPKPSEAPPSIF
SAT-KPSLDT-APAVNVPLMSRPP-GSKGTKGP---------------------------
------------------------------------------------------------
--------------------------------------------
>gnl|BL_ORD_ID|1034 @Ostreococcus_lucimarinus@93298|PACid:27413900
MS----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
DS----------------------------------------------------------
-------------------------------------------MTHLHAATGAPWFVALA
ASAALVRAATAPISART------------IKASATV--------SAAS------------
-----ALAKSRKRGNSEHVGVRDVLDAIGELRGKAPGTGAHP------------------
----------------------AWLVAGP----LAQIPFFLCAVMAVRRLAADGA-----
---NNGLV----------T---------GGALW------FQDL---TVP-AVDVAMMTAP
MGPYGGILPVLTAAALFANVN----ANFASA---AAQSRGMTIVKLVLEWMTLPMLVIGM
QLPQAVHCYWLTSSAWALA--QNRALSTTFAREALGINALAKV-----------------
----------------------------------TREIAASQGLGGEDVAMSPEVLELVK
AAAKERAGNNNAQAVNLLLRAARGGGDVAAALRGEDLGKSHPTVLFALGQTYAVLKEWKK
SALTYEYSARAEPDPLRRSRALMGAGVARARLGDLGMASEALYEANRLNPTDASVKVALA
SALKLNGDPERALEILREAAELQPDIDERYVKPLERELASRTSA
