>gnl|BL_ORD_ID|9070 @Chlamydomonas_reinhardtii@_17.g729800.t1.1|PACid:19867375
M-A------LQMKQSPS-------------------------------------------
-----MGVRRASQPVLPPRPIVHR---GVGSVS------------RRPAVVVKASLLDAA
SAASAVDAVHHA-----TQLY--TLAEGGPIDVLAQFFEFVLQTLDEGLESAKIP-----
-------------------------------Y--SYGFAIIALTVLVKVAT---------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------FPLTQK--------
---------------QVESTLSL--------QALQ-------------PRVKELQAKY-A
DDPEN--------LQLETARLYKEAGVNP-------LAGCFP------------------
-----------T----LATIPVFIGLYNALSNAAKEGLL-TEGFFWIPSLGGPTTI----
-G---------GGLEW------LVPF-ENGAP------PVGWANAAAYLVMPVLLVASQY
ASQK----IIS-SQ---NNQDPSQQQAQAILKFLPLMIGWFSLNVPSGLTLYWFVNNLLS
TG--QQLYLKATV---KVNIPEAIKA------PATAGSSTPIVKPKEERVKK----VTGK
ELGSRKKRR-----------------NDDGEEVEDVEVEVVS--------SGSSSSSGSN
GASGRKGEKFRALKAREAAA--------------KAASTVSAGAGGSEEGKDNSA-----
------------------------------------------------------------
------------------------------------
>gnl|BL_ORD_ID|5658 @Volvox_carteri@_Vocar20010438m|PACid:23129534
M-A------LAMKQYPSA------------------------------------------
-----LGARKPCQPLLPPRPSVRRPGAGIGSGS------------RRAAVCVKASLLDPS
TAASTVEAVQHA-----QNLY--TLADGGPIDLLAQFFTSVLRTLDDGLENAHVP-----
-------------------------------Y--SYGFAIITLTVLVKLAT---------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------FPLTQK--------
---------------QVESTLSL--------QALQ-------------PRVKELQAKH-A
DDPET--------LQLETARMYKEAGVNP-------LAGCLP------------------
-----------T----LATIPVFIGLYNALSNAAKAGLL-TEGFFWIPSLSGPTTI----
-G---------GGLEW------LFPF-QDGAP------PVGWANAAAYLVMPVLLVASQY
ASQK----IISTTQ---NSNDPAQQQSQAILKFLPLMIGWFSLNVPSGLTLYWFVNNLLS
TA--QQLYLKATV---KVNVPESIKA------PVAATSAT-VVKPKEERVKR----ITGK
ELGARKKRR-----------------NEAGEEVEEVDVEIVSTSGSNGAASASPAVNGNG
SGSSRKGEKFRALKAREAAA--------------KAAA----------------------
------------------------------------------------------------
------------------------------------
>gnl|BL_ORD_ID|1260 @Coccomyxa_subellipsoidea@15426|PACid:27386896
MTL---------------------------------------------------------
---------------------------------------------ADTAASSAAQAVGDK
AADAIVSSATAVQSAT-DAAAEAVQRDNGWFGFFTGPFETVLKVLDTGLDKLHVP-----
-------------------------------Y--SYGFSIILLTIFVKALT---------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------FPLSKK--------
---------------QVESTVAI--------QALQ-------------PRVKEIQEKYKG
RDPQE--------AQIEVAKLYQEAKVNP-------LAGCLP------------------
-----------T----LITLPVWIGLYRALSNVADEGLL-SEGFFWIPSLAGPTTLAAQK
AG---------AG-SW------LFPL-VNGAP------PIGWHDASAYLVLPVLLIVSQY
VSQK----IISPPS-----EDPSQQSAQWILKFLPLMIGWFSLNVPSGLTIYWFINNVLS
TA--QQLWLKKTI---QPPALASAGTGTV-------------------------------
--------------------------VNARSSVEDLRPTGETGCPFSLAASAPCK-----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>gnl|BL_ORD_ID|10331 @Micromonas_pusilla_CCMP1545@52221|PACid:27348985
M-Q------ATSATGAGAVARGAVAVAGARASSIRG------------------------
VAA--LPARRASRALAPRRRVAPRRAAVAARASI-GGEFPVFDVINDAVINAHASAMTSD
ALGSIFQVADAA-AVDVEEIP--GLQKGGWLGPITDFLEASLGVIDQGLEGLNVP-----
-------------------------------Y--SYGYAILVLTVVVKLVT---------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------FPLTKK--------
---------------QVEGSIAM--------QALQ-------------PRVKELQAMY-A
NDPER--------LQMETARLYKEANFNP-------LAGCLP------------------
-----------T----FATLPVFIGLYRALSNAATEGML-EDGFYWIPSLGGPTSIAARN
DG---------SGFSW------LWPF-VDGAP------PLGWHDTAAYLALPVLLVVSQF
ASQK----IMTPDQ--GKDVDPSQASSQAILKFLPFMIGFFSLNVPAGLTLYWFANNIFS
TA--QTVYLRKTT---KAPDSIQNVGGGSAAMPMPGTTPAATQPVRVEYVPKSQRKSGGA
--APKPPPPRVEAMPAAVASEFADFDDGPARVTETVEGVVVGGDGADATESAGGGGGGDA
RGKGSKKSKKAAGSRKRRNKSR--------------------------------------
------------------------------------------------------------
------------------------------------
>gnl|BL_ORD_ID|4751 96326|PACid:27400020
M-A------ACVANLGGIARSNALTPVGARGASSSR------------------------
TAGGLLPLRRAGSSGRAVRRV---RSSVAVRASMAGAEFPSFDQVQGAVANVHASFIGND
AVASLFQVADAADAAAPEELK--GLQKGGWLGPITDLLESILKGIDSGFVGLGVP-----
-------------------------------Y--SYGYAILALTVLVKVVT---------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------FPLTKK--------
---------------QVEGSLQM--------QAIQ-------------PRVKELQAMY-A
NDPER--------LQMETARLYKEANFNP-------LAGCLP------------------
-----------T----FATLPVFIGLYRALSNAAVEGEL-TDGFYWIPSLGGPTSIEARN
DG---------NGFAW------LFPF-VDGAP------PLGWHDTIAYLVLPVLLVASQL
ISQK----VMTPDQ--PKSDDPAQQQSQAILKFLPFMIGFFSLNVPAGLTLYWFANNIFS
TA--QTVYLRKTT---KAPEMPAAVAGG---MPMPG-TPASAQPVRVEYVPKSQRKAQGS
VPAPKPAPPKVEPMPESLAAEFGDFDDGPAKIVEPV--VVEAKVVADTTGAAAAAAAGEA
GGKKGGSRKGSKGSRKRKGSRK--------------------------------------
------------------------------------------------------------
------------------------------------
>gnl|BL_ORD_ID|557 @Ostreococcus_lucimarinus@3334|PACid:27413422
------------------------------------------------------------
------------------------------------------------------------
-----------------EALKAAGLQKGGWLGPITDGLESALEGIDSVLDG-RVP-----
-------------------------------Y--SYGFSIIVLTVLVKLAT---------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------FPLSKK--------
---------------QVESSMQM--------QAMQ-------------PRIKELQAMY-A
NDPER--------LQMEQARLYKEAGFNP-------LAGCLP------------------
-----------V----FATLPVFIGLYRALSNAASEGLL-TDGFYWIPSLGGPTSIASRN
AG---------SGFAW------LWPF-VDGHP------PLGWHDTTAYLVLPVLLVASQY
VSQQ----IVSPQP---KTDDPAQQQSQAILKFLPLMIGFFSLNVPAGLTLYWFANNIIT
TA--QTLILRKTT---TAPEPPVAKSGAAG------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>gnl|BL_ORD_ID|5045 @Coccomyxa_subellipsoidea@12888|PACid:27390681
MSRVLHHWR---------------------------------------------------
------------------------------------------------------------
-----------------CSALQAAAQDDGWLAPISSGLNYSLQQIQTGLDQLHVP-----
-------------------------------Y--SYGWAIIVLTVGTKILT---------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------FPFTK---------
----------------VESALAV--------QKLK-------------PTIDAIKRQY-G
EDKNS--------IQRETSALYEASGVNP-------AAGCLP------------------
-----------T----LATIPIFWGLYRTLSNVASAGLL-TEGFYWIPSLSGPTSLAAQR
AG---------TGTAW------LFPF-VDGAP------PVGWEDAARYLALPIALVAAQF
ASSA----VISPPI---DDEDKNAAFSKGLLIAVPFMVGWFALNVPSGLSLYYFSNTIIT
SG--IQIWLRKLG---GAYSPLLLLTFIH--WPTVRACSSFLCCPRQANSCASLFLVPGN
HLFACWARRDFYVQLSW-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>gnl|BL_ORD_ID|5308 @Chlamydomonas_reinhardtii@_06.g251900.t1.1|PACid:19863606
M-----------------------------------------------------------
-------------------------------------------------------YVLAD
ASASTAAAAVMPTAVD-SAAGAAPQRAGGWVAPVADALEQVLYALQEGLDKLHVP-----
-------------------------------Y--SYGYSIILLTLIVKLLT---------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------YPLTKQ--------
---------------QVESAMAV--------QALK-------------PRIDLIKDRF-G
EDKDK--------IQKETSVLYEQAGVNP-------LAGCLP------------------
-----------T----LATIPIFIGLFSSLTNVANDGLLDTQGFYFVPSLAGPTTMAMRQ
SG---------LGTSW------LWPLGPDGAP------PIGWEDAAAYLTLPLLLVAVQY
ASSS----VTSPPI---DPKDENANTQRALLVFLPLMVGWFSLNVPAGLSLYYLANTVLS
SA--IQIYLKKLG---GANVVMNELGPVT--KPGSGRRNGVAAGEWSVWKPA----TVL-
TTAEAAKAR-----------------AEAEEAVERAREAAEEAAAAAAFDNASVSLSVDD
STAAIAGTATMAVTAGATAAAMDPSKVNRRCKRRRLTSLVQDGSTASAAVAGASA-----
------------------------------------------------------------
------------------------------------
>gnl|BL_ORD_ID|4166 @Volvox_carteri@_Vocar20003543m|PACid:23128036
MAT------LRYRPVAQRVKRNAHFRYAIRYAARNV------------------------
LVDLPCPGRLRGSSYRAGSEITLLTSHLSA---------GIPDYLDRADLLPTFSFPLAN
AGAASESVAAAVTANI-LSASPTDQRAGGWVAPLADVLEQVLYVLKDCLDLLHVP-----
-------------------------------Y--SYGYSIILLTLIVKIVT---------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------YPLTKQ--------
---------------QVESTLAV--------QALK-------------PRVDLIKDRF-G
DDKEK--------IQKETSILYEQAGVNP-------LAGCLP------------------
-----------T----LATTPIFIGLYSSLTNVANEGLLDTQGFYWIPSL----------
--------------------------------------------------------AVQY
ASLY----STGPTS---DATDVNARLQRALLLGLPVMIGWFALNVPSGLSLYYLSNTILS
TA--QQVYLKKLG---GAKVAIKKLGPIM--KPGSGRRSGAPEAELKLWVSA----TTFK
STAERGKNS-----------------LNMEGPVELARNA----------------LDTDL
PETTAALTDVIKSSQTDSSPLVDLSNVNRFCKRRRLSSLVQDGANGAQIFPAATTSV---
------------------------------------------------------------
------------------------------------
>gnl|BL_ORD_ID|3956 @Micromonas_pusilla_CCMP1545@31798|PACid:27342602
MTS------QGCSSGSLVCRGARGLYRCGRQTGCPR------------------------
RDTSLLSRRTRPRSFDASCGAISATDIGESITIVPDVITAAIFASEQIADLSESTFTVGA
TVVDSSHATLFAELSA-LTEITGPQRMEGILSPVSDLLEEFVLATQRYFSDAGVR-----
-------------------------------Y--PLGSSIIFTTFVVKALT---------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------YPFTKV--------
---------------QVESALNM--------QNLQ-------------PQVNAVREKY-R
DDQEQ--------MNIEINRLYEDNQVSP-------LAGCGP------------------
-----------L----LLTLPVVWGLYRAFNNASIDGSF-DEPWFFIPSLAGPTP-----
-D---------RSLAW------LLPLDDNYQP------PLGWHDASLYLVVPILTVASQY
VSMS----ILSPVKDLNDPNTAETEQQSFLLNFLPLFIGYISLTVPAGLTLYWLFNNIFT
TA--TQVYLRQGG---GAVAKVEKIKDVK--LKVPLGCAIVDQNSTDQLSVHDVFEGPYV
LVTDSGEID-----------------LAYSGEIDLAYSALPDHDKAYGFYLSPELRSAKT
DKWRLHMEKRGKRSLDPAERYNATPEELRLLISEYLKLGMVAEAEEISVELGRLGSETER
SDPL--------------------------------------------------------
------------------------------------
>gnl|BL_ORD_ID|3977 @Ostreococcus_lucimarinus@3329|PACid:27416850
------------------------------------------------------------
------------------------------------------------------------
-----------AAKIA-SGEIAAPQRMEGWLAPVSDALEDLLFAIQGQLQGLGVP-----
-------------------------------Y--STGNAIIIVTILVKFVT---------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------YPLTRD--------
---------------QVVSSLNM--------KNLQ-------------PQIAAIREKY-E
DDQER--------MNKEINRVYEENGVNP-------LAGCGP------------------
-----------A----LLTFPVLAGLYRAFNNAGIDGAF-DEAWFFLPSLAGPTD-----
-A---------RDLSW------LLPLDSDYAP------PIGWEEASLYLIFPVLTTISQF
VSME----VLKPEE---TEKTDEMKNQSVLLKLLPLFIGYISLTVPAGLALYWFWNNVFT
TG--IQVFLRN-G---GAKATVE-------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>gnl|BL_ORD_ID|7951 @Coccomyxa_subellipsoidea@39658|PACid:27393587
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------MKLRRWLTIIYTTIGARLLT---------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------LPLVVK--------
---------------QQRNTANM--------TMAR-------------PEMMALKDWY-T
EETARGNPKATTEYQQRLANLWQKYDCNP-------FKSMLG------------------
-----------I----LAQAPLFIGFFSALRALSAAK---------VPSMT---------
-E---------GGVAW------FTDL-TLADP---------------YYALPIMSSAVFL
LTVE----L-GAADGMQGQDEAMLRRMKNIFRAIGVAMVPLTASFPQGVFLYWVTSNIFS
LG--QSVLFKLPAVRKTLKLPDLAKM----------------------------------
---------------------------------------------RATATGLPITEA---
------GKPLVTFAQPPKQRKAKTT-----------------------------------
------------------------------------------------------------
------------------------------------
>gnl|BL_ORD_ID|9618 @Micromonas_pusilla_CCMP1545@3586|PACid:27348271
------------------------------------------------------------
------------------------------------------------------------
-----------------------------EVIAIAADSWITTAGLMYVIEYFHLA-----
-------------------------------HGMEWYAAIAAATCVMRVCA---------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------FPLTIM--------
---------------QQKSAGKM--------HLAK-------------PEMTALQESI--
NEARRAGEHERAARLGRVFAIWSKHDVHP-------AKMLAP------------------
-----------L----LFQAPVFISFYFAISRMAEG----------LPSMR---------
-D---------GGFAW------FQDL-SIADP---------------TFALPIISSLTFL
AAVE----F-APQNPAVK--SSQREMTKWGLRALGVAMVPLTASFPSGVFVYWITSNVFS
FA--QTVLLRVPFAKRAMGIPEDPPP----------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>gnl|BL_ORD_ID|5645 @Ostreococcus_lucimarinus@40894|PACid:27418518
MTT---------------------------------------------------------
----------------------------------------------------------AG
GAAETLTSASDLAPVVGSLAS--------EVVPVASQSWPTTAALMYAMEYFHVA-----
-------------------------------HGLEWWLAIVGATVFMRTIT---------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------FPLIVM--------
---------------QMRNTAKM--------QLCK-------------PELEALQAKM--
KSNPQQDPELANAYYKEMQKVWKKYDVNP-------VKSFAP------------------
-----------I----LINAPVFISFFFAISKMAQG----------VPSFE---------
-S---------GGPSM------YPDL-SMADP---------------TYSLPILSSLTFL
ASVE----LGAVEGMQ----TSQSAQMKWFLRALAVAMVPLTASFPQGVFVYWITSNIFS
GF--QTSITRTKAFKSTMGIPDVSAV----------------------------------
---------------------------------------------AEAPAEAALGRVQLD
RFQKKYGATPTLHKRPPTQKQRKK------------------------------------
------------------------------------------------------------
------------------------------------
>gnl|BL_ORD_ID|3407 69262|PACid:27398672
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------HLA-----
-------------------------------HDMEWWAAIMATTAIMRVFV---------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------MPFMVM--------
---------------QQRVAARM--------HIAK-------------PEIEALNARI--
-KGMGGDQQVMAEAQKEIFAIWKKHNCNP-------AYMMLP------------------
-----------I----AVQAPLFISFYFAISEMAKG----------VPSFA---------
-S---------GGPDWPLGPISMHDL-TAADP---------------TYIMPVLSSATFL
ATVE----LGGAGNPETSGAAQQTMMTKWGLRALSVALIPMTAGFSKGVFVYWITTNMFS
LG--QTLAFKVPLIKKIVAIPEIP------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>gnl|BL_ORD_ID|3384 @Chlamydomonas_reinhardtii@_16.g690200.t1.1|PACid:19861677
MAQRWRALQRGAALLAHHTE-SAASTQVLSACSTSASSLLQQITLD--QRGSGGSWQQHQ
HAWGSSSHRTFFSFARKKPDAGAVAAASTG---DETSISGSEPVADPTPVGPPEFFPLPE
SAPDAIEVASAIHQAC-------SALERASIMSAKADAFFSASWCISGLQAVHDL-----
-------------------------------LDTPWFLSIAIFNITLRLLT---------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------FPLMVV--------
---------------AQKGSAKMMEFNHNLIHAKK-------------LQEAAMKATS-Q
EEHQRLFQAFRNEYNVQTAK-----HGDP-------VKTALV------------------
-----------VPGVMILNGAIFLSIFNGVSKLMAAK---------VPSLT---------
-T---------GGALW------FSDL-TSPDP---------------YFGLPLMCTAVTL
AMVEYGINLAGDAGPMPEDRAKMTNGLKNFMRVMAFMFIPAGGYVAAGTAVLWVSNTAFG
VV--QGLTLRNDRFRRRVGLPTMQAL----------------------------------
--------------------------RDMNAKVMAANAAGTPASAGAAGASAAATLAAAA
DTSAPASAAPLLSNSPVGAKARR-------------------------------------
------------------------------------------------------------
------------------------------------
>gnl|BL_ORD_ID|131 @Volvox_carteri@_Vocar20001462m|PACid:23123990
MAQRWRSLQRGAALLLHHAEPSASGAPGLLSAYPSASSLILNLKSDQHQHKGGASWHQN-
HAW---TGFIGVRHASTKSSSASVPSSSSGFPDDAPSNSG----MDLTP--PPEFFPLPE
SS--AAEVATAIHQAC-------DALERASLLGAKADAFFAASWCISGLQAVHEM-----
-------------------------------LDTPWWVSIMLFNISLRLCT---------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------FPLMVL--------
---------------AQRGSAKMMEFNYALLHAKK-------------LQEAAMKATN-R
AEHDRLFNAFRTEYTAQVSK-----HGDP-------VKTALM------------------
-----------VPGVMIFNGFVFLSIFNGISKLMAAKVLRRCA---VPSLT---------
-T---------GGALW------FSDL-TQPDP---------------FFGLPIMCTLVTL
AMVEYGINLAGDAGPMPSERQQATKTMKWVFRVLAFMFIPAGNYVAAGTALLWVSNTAFG
VV--QGMLLRNDGVRQRMGLPSMQEL----------------------------------
--------------------------REMNARVLEANSANAPKPSEAPPSIFSAT-KPSL
DT-APAVNVPLMSRPP-GSKGTKGP-----------------------------------
------------------------------------------------------------
------------------------------------
>gnl|BL_ORD_ID|1034 @Ostreococcus_lucimarinus@93298|PACid:27413900
MSD---------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------SMTHLHAA-----
-------------------------------TGAPWFVALAASAALVRAAT---------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------APISAR--------
---------------TIKASATV--------SAAS-------------ALAKSRKRGN--
--------SEHVGVRDVLDAIGELRGKAP-------GTGAHP------------------
---------AWLVAGPLAQIPFFLCAVMAVRRLAADGAN--------NGLV---------
-T---------GGALW------FQDL---TVP-AVDVAMMTAPMGPYGGILPVLTAAALF
ANVN-----ANFASAAAQ--SRGMTIVKLVLEWMTLPMLVIGMQLPQAVHCYWLTSSAWA
LA--QNRALSTTFAREALGINALAKV----------------------------------
--------------------------TREIAASQGLGGEDVAMSPEVLELVKAAAKERAG
NNNAQAVNLLLRAARGGGDVAAALRGEDLGKSHPTVLFALGQTYAVLKEWKKSALTYEYS
ARAEPDPLRRSRALMGAGVARARLGDLGMASEALYEANRLNPTDASVKVALASALKLNGD
PERALEILREAAELQPDIDERYVKPLERELASRTSA
>gnl|BL_ORD_ID|13549 @Chlamydomonas_reinhardtii@_03.g198150.t1.2|PACid:19871867
MQR---------------------------------------------------------
-----------------------CGGLVTRLLSRSVSAASKRDAAAACTGLGPWGVLCFR
GISSTSSPDTGVLQVQPQAADAFNAVAHSSLEDGLAMILSPTQLGVQLWEVAHAS-----
-------------------------------TGLPWWAAIPVATVGVRTML---------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------MPLSLR--------
---------------AYAASSYL--------ALLHRAFGLSREVGDAVAEAEATERRQRG
ESAGSASVSEGSAVAGETSA--SSSGSSPHSTGRKRNAAVVDGARALGRMELVRHVVAHL
HKGSNAPSLSWYVANGAVQMPIVISLTLALRRMCDSL---------WPGLT---------
-S---------EGALY------FTDL---TAP-PVYLQTLSTPYGTAGAILPLGLMLLYA
SAVD-------------RSRGGSSPGINVALKLCAIPLYIAALQQPHAVLLYWLSHAATQ
LGVYQVAVLMEPK-----------------------------------------------
----------------------------QTASTEATQTDQGDASLDDLLLVLSDSYEKAG
NKAAARACLQALSVRQPGLGSVQERLKQLDTTSGV-------------------------
------------------------------------------------------------
------------------------------------
>gnl|BL_ORD_ID|13190 @Chlamydomonas_reinhardtii@_03.g175100.t1.2|PACid:19871508
MAC---------------------------------------------------------
-----AGEGKFTGKDPAALPTLVVRFSGSGWLLAFHCGVGKFAYDHLRVDHPRLRFGGQS
GGSLISSALTAGMDVDCVYEASLM-----MIEPCKHNPFRMRKCLNEALDRLAPPDEAWI
RAKHRLIVGMSRIEHLGGAKIAWKSTNLTEFRGRAHGLRVLEASCHLPVISGLRGVDVDG
HRFFDGGVAELVPDITPEQIGLNSDPAKGPVDPVFSIDICSWGNLGEGYHICPGFDVPVG
WFFFPHNSGVLNKLFRLGYARAAECFAKVDPAIMADLWRPGMELSLSYLPGICEQVDELV
SYLREADPFCCIDAMLSSRKKYSKPQLSRLAQMHIPQLPMAQSSELLPLIAKAELSKIPG
PVDGGVKGGAQAVPEAAQPTGQL--------RVAM-------------PHTPALAKEQEE
QEQRRVTANGRSAGAAQQEERRNGSGTAAGGDASGGLQSSLP------------------
------------------------------AGAACAGTGHSMQLPGAPPVANISTSAAAA
DGADGCTAARRGSTAY-----------SVATPTAVDAAAALMSGSGSTASLPAVLAAHLG
AGSD-------YAGSAPDSPCAAAGPPRHSLRPM-----------PPLRPTTWLKDDSLR
TA--SLQNMAKRGSRVAPLPPLMGVL----------------------------------
------------------------------------------------------------
--SAPAPDSSTAGGSPP-------------------------------------------
------------------------------------------------------------
------------------------------------
