>gnl|BL_ORD_ID|9070 @Chlamydomonas_reinhardtii@_17.g729800.t1.1|PACid:19867375
MALQMKQSPS----------------MGVR------------------------RASQPV
LPPRPIVHRGVGSVSRRPAVVVKASLLDAASAASAV---DAVHHATQLYTLAEGGPIDVL
AQFFEFVLQTLDEGLESAKIPYSYGFAIIALTVLVKVATFPLTQKQVESTLSLQALQPRV
KELQAKYADDPENLQLETARLYKEAGVNPLAGCFPTLATIPVFIGLYNALSNAAKEGLL-
TEGFFWIPSLGGPTTI-----GGGLEWLVPF-ENGAPPVGWANAAAYLVMPVLLVASQYA
SQKIISSQ-NNQDPSQQQAQAILKFLPLMIGWFSLNVPSGLTLYWFVNNLLSTGQQLYLK
--ATVKVNIPE------------------------------------AIKAPATAGSSTP
IVKPKEERVK--KVTGKELGSRKKRRNDDGEEVEDVEVEVVSSGSSSSSGSNGASGRKGE
KFRALKAREAAAKAASTVSAGAGGSEEGKDNSA
>gnl|BL_ORD_ID|5308 @Chlamydomonas_reinhardtii@_06.g251900.t1.1|PACid:19863606
M-----------------------------------------------------------
-------------------YVLADASASTAAAAVMP---TAVDSAAGAAPQRAGGWVAPV
ADALEQVLYALQEGLDKLHVPYSYGYSIILLTLIVKLLTYPLTKQQVESAMAVQALKPRI
DLIKDRFGEDKDKIQKETSVLYEQAGVNPLAGCLPTLATIPIFIGLFSSLTNVANDGLLD
TQGFYFVPSLAGPTTMAMRQSGLGTSWLWPLGPDGAPPIGWEDAAAYLTLPLLLVAVQYA
SSSVTSPPIDPKDENANTQRALLVFLPLMVGWFSLNVPAGLSLYYLANTVLSSAIQIYLK
KLGGANVVMNELGPVTKPGSGRRNGVAAGEWSVWKPATVLTTAEAAKARAEAEEAVERAR
EAAEE---AAAAAAFDNASVSLSVDDSTAAIAGT------ATMAVTAGATAAAMDPSKVN
R------RCKRRRLTSLVQDGSTASAAVAGASA
>gnl|BL_ORD_ID|1260 @Coccomyxa_subellipsoidea@15426|PACid:27386896
M-----------------------------------------------TLADT-------
--------------AASSAAQAVGDKAADAIVSSATAVQSATDAAAEAVQRDNGWF----
-GFFTGPFETVLKVLDTGLDKLHVPYSYGFSIILLTIFVKALTFPLSKKQVESTVA----
--IQALQPRVKEIQEKYKGRD------------------PQEAQIEVAKLYQEAKVNPLA
GCLPTLITLPVWIGLYRALSNVADEGLLSEGFFWIPSLAGPTTLAAQK---------AGA
G-SWLFPLVNGAPPIGWHDASAYLV-----------LPVLLIVSQYVS-------QKIIS
PP-SEDPSQQSA---------QWILKFLPLMIGWFSLNVPSGLTIYWFINNVLSTAQQLW
L-----KKTIQPP-----------ALASAGTGTVVNARSSVED--LRPTGET--------
----------------------GCPF----------------------------------
-----------SLAA--SAPCK--------------------------------------
------------------------------------------------------------
-----------
>gnl|BL_ORD_ID|5045 @Coccomyxa_subellipsoidea@12888|PACid:27390681
MSRVLHHWRC--------------------------------------------------
-------------------------------------------SALQAAAQDDGWL----
-APISSGLNYSLQQIQTGLDQLHVPYSYGWAIIVLTVGTKILTFPFTK--VESALA----
--VQKLKPTIDAIKRQY-GED------------------KNSIQRETSALYEASGVNPAA
GCLPTLATIPIFWGLYRTLSNVASAGLLTEGFYWIPSLSGPTSLAAQR---------AGT
GTAWLFPFVDGAPPVGWEDAARYLA-----------LPIALVAAQFAS-------SAVIS
PP-IDDEDKNAA-------FSKGLLIAVPFMVGWFALNVPSGLSLYYFSNTIITSGIQIW
L-----RKLGGAYSPLLLLTFIHWPTVRACSSFLCCPRQAN-------------------
------------------------------------------------------------
-----------SCASLFLVPGNHLFACWARRDFYVQLSW---------------------
------------------------------------------------------------
-----------
>gnl|BL_ORD_ID|7951 @Coccomyxa_subellipsoidea@39658|PACid:27393587
M-----------------------------------------------------------
--------------------------------------------------KLRRWL----
------------------------------TIIYTTIGARLLTLPLVVKQQRNTAN----
--MTMARPEMMALKDWY-TEETA----------RGNPKATTEYQQRLANLWQKYDCNPFK
SMLGILAQAPLFIGFFSALRALSAAK--------VPSM-------------------TEG
GVAWFTDLTLADP---------YYA-----------LPI-MSSAVFLL-------TVELG
AA-DGMQGQDEA----MLRRMKNIFRAIGVAMVPLTASFPQGVFLYWVTSNIFSLGQSVL
FKLPAVRKTLKLP-------DLAKMRATATGLPITEAGKPLVT--FAQPPKQ--------
------------------------------------------------------------
-----------------------------------RKAKTT-------------------
------------------------------------------------------------
-----------
>gnl|BL_ORD_ID|10331 @Micromonas_pusilla_CCMP1545@52221|PACid:27348985
M------QATSATGAGAVARGAVAVAGARASSIRG---VAALPARRASRALAPRRRVAPR
RAAVAARAS--IGGEFPVF-DVINDAVINA-HASAMTSDALGSIFQVADA--AAVDVE--
---EIPGLQK-GGWLGPITDFLEASLGVIDQGLEGLNVPYSYGY-----------AILVL
TVVVKLVTFPLTKKQVEGSIAMQALQPRVKELQA-----MYANDPERLQM--ETARLYKE
ANFNPLAGCLPTFATLPVFIGLYRALSNAATEGMLEDGFYWIPSLGGPTSIAARNDGSGF
SWLWPFVDG-APPLGWHDTAAYLALPVL-----LVVSQFASQKIMTPDQGKDVDPSQASS
QA---I--LKFLPFMIGFFSLNVPAGLTLYWFANNIFSTAQTVYLRKTTKAPDSIQN---
--VGGGSAAMPM--------------------------------------------PGTT
PAATQPVRVEYVPKSQRKS-------GGAAPKPPPPRVEAMPAAVASEFA----------
---DFDDGPARVTETVEGVVVGGDGADATE-SAGGGGGGDARGKGSKKSKKAAGSRKRRN
KSR
>gnl|BL_ORD_ID|3956 @Micromonas_pusilla_CCMP1545@31798|PACid:27342602
M------------TSQGCSSGSLVCRGARGLYRCG---RQTGCPRRDTSLLSRRTRPRSF
DASCGAISATDIGESITIVPDVITAAIFASEQIADLSESTFTVGATVVDSSHATLFAELS
ALTEITGPQRMEGILSPVSDLLEEFVLATQRYFSDAGVRYPLGS-----------SIIFT
TFVVKALTYPFTKVQVESALNMQNLQPQVNAVRE-----KYRDDQEQMNI--EINRLYED
NQVSPLAGCGPLLLTLPVVWGLYRAFNNASIDGSFDEPWFFIPSLAGPT------PDRSL
AWLLPLDDNYQPPLGWHDASLYLVVPIL-----TVASQYVSMSILSPVKDLN-DPNTAET
EQQSFL--LNFLPLFIGYISLTVPAGLTLYWLFNNIFTTATQVYLRQGGGAVAKVEK---
--IKDVKLKVPLGCAIVDQNSTDQLSVHDVFEGPYVLVTDSGEIDLAYSGEIDLAYSALP
DHDKAYGFYLSPELRSAKTDKWRLHMEKRGKR----SLDPAERYNATPEELRLLISEYLK
LGMVAEAEEISVEL--------GRLGSETERSDPL-------------------------
---
>gnl|BL_ORD_ID|9618 @Micromonas_pusilla_CCMP1545@3586|PACid:27348271
------------------------------------------------------------
------------------------------------------------------------
----------------------EVIAIAADSWITTAGLMYVIEYFHLAHGMEWYAAIAAA
TCVMRVCAFPLTIMQQKSAGKMHLAKPEMTALQESINEARRAGEHERAARLGRVFAIWSK
HDVHPAKMLAPLLFQAPVFISFYFAISRMA-EGL--------PSM----------RDGGF
AWFQDLSIA-DP---------TFALPIISSLTFLAAVEFAPQ-----------NPAVKSS
QREMTKWGLRALGVAMVPLTASFPSGVFVYWITSNVFSFAQTVLLR--------------
--VPFAKRAMGI------------------------------------------------
------------------------------PEDPPP------------------------
------------------------------------------------------------
---
>gnl|BL_ORD_ID|4751 96326|PACid:27400020
MAACVAN-----LGG--IARSNALTPVGARGASSSRTAGGLLPLRRAGSSGRAVRRVRSS
VAVRASMAGAEFPSFDQVQGAVANVHASFIGNDAVASLFQVADA----ADAAAPEELKGL
QK-GGWLGPITDLLESILKGIDSGFVGLGVPYSYGYAILALTVLVKVVTFPLTKKQVEGS
LQMQAIQPRVKELQAM---YANDPERL---QMETARLYKEANFNPLAGCLPTFATLPVFI
GLYRALSNAAVEGELTDGFYWIPSLGGPTSIEARNDGNGFAWLFPFVDGAPPLGWHDTIA
---YLVLPVLLVASQLISQKVMTPDQPKSDDPAQQQSQAILKFLPFMIGFFSLNV--PAG
LTLYWFANNIFSTAQTV-----YLRKTTKA-PEMPAAVAGGMPMPGTPAS-AQP----VR
VEYVPKSQRKAQGSVPAPKPAPPKVEPMPESLAAEFGDFDDGPAKIVEPVVVEAKVVADT
TGAAAAAAAGEAGGKKGGSRKGSKGSRKRKGSRK
>gnl|BL_ORD_ID|3407 69262|PACid:27398672
HLAHDME-----------------------------------------------------
------------------------------------------------------------
-----WWA----------------------------AIMATTAIMRVFVMPFMVMQQRVA
ARMHIAKPEIEALNARIKGMGGDQQVMAEAQKEIFAIWKKHNCNPAYMMLPIAVQAPLFI
SFYFAISEMAKG---------VPSF----------ASGGPDWPL------GPISMHDLTA
ADPTYIMPVLSSATFLATVELGGAGNPETSGAAQQTMMTKWGLRALSVALIPMTAGFSKG
VFVYWITTNMFSLGQTLAFKVPLIKKIVAI-PEIP-------------------------
------------------------------------------------------------
----------------------------------
>gnl|BL_ORD_ID|557 @Ostreococcus_lucimarinus@3334|PACid:27413422
------------------------------------------------------------
---------------------------------------EALKAAGLQKGGWLGPITDGL
ESALEGIDSV-----------LDG-RVPYS--YGFSIIVLTVLVKLATFPLSKKQVESSM
QMQAMQPRIKELQAMYANDPER-------LQMEQARLYKEAGFNPLAGCLPV------FA
TLPVFIGLYRALSNAASE----GLLTDGFYWIPSL--GGPTSIASRNAGSGFAWLWPF-V
DGHPPLGWHDTTAYLVLPVLLVASQYVSQQIVSPQPKTDDPAQQQSQAILKFLPLMIGFF
SLNVPAGLTLYWFANNIITTAQTLILRKTTTAP---EPPVAKSGAAG-------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-
>gnl|BL_ORD_ID|3977 @Ostreococcus_lucimarinus@3329|PACid:27416850
------------------------------------------------------------
----------------------------------AAKIASGEIAAPQRMEGWLAPVSDAL
EDLLFAIQGQ-----------LQGLGVPYS--TGNAIIIVTILVKFVTYPLTRDQVVSSL
NMKNLQPQIAAIREKYEDDQER-------MNKEINRVYEENGVNPLAGCGPA------LL
TFPVLAGLYRAFNNAGID----GAFDEAWFFLPSL--AGPTD------ARDLSWLLPLDS
DYAPPIGWEEASLYLIFPVLTTISQFVSMEVLKPEETEKTDEMKNQSVLLKLLPLFIGYI
SLTVPAGLALYWFWNNVFTTGIQVFLRN-GGAKATVE-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-
>gnl|BL_ORD_ID|5645 @Ostreococcus_lucimarinus@40894|PACid:27418518
------------------------------------------------------------
------------------------------------MTTAGGAAETLTSASDLAPVVGSL
ASEVVPVASQSWPTTAALMYAMEYFHVAHGLEWWLAIVGATVFMRTITFPLIVMQMRNTA
KMQLCKPELEALQAKMKSNPQQDPELANAYYKEMQKVWKKYDVNPVKSFAPI------LI
NAPVFISFFFAISKMAQG-------------VPSFESGGPSM------------------
--YPDLSMADPTY--SLPILSSLTFLASVELG-AVEGMQTSQSAQMKWFLRALAVAMVPL
TASFPQGVFVYWITSNIFSGFQTSITRTKAFKSTMGIPDVSAVAEAPA------------
------------------------------------------------------------
--------------------------------EAALGRVQLDRFQKKYGATPTLHKRPPT
QKQRKK------------------------------------------------------
-
>gnl|BL_ORD_ID|1034 @Ostreococcus_lucimarinus@93298|PACid:27413900
------------------------------------------------------------
-------------------------------------------------------MSDS-
---------------------MTHLHAATGAPWFVALAASAALVRAATAPISARTIKASA
TVSAASALAKS---RKRGNSEH-----VGVRDVLDAIGELRGKAPGTGAHPAWLVAGPLA
QIPFFLCAVMAVRRLAADGANNGLVTGGALWFQDL--TVPAVDVAMMTA-----------
----PMGPYGG----ILPVLTAAALFANVNANFASAAAQSRGMTIVKLVLEWMTLPMLVI
GMQLPQAVHCYWLTSSAWALAQNRALSTTFAREALGINALAKVTREIAASQGLGGEDVAM
SPEVLELVKAAAKERAGNNNAQAVNLLLRAARGGGDVAAALRGEDLGKSHPTVLFALGQT
YAVLKEWKKSALTYEYSARAEPDPLRRSRALMGAGVARARLGDLGMASEALYEANRLNPT
DASVKVALASALKLNGDPERALEILREAAELQPDIDERYVKPLERELASRTS--------
A
>gnl|BL_ORD_ID|5658 @Volvox_carteri@_Vocar20010438m|PACid:23129534
MA---------LAMKQ---YPSALGARKPCQPLLPPRPSVRR-------PGAGIG---SG
SR------------RAAVCVKASL--------LDPSTAA-----STVEAVQHAQNLYTLA
D--------------------GGPIDLLAQFFTSVLRTLDDGLENAHVPYSYGFAIITLT
------VLVKLATFPLTQKQVESTLSLQALQPRVKELQAKHADDPETLQLETARMYKEAG
VNPLAGCLPTL----ATIPVFIG-----------------------LYNALSNAAKAGLL
-TEGFFWI-PSLSGPTTI------GGGLEWLFPFQDGAPPVGWANAA-------------
---AYLVMPVLLVASQYASQKII---------------STTQNSNDPAQQQSQAILKFLP
LMIGWF--SLNVPSGLTL----YWFVNNLLSTAQQLYLK--ATVKVNVPESIKAPVAATS
A--TVVKPKE--------------ERVKRITGKELGARKKRRN---------EAGEEVEE
--VDVEIVSTSGSN-----GAASASPAVNGNGS-GSSRKGEKFRALKAREA-------AA
KAAA
>gnl|BL_ORD_ID|4166 @Volvox_carteri@_Vocar20003543m|PACid:23128036
MA----------TLRY---RPVAQRVKRNAHFRYAIRYAARNVLVDLPCPGRLRG---SS
-----YRAGSEITLLTSHLS----AGIPDY--LDRA-DL-----LPT-FSFPLANAGAAS
ESVAAAVTANILSASPTDQRAGGWVAPLADVLEQVLYVLKDCLDLLHVPYSYGYSIILLT
------LIVKIVTYPLTKQQVESTLAVQALKPRVDLIKDRFGDDKEKIQKETSILYEQAG
VNPLAGCLPTL----ATTPIFIG-----------------------LYSSLTNVANEGLL
DTQGFYWI-PSL------------------------------------------------
-------------AVQYASLYST---------------GPTSDATDVNARLQRALLLGLP
VMIGWF--ALNVPSGLSL----YYLSNTILSTAQQVYLKKLGGAKVAI-KKLGPIMKPGS
GRRS-------------------GAPEAELKLWVSATTFKSTAERGKNSLNMEGPVELAR
NALDTDLPETTAALTDVIKSSQTDSSPLVDLSNVNRFCKRRRLSSLVQDGANGAQIFPAA
TTSV
>gnl|BL_ORD_ID|9070 @Chlamydomonas_reinhardtii@_17.g729800.t1.1|PACid:19867375
MALQMKQS---------PSMGV--RRASQPVLPPRPIVHRGVGSVSRRPAVVVKA-----
----------------SLLDAA-SAASAVDAVHHATQLYTL-------------------
---AEGGPIDVLAQFFEFVLQTLDEGLESAKIPY-----------SYGFAIIALTVLVKV
ATFPLTQKQVESTL----SLQALQPRVKELQAKYADDPENLQLETARLYKEAGVNPLAGC
FPTLATIPVFIGLYNALSNAAKEGLL-TEGF---------------------FWIP----
SLGGPTTI-----GGGLEWLVPF-ENGAPPVGWANAAAYLVMPVLLVASQYASQKIISSQ
-NNQDPSQQQAQAILKFLPLMIGWFSLNVPSGLTLYWFVNNLLSTGQQLYLKATVKVNIP
EAIKAPATAGSSTPIVKPKEERVKKVTGKELGSRKKRRNDDGEEVEDVEVEVVSSGSSSS
SGSNGASGRKGEKFRALKAREA-----------AAKAASTVSAGAGGSEEGKD-------
-----------NSA----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------
>gnl|BL_ORD_ID|5308 @Chlamydomonas_reinhardtii@_06.g251900.t1.1|PACid:19863606
M-------------------------------------------------YVLAD-----
----------------ASASTA-AAAVMPTAVDSAAGAAPQ-------------------
---RAGGWVAPVADALEQVLYALQEGLDKLHVPY-----------SYGYSIILLTLIVKL
LTYPLTKQQVESAM----AVQALKPRIDLIKDRFGEDKDKIQKETSVLYEQAGVNPLAGC
LPTLATIPIFIGLFSSLTNVANDGLLDTQGF---------------------YFVP----
SLAGPTTMAMRQSGLGTSWLWPLGPDGAPPIGWEDAAAYLTLPLLLVAVQYASSSVTSPP
IDPKDENANTQRALLVFLPLMVGWFSLNVPAGLSLYYLANTVLSSAIQIYLKKLGGANV-
-------VMNELGPVTKPGSGRRNGVAAGEWS------------VWKPATVL--------
--TTAEAAKA----RAEAEEAVERAREAAEEAAAAAAFDNASVSLSVDDSTAAIAGTATM
AVTAGATAAAMDPSKVNRRCKRRRLTS-----LVQDGSTASAAVAGASA-----------
------------------------------------------------------------
------------------------------------------------------------
----------
>gnl|BL_ORD_ID|13190 @Chlamydomonas_reinhardtii@_03.g175100.t1.2|PACid:19871508
MACAGEGKFTGKDPAALPTLVV--RFSGSGWLL---AFHCGVGKFAYDHLRVDHPRLRFG
GQSGG-----------SLISSALTAGMDVDCVYEASLMMIEPCKHNPFRMRKCLNEALDR
LAPPDEAWIR--AKHRLIVGMSRIEHLGGAKIAWKSTNLTEFRGRAHGLRVLEASCHLPV
IS-GLRGVDVDGHRFFDGGVAELVPDITPEQIGLNSDPAKGPVDPVFSIDICSWGNLGEG
YHICPGFDVPVGWFFFPHNS---GVL-NKLFRLGYARAAECFAKVDPAIMADLWRPGMEL
SLSYLPGI-----CEQVDELVSY-LREADPFCCIDA-------MLSSRKKYSKPQLSRLA
-QMHIPQLPMAQS-SELLPLIAKAELSKIP------------------------------
------------GPV--------------------------------------DGGVKGG
AQAVPEAAQPTGQLRVAMPHTPALAKEQEEQEQRRVTANGRSAGAAQQEERRN-------
-----------GSGTAAGGDASGGLQSSLPAGAACAGTGHSMQLPGAPPVANISTSAAAA
DGADGCTAARRGSTAYSVATPTAVDAAAALMSGSGSTASLPAVLAAHLGAGSDYAGSAPD
SPCAAAGPPRHSLRPMPPLRPTTWLKDDSLRTASLQNMAKRGSRVAPLPPLMGVLSAPAP
DSSTAGGSPP
>gnl|BL_ORD_ID|1260 @Coccomyxa_subellipsoidea@15426|PACid:27386896
MT--------------------------------------------------LADTAASS
AAQAVGDKAADAIVSSATAVQSATDAAAEAVQRDNGWF-----GFFTGPFETVLKVLDTG
LDKLHVPYS-------YGF-----SIILLTIFVKALTFPLSKKQVESTVAIQALQPRVK-
-------------------EIQEKYK-------GRDPQEAQIEVAKLYQEAKVNPLAGC-
---LPTLITLPVWIGL-----YRALSNVADEGL--LSEGFFWIPSLAGPTTLAAQKAGAG
-SWLFPLVNGAPPIGWHDAS-------AY----LVLPVL--LIVSQYVSQKII-SPPS--
--EDPSQQSA---------QWILKFLPLMIGWFSLNVPSGLTIYWFINNVLSTAQQLWLK
K--------------------------TIQPPALASAGTGTVVNARSSVEDLRPTGETGC
PFSLA--------------------------ASAPCK-----------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------
>gnl|BL_ORD_ID|5045 @Coccomyxa_subellipsoidea@12888|PACid:27390681
MS----------------------------------------------------------
-----------------RVLHHWRCSALQAAAQDDGWL-----APISSGLNYSLQQIQTG
LDQLHVPYS-------YGW-----AIIVLTVGTKILTFPFTK--VESALAVQKLKPTID-
-------------------AIKRQY--------GEDKNSIQRETSALYEASGVNPAAGC-
---LPTLATIPIFWGL-----YRTLSNVASAGL--LTEGFYWIPSLSGPTSLAAQRAGTG
TAWLFPFVDGAPPVGWEDAA-------RY----LALPIA--LVAAQFASSAVI-SPPI--
--DDEDKNAAF-------SKGLLIAVPFMVGWFALNVPSGLSLYYFSNTIITSGIQIWLR
KLGGAYSPLLLLTFI--------------HWP-TVRACS-----SFLCC----PRQANSC
ASLFL--------------------------VP---------------------------
------------------------------GNHLFACWARRDFYVQLS------------
------------------------------------------------------------
-------------------------------W
>gnl|BL_ORD_ID|7951 @Coccomyxa_subellipsoidea@39658|PACid:27393587
MK----------------------------------------------------------
---------------------------------LRRWL----------------------
------------------------TIIYTTIGARLLTLPLVVKQQRNTANMTMARPEMM-
-------------------ALKDWYTEETARGNPKATTEYQQRLANLWQKYDCNPFKSM-
---LGILAQAPLFIGF-----FSALRALSAAKVPSMTEG--------------------G
VAWFTDLTLADP----------------Y----YALPIMSSAVFLLTVELGAADGMQG--
--QDEAMLRR--------MKNIFRAIGVAMVPLTASFPQGVFLYWVTSNIFSLGQSVLFK
---------------------LPAVRKTLKLPDLAKMRA-----TATGL----PITEAGK
PLVTF--------------------------AQPPKQR----------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------KAKTT
>gnl|BL_ORD_ID|10331 @Micromonas_pusilla_CCMP1545@52221|PACid:27348985
MQATSATGAGAVARGAVAVAGARASSIRGVAALPARRASRALAPRRRVAPRRAAVAARAS
--IGGEFPVF-DVINDAVINAHASAMTSDALGSIFQVADAAAVDVEEIP-----GL----
----QKGGWLGPITDFLEASLGVIDQGLEGLNVPYSYGY-----------A-------IL
VLTVVVK-------------------------------LVTFPLTKKQVEGSIAMQALQP
RVKELQA-----MYANDPERLQMETARL------YKEANFNPLAGCLPTF----------
------------------------------------ATLPVFIGL----------YRALS
NAATEGMLEDGFYWI------PSLGG-------PTSIAARNDGSGFSWLWPFVDG-APPL
GW-HDTAAYLALPVLLVVSQFASQKIMT-PDQGKDVDPSQASSQA---I--LKFLPFMIG
FFSLNVPAGLTLYWFANNIFSTAQTVYLRKTTKAPDSIQNVGGGSAAMPMPGTTPAATQP
VRVEY--VPKS-------------------------------QRKSGGAAPKPPP-PR--
-------------------VEAMPAA----VASEFAD---------------FDDGP---
ARVTETVEG-VVVGGDGA---DATESAGGGGGGDARGKGSKKSKKAAGSRKRRNKSR---
-----------------------------------------------
>gnl|BL_ORD_ID|3956 @Micromonas_pusilla_CCMP1545@31798|PACid:27342602
MTSQ------GCSSGSLVCRGARGLYRCGRQTGCPRRDTSLLSRRTRPRSFDASCGAISA
TDIGESITIVPDVITAAI---FASEQIADLSESTFTVG-ATVVDSSHATLFAELSALTEI
TGPQRMEGILSPVSDLLEEFVLATQRYFSDAGVRYPLGS-----------S-------II
FTTFVVK-------------------------------ALTYPFTKVQVESALNMQNLQP
QVNAVRE-----KYRDDQEQMNIEINRL------YEDNQVSPLAGCGPLL----------
------------------------------------LTLPVVWGL----------YRAFN
NASIDGSFDEPWFFI------PSLAG-------PTP------DRSLAWLLPLDDNYQPPL
GW-HDASLYLVVPILTVASQYVSMSILS-PVKDLN-DPNTAETEQQSFL--LNFLPLFIG
YISLTVPAGLTLYWLFNNIFTTATQVYLRQGGGAVAKVEKIKDVKLKVPL---GCAIVDQ
NSTDQLSVHDVFEGPYVLVTDSGEIDLAYSGEIDLAYSALPDHDKAYGFYLSPELRSAKT
DKWRLHMEKRGKRSLDPAERYNATPEELRLLISEYLK-----------------------
------------------------------LGMVAEAEEISVELGRLGSETERSDPL---
-----------------------------------------------
>gnl|BL_ORD_ID|9618 @Micromonas_pusilla_CCMP1545@3586|PACid:27348271
------------------------------------------------------------
------------------------------------------------------------
-----------------EVIAIAADSWITTAGLMYVIEYFHLAHGMEWYAA-------IA
AATCVMR-------------------------------VCAFPLTIMQQKSAGKMHLAKP
EMTALQESINEARRAGEHER----AARLGRVFAIWSKHDVHPAKMLAPLL----------
------------------------------------FQAPVFISF----------YFAIS
RMA-EGL--------------PSMR-----------------DGGFAWFQDLSIA-DP--
--------TFALPIIS------SLTFLA-AVEFAPQNPAVKSSQREMTKWGLRALGVAMV
PLTASFPSGVFVYWITSNVFSFAQTVLLR------------------VPF----------
------------------------------------------AKRAMGIPEDPPP-----
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------
>gnl|BL_ORD_ID|4751 96326|PACid:27400020
MAACVANLGGIARSNALTPVGARGASSSRTAGGLLPLRRAGSS---GRAVRRVRSSVAVR
ASMAGAEFPSFDQVQGAVANVHASFIGNDAVASLFQVADAA-------DAAAPEELKGLQ
KGGWLGPITDLLESILKGIDSGFVGLGVPYSYGYAILALTVLVKVVTFPLTKKQVEGSLQ
MQAIQPRVKELQAM---YANDPERL---QMETARLYKEANFNPLAGCLPTFATLPVFIGL
YRALSNAAVEGELTDGFYWIPSLGGPTSIEARNDGNGFAWLFPFVDGAPPLGWHDTIA--
-YLVLPVLLVASQLISQKVMTPDQPKSDDPAQQ--QSQAILKFLPFMIGFFSLNVPAGLT
LYWFANNIFSTAQTVYLRKTTKA-----------------------------------PE
MPAAVAGGMPMPGTPASAQPVRVEYVPKSQRKAQGSVPAPKPAPPKVEPMPESLAAEFGD
FDDGPAKIVEPVVVEAKVVADTTGAAAAAAAGEAGGKKGGSRKGSKG-------SRKRKG
SRK
>gnl|BL_ORD_ID|3407 69262|PACid:27398672
HLA---------------------------------------------------------
-----------------------------------------------------------H
DMEWWA----------------------------AIMATTAIMRVFVMPFMVMQQRVAAR
MHIAKPEIEALNARIKGMGGDQQVMAEAQKEIFAIWKKHNCNPAYMMLPIAVQAPLFISF
YFAISEMAKG---------VPSFA----------SGGPDWPLG------PISMHDLTAAD
PTYIMPVLSSATFLATVELGGAGNPETSGAAQQTMMTKWGLRALSVALIPMTAGFSKGVF
VYWITTNMFSLGQTL------------------------------AFKVPLIKKIVAIPE
IP----------------------------------------------------------
------------------------------------------------------------
---
>gnl|BL_ORD_ID|557 @Ostreococcus_lucimarinus@3334|PACid:27413422
EA----------------------------------------------------------
-------------------------LKAAGLQKGGWLGPITDGLESALEGIDS-------
-----VLDGRVPY--SYGFSIIVLTVLVKLATFPLSKKQVESSMQMQAMQPRIKELQAMY
ANDPER-------LQMEQARLYKEAGFNPLAGCLPVFATLPVFIGLYRALSNAASEGLLT
DGFYWIPSL--GGPTSIASRNAGSGFAWLWPF-VDGHPPLGWHDTTAYLVLPVLLVASQY
VSQQIVSPQPKTDDPAQQQSQAILKFLPL------------------MIGFFSLNVPAGL
TL---YWFANNIITTAQTLI----------------------------------------
----------LRK------------TTTAPEP----------------------------
--------------------------------------------PVAKSGAAG-------
------------------------------------------------------------
--------
>gnl|BL_ORD_ID|3977 @Ostreococcus_lucimarinus@3329|PACid:27416850
AAKI--------------------------------------------------------
----------------------ASGEIAAPQRMEGWLAPVSDALEDLLFAIQGQ------
-----LQGLGVPY--STGNAIIIVTILVKFVTYPLTRDQVVSSLNMKNLQPQIAAIREKY
EDDQER-------MNKEINRVYEENGVNPLAGCGPALLTFPVLAGLYRAFNNAGIDGAFD
EAWFFLPSL--AGPT------DARDLSWLLPLDSDYAPPIGWEEASLYLIFPVLTTISQF
VSMEVLKPEETEKTDEMKNQSVLLKLLPL------------------FIGYISLTVPAGL
AL---YWFWNNVFTTGIQVF----------------------------------------
----------LRN-------------GGAKATVE--------------------------
------------------------------------------------------------
------------------------------------------------------------
--------
>gnl|BL_ORD_ID|5645 @Ostreococcus_lucimarinus@40894|PACid:27418518
MT----------------------------------------------------------
----------------------TAGGAAETLTSASDLAPVVGSLASEVVPVASQSWPTTA
ALMYAMEYFHVAHGLEWWLAIVGATVFMRTITFPLIVMQMRNTAKMQLCKPELEALQAKM
KSNPQQDPELANAYYKEMQKVWKKYDVNPVKSFAPILINAPVFISFFFAISKMAQG----
-----VPSFESGGPSM--------------------YPDLSMADPT--YSLPILSSLTFL
ASVELGA-VEGMQTSQSAQMKWFLRALAV------------------AMVPLTASFPQGV
FV---YWITSNIFSGFQTSI----------------------------------------
----------TRTKAFKSTMGIPDVSAVAEAPAEAALGRVQLDRFQKKYGATPTLHKRP-
----------------------PTQKQRKK------------------------------
------------------------------------------------------------
--------
>gnl|BL_ORD_ID|5658 @Volvox_carteri@_Vocar20010438m|PACid:23129534
M-----------------------------------------------------------
-------ALAMKQYPSALGARKPCQPLLPPRPSVRR-------PGAGIGSGSRR------
------------------------------------------------------------
------------------------------------------------------------
------------------------------AAVCVKASLLDPST----------------
------------------------------------------------------------
----------------------------------------------AASTVEAVQHAQNL
YTLADGGPIDLLAQFFT-------------------------------------------
---------------------------------SVLRTLDDGLENAHVPYS---------
-----------------------------------------YGFAIIT-----LTVLVKL
ATFPLTQKQVESTLSLQALQ-----------PRVKELQAKHADDP--ETLQLETARMYKE
AG-------------------------------VNPLAG---------------------
---------------------CLPTLAT--------------IPVFIGLYNALSNAAKAG
LL-TEGFFWIPSLSGPTTI-----GGGLEWLFPFQDGAPPVGWANAAAYLVMPVLLVASQ
YASQKIISTTQNSNDPAQQQSQAILKFLPL------------------------------
-------------------------------------MIGWFSLNVPSGLTLYWFVNNLL
STAQQLYL----------------------KATVKVNVPESIKAPV--------------
---------------AATSATVVK-PKEERVKRITG------------KELGARKKRRNE
-----------------------AGEEVEEVDVEIVSTSGSNGAASAS-----PAVNGNG
SGSSRKGE----------------------------------------------------
-----------------------------------------------------------K
FRALKAREAAAKAAA---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------
>gnl|BL_ORD_ID|4166 @Volvox_carteri@_Vocar20003543m|PACid:23128036
M-----------------------------------------------------------
--------ATLRYRPVAQRVKRNAHFRYAIRYAARNVLVDLPCPGRLRGSSYRA------
------------------------------------------------------------
----------------------------------------GSEITLLTSHLSAG------
-----------IPDYLD-----RADLLPTFSFPLANAGAASESV----------------
------------------------------------------------------------
----------------------------------------------AAAVTANILSASPT
DQRA-GGWVAPLADVLE-------------------------------------------
---------------------------------QVLYVLKDCLDLLHVPYS---------
-----------------------------------------YGYSIIL-----LTLIVKI
VTYPLTKQQVESTLAVQALK-----------PRVDLIKDRFGDDK--EKIQKETSILYEQ
AG-------------------------------VNPLAG---------------------
---------------------CLPTLAT--------------TPIFIGLYSSLTNVANEG
LLDTQGFYWIPSLA--------------------------------------------VQ
YASLYSTGPTSDATDVNARLQRALLLGLPV------------------------------
-------------------------------------MIGWFALNVPSGLSLYYLSNTIL
STAQQVYLKKL----GGAKVAIKKL-GPIMKPGSGRRSGAPEAELK--------------
---------------LWVSATTFKSTAERGKNSLNMEGP-----------VELARNALDT
DLPETTAA-------LTDVIKSSQTDSSPLVDLSNVNRFCKRRRLSSL--VQDGANGAQI
FPA---------------------------------------------------------
------------------------------------------------------------
----------ATTSV---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------
>gnl|BL_ORD_ID|3384 @Chlamydomonas_reinhardtii@_16.g690200.t1.1|PACid:19861677
MAQRWRALQRGAALLAHHTESAASTQVLSACSTSASSLLQQITLDQRGSGGSWQQHQHAW
GSSSHRTFFSFARKKPDAGAVAAASTGDETSISGSEPVADPTPVGPPEFFPLPESAPD--
------------------------------------------------------------
----------------------------------------AIEVASAIHQACSALER---
--------------------------------------------ASIMSAK---------
ADAF-FSASWC-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------ISG
LQAVHDL------------------------LDTPWFLSIAIFNITLRLLTFPLMVVAQK
GSAKMMEFNHNLIHAK-KLQEAAMKATSQEEHQR-----------LFQAFRNEYNVQTAK
HGDPVKT----------------------ALVVPGVM-----------------------
ILNGAIF----------------------------------------LSIFNGV------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------SKLMAA---------KVPSLT----------
TGGAL-------------------------------------------------------
-----------------------------WFS----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------DL----------TSPDP
YF------------GLPLMCTAVTLAMVEYGINLAGDAG-PMPEDRAKMTNGLKNFMRVM
AFMFIP---AGGYVAAGTAVL---WVSNTA--FGVVQGLTLR------------------
------NDRFRRRVGLP-----------------TMQALRDMNAKVMAAN-AAG---TPA
SAGAAGASAAAT------LAAAADTSAPASAAPLLSNSPVGAKARR--------------
------------------------------------------------------------
----------------------------------------
>gnl|BL_ORD_ID|9070 @Chlamydomonas_reinhardtii@_17.g729800.t1.1|PACid:19867375
MALQMKQ-----------------------------------------------------
-------------------------SPSMGVRRASQPVLPPRPI---------------V
HRGVGSVSRRPAV-----------------------------------------------
-----------------------------------VVKASLLD-AASAASAVDAVHH---
--------------------------------------------ATQLYTLAEGGPIDVL
AQFFEFVLQTL-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------DEG
LESAK--------------------------IPYSYGFAIIALTVLVKVATFPLTQKQVE
STLSLQALQPRVKELQAKYAD------DPENLQL-----------ETARLYKEAGVNPLA
GCFPT-------------------------------------------------------
LATIPVF----------------------------------------IGLYNAL------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------SNAAKEGLL-TEGFFWIPSLGGPTTI-----
GGGLE-------------------------------------------------------
-----------------------------WLV----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------PF-ENGAPPVGWANAAA
YL------------VMPV-----LLVASQYASQKIISSQ----NNQDPSQQQAQAILKFL
PLMIGW---FSLNVPSGLTLY---WFVNNL--LSTGQQLYLKATVKVNIPEAIKAPATAG
SSTPIVKPKEERVKKVTGKELGSRK-----------KRRNDDGEEVEDVEVEVV---SSG
SSSSSGSNGASGRKGEKFRALKAREAAAKAASTVSAGAGGSEEGKDNS------------
------------------------------------------------------------
---------------------------------------A
>gnl|BL_ORD_ID|5308 @Chlamydomonas_reinhardtii@_06.g251900.t1.1|PACid:19863606
M-----------------------------------------------------------
------------------------------------------------------------
------------Y-----------------------------------------------
-----------------------------------VLADASAS-TAAAAVMPTAVDS---
--------------------------------------------AAGAAPQRAGGWVAPV
ADALEQVLYAL-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------QEG
LDKLH--------------------------VPYSYGYSIILLTLIVKLLTYPLTKQQVE
SAMAVQALKPRIDLIKDRFGE------DKDKIQK-----------ETSVLYEQAGVNPLA
GCLPT-------------------------------------------------------
LATIPIF----------------------------------------IGLFSSL------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------TNVANDGLLDTQGFYFVPSLAGPTTMAMRQS
GLGTS-------------------------------------------------------
-----------------------------WLW----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------PLGPDGAPPIGWEDAAA
YL------------TLPL-----LLVAVQYASSSVTS---PPIDPKDENANTQRALLVFL
PLMVGW---FSLNVPAGLSLY---YLANTV--LSSAIQIYLKKLGGANV--------VMN
ELGPVTKPGSGRRNGVAAGEWSVWKPATVLTTAEAAKARAEAEEAVERAR-EAA---EEA
AAAAAFDNASVS------LSVDDSTAAIAGTATMAVTAGATAAAMDPSKVNRRCKRRRLT
SLVQDGSTASAAVAGAS-------------------------------------------
---------------------------------------A
>gnl|BL_ORD_ID|13549 @Chlamydomonas_reinhardtii@_03.g198150.t1.2|PACid:19871867
M-----------------------------------------------------------
--------------QRCGGLVTRLLSRSVSAASKRDAAAACTGLGPWGVLCF--------
-RGISSTSSP--------------------------------------------------
-------------------------------------DTGVLQVQPQAADAFNAVAH---
--------------------------------------------SSLEDGL---------
AMIL-SPTQLG-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------VQL
WEVAHAS------------------------TGLPWWAAIPVATVGVRTMLMPLSLRAYA
ASSYLALLHRAFGLSR-EVGDAVAEAEATERRQR-----------GESAGSASVSEGSAV
AGETSASSSGSSPHSTGRKRNAAVVDGARALGRMELVRHVVAHLHKGSNAPSLSWYVANG
AVQMPIV----------------------------------------ISLTLAL------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------RRMCDS---------LWPGLT----------
SEGAL-------------------------------------------------------
-----------------------------YFT----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------DL----------TAPPV
YLQTLSTPYGTAGAILPL--GLMLLYASAVDRSRGGS------------SPGINVALKLC
AIPLYI---AALQQPHAVLLY---WLSHAATQLGVYQVAVLM------------------
------EPKQTASTEAT-------------QTDQGDASLDDL---------LLV---LSD
SYEKAGNKAAAR----------ACLQALSVRQP-----GLGSVQERLKQLDTTSG-----
------------------------------------------------------------
---------------------------------------V
>gnl|BL_ORD_ID|7951 @Coccomyxa_subellipsoidea@39658|PACid:27393587
MKLRR-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------WL------------------TIIYTTIGARLLTL
PLVVKQQRNTANM-----------------------------------------------
--------------------------------------------TMARPEMMALKD----
-----------------------WYTEETARGNPKAT-TEY------QQRLANLWQKYDC
NPFKS-----------------MLGILAQAPLFIGF-----FSALRALSAAK--------
V----------PSMT---------EGG-------------VAWFTDLTLADP--------
-----------------------YYALP--------------------------------
---------------------------------------------------IMSSAVFLL
T-------VELGAADGMQGQ-DEAMLRRMKNIFRAIGV------------------AMVP
LTAS-FPQGVFLY--WVTSNIFSLGQSVLFKLPAVRKTLKLPDLA--------KMRATAT
GL-PITEAGKPLVTFAQP-----------------------------------PKQRKAK
T-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------T
>gnl|BL_ORD_ID|1260 @Coccomyxa_subellipsoidea@15426|PACid:27386896
MTLADT------------------------------------------------------
------------------------------------------------------------
-------------------------------------AASSAAQAVGDKA-ADAIVSSAT
AVQSATDAAAEAVQRDNG-------------------------------------WFGFF
TGPFETVLKVLDTGLDKLH--VPYSYGF------------------SIILLTIFVKALTF
PLSKKQVESTVAI-----------------------------------------------
--------------------------------------------QALQPRVKEIQE----
-----------------------KY-----KGRDP---QEA------QIEVAKLYQEAKV
NPLAG-----------------CLPTLITLPVWIGL-----YRALSNVADEGLLSEGFFW
I----------PSLAGPTTLAAQKAGA-------------GSWLFPLVNGAPPIGWHD--
--------------------ASAYLVLPVLL-----------------------------
---------------------------------------------------IVSQYVSQK
I-------ISPPSEDPSQQ--------SAQWILKFLPL------------------MIGW
FSLN-VPSGLTIY--WFINNVLSTAQQLWLK-----KTIQPPALASAGTGTVVNARSSVE
DLRPTGETGCPFSLAASA-----------------------------------PC-----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------K
>gnl|BL_ORD_ID|9618 @Micromonas_pusilla_CCMP1545@3586|PACid:27348271
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------EVI-A--
---IAADS-----------WITTAGLMY-------VIEYFHLAHG---------------
-------------------------------------------------------MEWYA
AIAAATCVMRVCAFPLTIMQQKSAGKMHLAKPEMTALQESINEARRAGEHERAARLGRVF
AIWSKHD-VHPAKMLAPLLFQAPVF------ISFYFAISRMAEG---------LPS----
------MRDGGFAWFQDLSIA----------------DPTFALPIISSLTFLAAVEFAPQ
NP-AVKSSQREMTK---WGLRALGVAMVPLTA--------------------SFPSGVFV
------------------------------------------------------------
--------------YWITSNVFSFAQTVLLRV----------------------------
-------------PFAKRAMG--IPED---------------------------------
------------------------PPP---------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------
>gnl|BL_ORD_ID|10331 @Micromonas_pusilla_CCMP1545@52221|PACid:27348985
MQ-----------------------------ATSATGAGAVARGAVAVAGARASSIRGVA
ALPARRASRALAPRRRVAPRRAAVAARAS--IGGEFPVF-DVI-----------------
--------------------------------NDAVINAHASAMTSDALGSIFQVADA--
---AAVD------------VEEIPGLQK-GGWLGPITDFLEASLG---------------
-------------------------------------------VIDQGLEGLNVPYSYGY
AILVLTVVVKLVTFPLTKKQVEGSIAMQALQPRVKELQAMYANDPERLQME-------TA
RLYKEAN-FNPLAGCLPTFATLPVF------IGLYRALSNAATEGMLEDGFYWIPSLGGP
TSIAARNDGSGFSWLWPFVDG-------APPLGWHDTAAYLALPVLLVVSQFASQKIMTP
DQGKDVDPSQASSQ---AILKFLPFMIGFFSL--------------------NVPAGLTL
------------------------------------------------------------
--------------YWFANNIFSTAQTVYLRKTTKAPDSIQNVGGGSAAMPM-----PGT
TPAATQPVRVEYVPKSQRKSGGAAPKP---------------------------------
------------------------PPPRVEAMP-AAVASEFADFDDGPARVTETVEGVVV
------------------------------------------------------------
------------------------------------------------------------
---------GGDGADATESAGGGGGGDARGKGSKKSKKAAGSRKRRNKSR
>gnl|BL_ORD_ID|3407 69262|PACid:27398672
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------HLA
HDMEW-WA-AIMATTAIMRVFVMPFMVMQQRVAARMHIAKPEIEALNARIKGMGGDQQVM
AEAQKEIFAIWKKHNCNPAYMMLP-IAVQAPLFISFYFAISEMAKG---------VPS--
-------------------FASGGPDWP--LGPISMHDLTAADPT----YIMPVLSSATF
LATVEL----GGAGNPETSGAAQQTMMTKWGLRALSVALIPMTAGFSKGVFVYWITTNMF
SLGQTLAFKVPLIKKIVAI-PEIP------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------
>gnl|BL_ORD_ID|5645 @Ostreococcus_lucimarinus@40894|PACid:27418518
M-----------------------------------------------------------
------------------------TTAGGAAETLTSASDLAPV------------VGSLA
SEVVPVASQSWPTTAALMYAMEYFHVAHGLEWWLAIVGATVFMRTITFPLIVMQMRNTAK
MQLCKPELEA-LQAKMKSNPQQDP----ELANAYYKEMQKVWKKYDVNPVKSFAPIL---
---------------INAPVFISFFFAISKMAQG---------VPSFESGGPSM------
--------------YPDLSMADPTY------------SLPILSSLTFLASVELGAVEGMQ
TS-QSAQMKWFLRALA--VAMVPLTASFPQGVFVYWITS-----------NIFSGFQTSI
TRTKAFKSTMGIPDVSAVAEAPAEAAL---------------------------------
------------------------------GRVQLDRFQKKYGATPTLHKR----PPT--
------------------------------------------------------------
--------------------------------------------QKQRKK
>gnl|BL_ORD_ID|557 @Ostreococcus_lucimarinus@3334|PACid:27413422
E-----------------------------------------------------------
---------------------------ALKAAGLQKGGWLGPI------------TDGLE
SALEGIDSV-----------LDG-RV--PYSYGFSIIVLTVLVKLATFPLSKKQVESSMQ
MQAMQPRIKE-LQAMYANDPER-----------LQMEQARLYKEAGFNPLAGCLPVF---
---------------ATLPVFIGLYRALSNAASEGLLTDGFYWIPSL--GGPTSIASRNA
GSGFAWLWPF-VDGHPPLGWHDTTAYL----------VLPVLLVASQYVSQQIVSPQPKT
DDPAQQQSQAILKFLP--LMIGFFSLNVPAGLTLYWFAN-----------NIITTAQTLI
LRKT---TTAPEPPVAKSGAA---------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------G
>gnl|BL_ORD_ID|3977 @Ostreococcus_lucimarinus@3329|PACid:27416850
A------------------AK---------------------------------------
------------------------IASGEIAAPQRMEGWLAPV------------SDALE
DLLFAIQGQ-----------LQGLGV--PYSTGNAIIIVTILVKFVTYPLTRDQVVSSLN
MKNLQPQIAA-IREKYEDDQER-----------MNKEINRVYEENGVNPLAGCGPAL---
---------------LTFPVLAGLYRAFNNAGIDGAFDEAWFFLPSL--AGPTD------
ARDLSWLLPLDSDYAPPIGWEEASLYL----------IFPVLTTISQFVSMEVLKPEETE
KTDEMKNQSVLLKLLP--LFIGYISLTVPAGLALYWFWN-----------NVFTTGIQVF
LRNGGAKATV--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------E
>gnl|BL_ORD_ID|1034 @Ostreococcus_lucimarinus@93298|PACid:27413900
M-----------------------------------------------------------
------------------------------------------------------------
-----------------SDSMTHLHAATGAPWFVALAASAALVRAATAPISARTIKASAT
VSAASALAKSRKRGNSEHVGVRDV----LDAIG---ELRGKAPGTGAHPAWLVAGPL---
---------------AQIPFFLCAVMAVRRLAADGA-------NNGLVTGGALW------
--------------FQDLTVPAVDVAMMTAPMGPYGGILPVLTAAALFANVNANFASAAA
QSRGMTIVKLVLEWMT--LPMLVIGMQLPQAVHCYWLTS-----------SAWALAQNRA
LSTTFAREALGINALAKVTREIAASQGLGGEDVAMSPEVLELVKAAAKERAGNNNAQAVN
LLLRAARGGGDVAAALRGEDLGKSHPTVLFALGQTYAVLKEWKKSALTYEYSARAEPDPL
R-----------RSRALMGAGVARARLGDLGMASEALYEANRLNPTDASVKVALASALKL
NGDPERALEILREAAELQPDIDERYVKPLER-----------ELASRTSA
>gnl|BL_ORD_ID|131 @Volvox_carteri@_Vocar20001462m|PACid:23123990
MA----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------QRWRSLQRGAALLLHHAEPSAS
GAPGLLSAYPSASSLILNLKSDQHQHKGGASWHQNHAWTGFIGVRHASTKSSSASVPS--
------------------------------------------S-------SSGFP-----
DDAP---------SNSGMDLTPPPEFFPLPESSAAEVATAIHQACDALERASLLGAKADA
FFAAS---WCISGLQAVHEMLDTPWWVSIMLFNISLRLCTFPLMVLAQRG-SAKMMEFNY
ALLHAK-----------------------KLQEAAMKATNRAEH----------------
----------------------------------------------------------DR
LFNAFRTEYTAQVSKHGDPVKTALM------VPGV-MIFNGFVFLSIFNGISK-------
--------------------LMAAKVLRRCAV----------------------------
--------PSLTTGGALWFSDL--------------------------TQPDPF------
--------------------FGLPIM-------CTLVTLAMVEYGINLAGDAGPMPSERQ
QATKTMKWVFRVLAF----------------------MFIPA---GNYVAAGTALLWVSN
TAFGV-VQGMLLR-------ND--------------------------------------
------------------------------------------------------------
----------------------------------------------------GVRQRMGL
PSM---------------------------QELREMNARVLEANSANA-P----------
------------------------------------------------------------
------KPSEAPPSIFSAT-KP-SLDTAPA-VNVPLMSRPPGS-----------------
-KGTKGP
>gnl|BL_ORD_ID|5658 @Volvox_carteri@_Vocar20010438m|PACid:23129534
MALA--------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------MKQYPSALGARK----------
---------PC-------------------------------------------------
------------------------------------------QPLLPPRPSVRRP-----
GAGI---------GSGSRRAAVCVKASLLDPSTAASTVEAVQHAQNLYTLADGGPIDLLA
QFFTSVLRTLDDGLENAH--VPYSYGFAIITLTVLVKLATFPLTQKQVES-TLSLQALQP
RVK--------------------------ELQAKHADDPETL------------------
----------------------------------------------------------QL
ETARMYKEAGV----------NPLA------GCLP-TLATIPVFIGLYNALSN-------
--------------------AAKAGL----------------------------------
-----------LTEGFFWIPSL--------------------------SGPTTIGGGLEW
LFPFQDGAPPVGWANA-AAYLVMPVL-------LVASQYASQKIISTTQNSNDPAQQ---
----QSQAILKFLPL----------------------MIGWF---SLNVPSGLTLYWFVN
NLLST-AQQLYLK----ATVKV--------------------------------------
------------------------------------------------------------
----------------------------------------------------NVPESIKA
PVAA-------------TSATVVKPKEERVKRITGKELGARKKRRNEAGE----------
------------------------------------------------------------
------EVEEVDVEIVSTSGSNGAASASPA-VNGNGSGSSRKGEKFRAL------KAREA
-AAKAAA
>gnl|BL_ORD_ID|4166 @Volvox_carteri@_Vocar20003543m|PACid:23128036
MAT---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------LRYRPVAQRVKRNAHFRYAIRY
AARNVLVDLPC------------PGRLRGSSYRAGSEITLLTSHLSAGIPDY--------
------------------------------------------LDRADLLPTFSFP-----
LANA---------GAASESVAAAVTANILSASPTDQRA--------------GGWVAPLA
DVLEQVLYVLKDCLDLLH--VPYSYGYSIILLTLIVKIVTYPLTKQQVES-TLAVQALKP
RVD--------------------------LIKDRFGDDKEKI------------------
----------------------------------------------------------QK
ETSILYEQAGV----------NPLA------GCLP-TLATTPIFIGLYSSLTN-------
--------------------VANEGL----------------------------------
----------LDTQGFYWIPSL--------------------------------------
-----------------------------------AVQYASLYSTGPTSDATDVNAR---
----LQRALLLGLPV----------------------MIGWF---ALNVPSGLSLYYLSN
TILST-AQQVYLKKLGGAKVAI--------------------------------------
------------------------------------------------------------
----------------------------------------------------KKLGPIMK
PGSGRRSGAPEAELKLWVSATTFKSTAERGKNSLNME-GPVELARNALDT----------
------------------------------------------------------------
------DLPETTAALTDVIKSS-QTDSSPL-VDLSNVNRFCKRRRLSSLVQDGANGAQIF
PAATTSV
