>Aquilegia_coerulea_gnl|BL_ORD_ID|22333 _027_00319.1|PACid:22045412
M------------------------------------------AKTLISSP--IFQTT--
-QLPSLSRHSNKF--------PSFTPYRKHNYTTKVKFSLNEIPPI--------QSFDSS
SSSSIDFH---------------------------------GIISRAEGLLYTLADA---
------------------------------------------------------------
------------------------------------------------------------
-------------------------AVVA--TDSAASSTGN-------STD-VAAQK---
----SGGWFGFISD-AMEIVLKVLKDGLTAVHVPYAYGFAIILLTVIVKVATLPLTKQQV
ESTLAMQNLQPKIK----AIQERYAG-NQERIQLETSRLYKQAGVNPLAGCLPTLATIPV
WIGLYQALSNVANEGLF--------------------------------TEGFFWIPSLG
GPT---------------------------------------------------------
-----TIAARQSGSGVSWLFPF-VDGHPPLG--------WHDTAAYLVLPVLLVVSQFVS
MEIMKPP--Q-TNDPA---QKNTLLIFKFLPLMIG--YFSLSVPSGLSIYWFT-------
NNVLSTAQQVWLRKLGGAKPVVNENASGIIS-----------------------------
--------AGRAKRRDAQSAQT------------------GERFRQLKEEEKKKYINKAL
PESDSSSSLSDS------------------------------------------------
----------DEVSDGEVNDK----DDALEEAYTSG-VNKQLPD-SGPRRSKRSKRKRAV
------------------------------
>Brassica_rapa_gnl|BL_ORD_ID|37155 _035669|PACid:22720665
M------------------------------------------ARVLISSPSSFFGSPLL
KPSSSSRHVAGGGGGSLQF-----------RNKHLVRFSLNELPPL--------------
-HGSVDIG---------------------------------AILTRAESFLYTVADA---
------------------------------------------------------------
------------------------------------------------------------
-------------------------AVVGGAADSAV------------STD-PAVQK---
----SGGWFGFISD-GMELVLKFLKDGLTAVHVPYAYGFAIILLTIIVKAATYPLTKQQV
ESTMAMQNLQPKIK----AIQQRYAG-NQERIQLETSRLYKQAGVNPLAGCLPTLATIPV
WIGLYQALSNVANEGLF--------------------------------TEGFFWIPSLG
GPT---------------------------------------------------------
-----SIAARQSGSGVSWLFPF-VDGHPPLG--------WGDTAAYLVLPVLLIVSQYVS
MEIMKPP--Q-TDDPA---QKNTLLVFKFLPLMIG--YFALSVPSGLSIYWFT-------
NNVLSTAQQVWLRKLGGAAPAVNENASGIIT-----------------------------
--------AGRAKRSIAQPDDA------------------GERFRQLKEQEKRSKKNKAV
AKDTVELL-ESQ------------------------------------------------
----------SESEEGSDDEEEE----VREGALASS-TSKPLPD-VGQRRSKRSKRKRAV
------------------------------
>Alb3_gi|15226968|ref|NP_180446.1| inner membrane protein ALBINO3 [Arabidopsis thaliana]
M------------------------------------------ARVLVSSPSSFFGSPLI
KPSSSLRHSGVGGGGTAQFLPYRSNNNKLFTTSTTVRFSLNEIPPF------------HG
LDSSVDIG---------------------------------AIFTRAESLLYTIADA---
------------------------------------------------------------
------------------------------------------------------------
-------------------------AVVG--ADSVV------------TTDSSAVQK---
----SGGWFGFISD-AMELVLKILKDGLSAVHVPYAYGFAIILLTIIVKAATYPLTKQQV
ESTLAMQNLQPKIK----AIQQRYAG-NQERIQLETSRLYKQAGVNPLAGCLPTLATIPV
WIGLYQALSNVANEGLF--------------------------------TEGFFWIPSLG
GPT---------------------------------------------------------
-----SIAARQSGSGISWLFPF-VDGHPPLG--------WYDTVAYLVLPVLLIASQYVS
MEIMKPP--Q-TDDPA---QKNTLLVFKFLPLMIG--YFALSVPSGLSIYWLT-------
NNVLSTAQQVYLRKLGGAKPNMDENASKIIS-----------------------------
--------AGRAKRSIAQPDDA------------------GERFRQLKEQEKRSKKNKAV
AKDTVELVEESQ------------------------------------------------
----------SESEEGSDDEEEE----AREGALASSTTSKPLPE-VGQRRSKRSKRKRTV
------------------------------
>Vitis_vinifera_gnl|BL_ORD_ID|16450 _GSVIVT01024995001|PACid:17833075
M-------------------------------------HVCVREINLITNK---------
-------------VKVVEFYIYELYFQLRNSLKHVFRIFHKLIPNF--------SLCSSQ
FPTPKAFY--------------------------------------QIHLLYTLADA---
------------------------------------------------------------
------------------------------------------------------------
-------------------------AVSA--DPAAAGPASG-------TAD-AAVQK---
----NGGWFGFISE-GMEVVLKVLEDGLTAVHVPYAYGFAIILLTVIVKIATYPLTKKQV
ESTLAMQNLQPKIK----AIQERYKG-NQERIQLETSRLYKQAGVNPLAGCFPTLATIPV
WIGLYQALSNVANEGLL--------------------------------TEGFFWIPSLG
GPT---------------------------------------------------------
-----TIAARQSGSGISWLIPF-VDGHPPLG--------WQDTAAYLVLPVLLVISQYVS
MELMKPP--Q-TDDPS---QKNTLLVFKFLPLMIG--YFSLSVPSGLSIYWFT-------
NNVLSTAQQVWLRKLGGAKPVVNEDASGIIT-----------------------------
--------AGRAKRSASQPARA------------------GDRFRQLKEEEKKKKISKAL
PAEEIQALASES------------------------------------------------
-----------DSDEGSDEETKDKGDDVLEEAYVSS-GSKQVPQYAGPRRSKRSKRKRAG
------------------------------
>Oryza_sativa_gnl|BL_ORD_ID|27700 _LOC_Os01g05800.2|PACid:21910172
M------------------------------------------AKALLSSS--LLPSL--
------QPRAAAARLPMLTLPSLRRHGGRRASACRVRASLHGLDSI--------------
--AGLDLH---------------------------------AALERAEAALYTLADA---
------------------------------------------------------------
------------------------------------------------------------
-------------------------AVVA--ADAAAGGGGGGGGGGGEAAA-SVAQK---
----NGGWFGFISE-ALEVVLKVLKDGLSAVHVPYSYGFAIILLTVIVKAATLPLTKQQV
ESTLAMQNLQPQIK----AIQQRYAG-NQERIQLETARLYKQAGVNPLAGCFPTLATIPV
WIGLYQALSNVANEGLL--------------------------------TEGFFWIPSLG
GPT---------------------------------------------------------
-----TIAARQSGAGISWLLPF-VDGHPPLG--------WHDTICYLVLPVLLVASQFVS
MEIMKPP--Q-TDDPS---QKNTLLVLKFLPFMIG--WFSLSVPSGLSIYWFT-------
NNILSTAQQVWLRKLGGAKPVVNQGGSGIIT-----------------------------
--------AGRAKRTSAQPAQP------------------GERFKQLKEEESKRKGNKAL
AAGDSDLSAST-------------------------------------------------
----------SEDEESDDETTEE--GGP-EERYNSS-SNKKLPN-YSGKKGKRSKRKRMV
Q-----------------------------
>Zea_mays_gnl|BL_ORD_ID|32200 _GRMZM2G110063_T02|PACid:20851926
M------------------------------------------AKALLYSS--LLPGL--
-PRAVGSSRSAAA-RLLLLPPLRLRRGRRAASACAVRAGLHGLDSV--------------
--GGPHLQ---------------------------------AALERAEAALYTLADA---
------------------------------------------------------------
------------------------------------------------------------
-------------------------AVAA--ADAAAGAGDDAG-----QAA-AAVQK---
----NGGWFGFISE-ALEVVLKVLKDGLSAVHVPYSYGFAIILLTIIVKAATLPLTKKQV
ESTMAMQNLQPQLK----AIQQRYAG-NQERIQLETARLYRQAGVNPLAGCFPTLATIPV
WIGLYQALSNVANEGLL--------------------------------TEGFFWIPSLG
GPT---------------------------------------------------------
-----TIAARQSGAGISWLFPF-VDGHPPLG--------WYDTICYLVLPVLLVASQYVS
MEIMKPP--Q-SDDPS---QKNTLLVLKFLPFMIG--YFSLSVPSGLSIYWFT-------
NNVLSTAQQVWLRKMGGAKPVVSEGDRRIIT-----------------------------
--------AGRAKRSNAQPA--------------------GERFRQLKEEESMRKVNKAL
AAGDSNASSSTY------------------------------------------------
---------DMEDEESDDETTEE--GGPVEEASSTG-SDKKPPS-YSGKKGKRSKRKRMV
Q-----------------------------
>Zea_mays_gnl|BL_ORD_ID|11477 _GRMZM5G839422_T01|PACid:20831203
M------------------------------------------AKALLSSS--LLPAL--
-PGAAGGSRS-AA-RPMLLPPLRLRRGRRGASACEVRAGLHGLDSV--------------
--GGPHLQ---------------------------------AALERAEAALYTLADA---
------------------------------------------------------------
------------------------------------------------------------
-------------------------AVAA--ADTAAGAGADAG------QA-AAVQK---
----NSGWFGFISE-ALEVVLKVLKDGLSAVHVPYSYGFAIILLTIIVKAATLPLTKKQV
ESTLAMQNLQPQIK----AIQQRYAG-NQERIQLETARLYKQAGVNPLAGCFPTLATIPV
WIGLYQALSNVANEGLL--------------------------------TEGFFWIPSLG
GPT---------------------------------------------------------
-----TIAARQSGSGITWLFPF-VDGHPPLG--------WHDTICYLVLPVLLVASQYVS
MEIMKPP--Q-SDDPS---QKNTMLILKFLPFMIG--WFSLSVPSGLSIYWFT-------
NNVLSTAQQVWLRKMGGAKPVVTEGGSGIIT-----------------------------
--------AGRAKRSNAQPA--------------------GERFRQLKEEENRRKFSKAL
AAGDSDASSSTY------------------------------------------------
---------DMDDEES-DETIEE--GGPVEEA-STS-SDKKLPN-YSGKKGKRSKRKRMV
Q-----------------------------
>Selaginella_moellendorffii_gnl|BL_ORD_ID|8056 _12954|PACid:15409334
L-----------------------------------------------------------
------------------------------------------------------------
--------------------------------------------ARVEGFLYTVADA---
------------------------------------------------------------
------------------------------------------------------------
-------------------------AVAT--DVVTDG-----------TSETVQQAQ---
----QSDWFSGVTT-VMEAVLKVLKDGLTTLKVPYAYGFAIILLTVLVKVLTFPLTKSQA
ESTISMQNLQPKLK----AIQQRYAG-DQERIQMETARLYKQAGVNPLAGCLPTLATLPV
WIGLYRALSNVANEGLL--------------------------------SEGFFWIPSLA
GPT---------------------------------------------------------
-----TIAARQSGSGISWLFPF-VDGHPPLG--------WGDTIAYLVLPVLLIGSQYAS
MQIMQPP--Q--TDPS---QKNTQLILKFLPLMIG--YFALSVPSGLSLYWLSTENRVAN
KHILSTGQQVWLRKLGGRKPVVASGGGDIIS-----------------------------
--------AGQAKRSTPSP-----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------
>Physcomitrella_patens_gnl|BL_ORD_ID|31321 _Pp1s198_153V6.3|PACid:18067858
M----------------ATLSIHACSPSL---STALAVETNVAVKPYVVLS--LLPAA--
-RGLRPRRGLLSR------GPSLRKHSVRRNGLVVPKAYSGQLPDP----EHVRLALSAL
SKTPDALE---------------------------------GLLTRTEGLFFTLADA---
------------------------------------------------------------
------------------------------------------------------------
-------------------------AVAT--DPGQ-------------VTDAVVQKQ---
----DGGWLGGITN-TLELALTFLKDGIAKIGLPYSYGFAIILLTVIVKAATYPLTKKQV
ESTLAMQNLQPKIK----AIQTRYQG-DQERIQLETARLYKQAGVNPLAGCLPTLATLPV
WIGLYRALSNVANEGLL--------------------------------TEGFFWIPSLA
GPT---------------------------------------------------------
-----TIAARSSGSGISWLFPF-VDGAPPLG--------WGDTIAYLVLPVLLIGSQYVS
MQIMQPA--TASNDPA---QNQSQLILKFLPLMIG--YFSLSVPSGLSLYWLT-------
NNVLSTAQQVYLRQLGGAQPIVDKEGSGIIS-----------------------------
--------AGQAKRTPLPPPSAT-ATATDAPTSTSTKDSRGTRFKQLKEEEARKKEARRK
AAEEASKAAAAK-------------------------------AAEERDNILRAQLAQEA
QKSAASAGETSDEAQVESDGEKEDSDNSK--ALA---ANGAVGDSSGKQASKRSKRRRSP
------------------------------
>Physcomitrella_patens_gnl|BL_ORD_ID|25182 _Pp1s381_17V6.1|PACid:18061718
M----------------STLSTHARVSSLSSVSTASNVVANVAVRPCMIVS--LLPVA--
-RGLCSRKGLMSR------GP-LRRHSCMKSVSVMPRASLGQLPDP----EQVDLYINAL
SQTPDALQ---------------------------------GLLSRTEGLFFTLADV---
------------------------------------------------------------
------------------------------------------------------------
-------------------------AVAT--DPSQ-------------VTDAVVQKQ---
----DGGWLGGVSN-SLEIALTFLKDTIAKLGIPYSYGFAIILLTILVKAATYPLTKKQV
ESTLAMQNLQPKIK----AIQTRYQG-DQERIQLETARLYKQAGVNPLAGCLPTLATLPV
WIGLYRALSNVANEGLL--------------------------------TEGFFWIPSLA
GPT---------------------------------------------------------
-----TIAARSSGSGISWLFPF-VDGAPSLG--------WADTIAYLVLPVLLIGSQYVS
MQIMQPP--T-TNDPA---QNQSQLILKFLPLMIG--YFSLSVPSGLSLYWLT-------
NNVLSTAQQVYLRQLGGAQPIVDKEGSGIIS-----------------------------
--------AGQAKRTPLPPSASTSATVTAAPTS-SAKDNRGSRFKQLKEEDAKKKGSRRK
SAEEASKAAAAK-------------------------------GAEERDNLLRAQLAQDA
QKSTDASEETSDEEQYQNE-EKEDSDTSKEEALA---TNGAVGN-SSAKIKGRSKRRRSP
------------------------------
>Oryza_sativa_gnl|BL_ORD_ID|28879 _LOC_Os03g62750.4|PACid:21911351
M---------------------------------DAHLLLLARPRALALAA--ARAPG--
-GVAGFRRPASAR------------------RVAPRRVVLRPVAAL------------GG
GGGFAEVG---------------------------------ELFGRVEAFLYTVADA---
------------------------------------------------------------
------------------------------------------------------------
-------------------------AVSA--SPEVVQGGGG-----------GTKEA---
----AGDWLSGITN-SMETVLKVLKDGLSALHVPYPYGFAIILLTVLVKAATFPLTKKQV
ESAIAMRSLQPQVK----AIQERYAG-DQERIQLETARLYKLSDVDPLAGCLPTLVTIPV
WIGLYRALSNVANEGLL--------------------------------TEGFFWIPSLA
GPT---------------------------------------------------------
-----TIAARQSGQGISWLFPF-TDGHPPLG--------WSDTLAYLVLPVLLVISQYVS
SQVMQPP--Q-NNDPS---QQGAQAVVKFLPLLIG--YFALSVPSGLSLYWLT-------
NNILSTAQQVWLQKLGGAKNPVKEYIDKLAKEESTNLGK--------------PEPAIKS
DPLPKVGKPPASQEPEPSGPQR------------------GERFRKLKEEESRRKVFLEK
AEQTEQAGTQAG-------------------------------------------IVDGK
QNSDA-SGDNIDEQESHENEPII------------ANGNGGLSHSTNEMIPNGSMKEVCF
VLIKATNIFK--------------------
>Zea_mays_gnl|BL_ORD_ID|46719 _GRMZM2G426200_T04|PACid:20866535
M-------------------------------AAPSHLHLPGCPQTLALPL--PWPRG--
-FSAPPGLLSRSR-------------------------RLRPVAAL--------------
--GPADAG---------------------------------DLLGRVEALLYTVADA---
------------------------------------------------------------
------------------------------------------------------------
-------------------------AVSA--EPVAAAG--------------TKEAA---
----AGDWLSSITN-SMETVLKVLKDGLLSLHVPYSYGFAIILLTVLVKAATFPLTKKQV
ESALAMRSLQPQVK----TIQERYAG-DQERIQLETARLYKLSGVDPLAGCLPTLVTIPV
WIGLYRALSNVANEGLL--------------------------------TEGFFWIPSLA
GPT---------------------------------------------------------
-----TIAAQQNGQGISWLFPF-TDGHPPLG--------WSDTLAYLVLPVLLVISQYIS
SQVMQPP--Q-SNDPS---QQGAQAVTKFLPLLIG--YFALSVPSGLGLYWLT-------
NNILSTAQQVWLQKLGGAKNPVKEYIDKLSREESTNVQK--------------NGSTVQS
KPLPKLSKAQPSQELKPTGPQR------------------GERFRKLKEEESRRKEVLGQ
AEQSEQSSFESS-------------------------------------------VVDGA
QISDASSGDKNDEQEPHEIGPIV------------ANSNGGVNHSRNEKTENFSSEKEAA
DDHSSVSKPMLPDAHKLTDQDNGNDAV---
>Cucumis_sativus_gnl|BL_ORD_ID|32113 _394650.2|PACid:16983237
M------------------------------------ASISPYRPNFVFSS--FPSRV--
-PNSNPLFHGVQF------RGLSHHKPFLRGSLAVARFGFKPEFLP------------DP
DNAEGFVR---------------------------------DLFGKAESFLYTIADA---
------------------------------------------------------------
------------------------------------------------------------
-------------------------AVSA--SPDNV----------------TTVKQ---
----TDDWFTGITN-YMESVLKILKDGLSTLHVPYAYGFAIILLTVLVKAATFPLTKKQV
ESAMAMRSLQPQVK----AVQQRYAG-DQERIQLETARLYKLAGINPLAGCLPTLATIPV
WIGLYRALSNVANEGLL--------------------------------TEGFFWIPSLA
GPT---------------------------------------------------------
-----TIASRQNGSGISWLFPF-VDGHPPLG--------WSDTFAYLVLPVLLVVSQYIS
VQIMQSS--Q-NNDPS---MKSSQAITQFLPLMIG--YFALSVPSGLSLYWLT-------
NNILSTAQQAWLQKAGGAKTLDKQFIDEIMKQEEKQVRVQSEAPKL--------------
NSISSSTVARQEEKPTAEGLKP------------------GERFKRLKEQEARLRQQREE
EERKAEESAKAE--------------------------------SLTVNDGDKSATVGVV
VNGSLSRQDVKEDQNSIPTTTMQRVDVDSEPSATQGEN----------------------
------------------------------
>Cucumis_sativus_gnl|BL_ORD_ID|32112 _394650.1|PACid:16983236
M------------------------------------ASISPYRPNFVFSS--FPSRV--
-PNSNPLFHGVQF------RGLSHHKPFLRGSLAVARFGFKPEFLP------------DP
DNAEGFVR---------------------------------DLFGKAESFLYTIADA---
------------------------------------------------------------
------------------------------------------------------------
-------------------------AVSA--SPDNV----------------TTVKQ---
----TDDWFTGITN-YMESVLKILKDGLSTLHVPYAYGFAIILLTVLVKAATFPLTKKQV
ESAMAMRSLQPQVK----AVQQRYAG-DQERIQLETARLYKLAGINPLAGCLPTLATIPV
WIGLYRALSNVANEGLL--------------------------------TEGFFWIPSLA
GPT---------------------------------------------------------
-----TIASRQNGSGISWLFPF-VDGHPPLG--------WSDTFAYLVLPVLLVVSQYIS
VQIMQSS--Q-NNDPS---MKSSQAITQFLPLMIG--YFALSVPSGLSLYWLT-------
NNILSTAQQAWLQKAGGAKTLDKQFIDEIMKQEEKQVRVQSEAPKL--------------
NSISSSTVARQEEKPTAEGLKP------------------GERFKRLKEQEARLRQQREE
EERKAEESAKAE--------------------------------SLTVNDGDKSATVGVV
VNGSLSRQDVKEDQNSIPTTTMQRVDVDSEPSATQGEGVLETYTRVAKDAKLNGEEQRE-
------------------------------
>Vitis_vinifera_gnl|BL_ORD_ID|426 _GSVIVT01000594001|PACid:17817051
M-----------------------------------STFFAFHTSPLHLSP--FPHRT--
-QIRTPILHPSHF------PGLPN-----RRSLGVARFGFRPF---------------HS
DGADAVIG---------------------------------DLFGRVETLLYTIADA---
------------------------------------------------------------
------------------------------------------------------------
-------------------------AVSA--SD---------------------GKQ---
----SGDWLSGITN-YMETVLKVLKGGLSTLHVPYAYGFAIILLTVLVKAATFPLTKKQV
ESAMAMRSLQPQIK----AIQQRYAG-DQERIQLETARLYKLAGINPLAGCLPTLATIPV
WIGLYRALSNVADEGLL--------------------------------TEGFFWIPSLS
GPT---------------------------------------------------------
-----TIAARQNGSGISWLFPF-VDGHPPLG--------WSDTLAYLVLPMLLIVSQYIS
VQIMQSS--Q-SNDPS---LKTSQALTKFLPLMIG--YFALSVPSGLSLYWFT-------
NNILSTAQQVWLQKLGGAQIPVKQFSDDIEKEELSQI----------QK----PVFEINS
----TKKEPKQTEKLTSEGLRP------------------GERFKQIKEQEARRRQQREE
EKTKAEEAAANRIPTTNGGYKNEANSTKREYRTGGDLVDGGNDSFQSLTTTHNSSNIEVV
VNDELSNEDSKDEQKMYVTRTES--------------SENSVNYEVDVRDEQHINGKLEK
EVIEVCTDNKPSGEETLQPRREQPTEREEV
>Alb4_gi|332192418|gb|AEE30539.1| ALBINO3-like protein 1 [Arabidopsis thaliana]
M-----------------------------------SSTISLKPTHLIL-S--SFSTG--
-KVLQFRRSRFSH------T-PSSSSS--RYRTLVAQLGFRPD-----------------
-----SFD---------------------------------FIKDHAENLLYTIADA---
------------------------------------------------------------
------------------------------------------------------------
-------------------------AVSS--SETFESVAG--------TT--TKTTQ---
----SNDWFSGIAN-YMETILKVLKDGLSTVHVPYSYGFAIILLTVLVKAATFPLTKKQV
ESAMAMKSLTPQIK----AIQERYAG-DQEKIQLETARLYKLAGINPLAGCLPTLATIPV
WIGLYRALSNVADEGLL--------------------------------TEGFFWIPSLA
GPT---------------------------------------------------------
-----TVAARQNGSGISWLFPF-IEGHPPLG--------WPDTLAYLVLPLLLVFSQYLS
IQIMQSS--Q-SNDPA---MKSSQAVTKLLPLMIG--YFALSVPSGLSLYWLT-------
NNILSTAQQVWLQKYGGAKNPVEKFTNLVTKEDKTQQIEKSFSEPLVQK----------S
VSELKIPREKGGEKVTPECPKP------------------GERFRLLKEQEAKRRREKEE
-RQKAEAALSNQ------------------------------------------------
------NTDKAHEQDEKSDTAIVA-EDDKKTELSAVDETSDGTVAVNGKPSIQKDETTNG
TFGIGHDTEQQHSHETEKR-----------
>gi|332192418|gb|AEE30539.1| ALBINO3-like protein 1 [Arabidopsis thaliana]
M-----------------------------------SSTISLKPTHLIL-S--SFSTG--
-KVLQFRRSRFSH------T-PSSSSS--RYRTLVAQLGFRPD-----------------
-----SFD---------------------------------FIKDHAENLLYTIADA---
------------------------------------------------------------
------------------------------------------------------------
-------------------------AVSS--SETFESVAG--------TT--TKTTQ---
----SNDWFSGIAN-YMETILKVLKDGLSTVHVPYSYGFAIILLTVLVKAATFPLTKKQV
ESAMAMKSLTPQIK----AIQERYAG-DQEKIQLETARLYKLAGINPLAGCLPTLATIPV
WIGLYRALSNVADEGLL--------------------------------TEGFFWIPSLA
GPT---------------------------------------------------------
-----TVAARQNGSGISWLFPF-IEGHPPLG--------WPDTLAYLVLPLLLVFSQYLS
IQIMQSS--Q-SNDPA---MKSSQAVTKLLPLMIG--YFALSVPSGLSLYWLT-------
NNILSTAQQVWLQKYGGAKNPVEKFTNLVTKEDKTQQIEKSFSEPLVQK----------S
VSELKIPREKGGEKVTPECPKP------------------GERFRLLKEQEAKRRREKEE
-RQKAEAALSNQ------------------------------------------------
------NTDKAHEQDEKSDTAIVA-EDDKKTELSAVDETSDGTVAVNGKPSIQKDETTNG
TFGIGHDTEQQHSHETEKR-----------
>Brassica_rapa_gnl|BL_ORD_ID|16345 _012507|PACid:22699855
M-----------------------------------ASAISLRPTSLILSS--SFSTG--
-RVLHFRRFPFSH------RPPSSSSS--RRRTLVAQFGLGPGSFP--------------
-DPGFSLD---------------------------------LIKDHAESLLYTIADA---
------------------------------------------------------------
------------------------------------------------------------
-------------------------AVSS--SETFESVSG------------TTTKQ---
----NSDWFSGIAN-YMETILKVLKDGLSTVHVPYSYGFAIILLTVLVKAATFPLTKKQV
ESAMAMKSLQPQIK----AIQERYAG-DQERIQLETARLYKLAGINPLAGCLPTLATIPV
WIGLYRALSNVADEGLL--------------------------------TEGFFWIPSLA
GPT---------------------------------------------------------
-----TVAARQSGSGISWLFPF-IEGHPPLG--------WSDTLAYLVLPLLLIFSQYLS
IQIMQSSQPQ-SNDPA---MKSSQAVTKLLPLMIG--YFALSVPSGLSLYWLT-------
NNILSTAQQVWLQKYGGAKNPMEKLTNLVMKEDKTQKVEKSISEPLVKK----------S
VSELKVPKEKGGEKVTSEGPKP------------------GERFRLLKEQEAKRRREKEE
ARQKAEAALSNQ------------------------------------------------
------NIGSVQEQEDKSDTADVAVGNNERAKLSAVGETADGSVAVNGKPSIH-------
--GVGHDTEQHHSHEE--------------
>Brassica_rapa_gnl|BL_ORD_ID|32609 _032799|PACid:22716119
M-----------------------------------ATSISLKPTNLLL-S--SFSTG--
-RVLHLRRSRFSH------R-PSPSSS--CRRTLVAQFGFSPG-----------------
---PVSLD---------------------------------LIKEHVESLLYTIADA---
------------------------------------------------------------
------------------------------------------------------------
-------------------------AVSS--SETFDSFSG--------TTTTTTTNQ---
----NSDWFTGIAN-YMETILKVLKDGLSTVNVPYSYGFAIILLTVLVKAATFPLTKKQV
ESTMAMKSLQPQIK----AIQERYAG-DQEKIQLETARLYKLAGINPFAGCLPTLATIPV
WIGLYRALSNVADEGLL--------------------------------TEGFFWIPSLA
GPT---------------------------------------------------------
-----TVAARQSGSGISWLFPF-IEGHPPLG--------LSDTLAYLVLPLLLIFSQYLS
IQIMQSSQPQ-SDDPA---MKSSQAVTKFLPLMIG--YFALSVPSGLSLYWLT-------
NNILSTAQQVWLQKYGGAKNPMEKLTNLVTKEDKTQKVDKSISQPLVQK----------S
VSELKIPRDKGSEKVTSEGPKP------------------GERFRLLKEQEAKRRREKEE
ERQKAEAALSNQ------------------------------------------------
------NTDSAQEHEGKSDT--------------GAEETGDGSAAVNGKPSIQKDETTND
KLGVGHDAEKQHSHET--------------
>Medicago_truncatula_gnl|BL_ORD_ID|18646 _Medtr3g102810.1|PACid:17450297
M------------------------------------SALLPCTPTILSAP--FGNRS--
-RTNHLPLRPHSH------ALPGSTKRFLRGSLSVTRFGFHPGFLP------------EP
EDAEFVLR---------------------------------ELFNRAEGFLYTIADA---
------------------------------------------------------------
------------------------------------------------------------
-------------------------AVSS--SDIAITT--------------TTAKQ---
----NNDWFSGITN-YMEIILKVLKDGLSTLHVPYAYGFAIIMLTILVKVATFPLTRKQV
ESAMAMRSLQPQVK----AIQKQYAR-DQERIQLETARLYTLANINPLAGCLPVLLTTPV
WIGLYRAFSNVADEGLL--------------------------------NEGFFWIPSLS
GPT---------------------------------------------------------
-----TIAARQNGSAISWLFPF-VDGHPPLG--------WPDTLAYLVLPVLLVVSQYIS
LQIMQSS--Q-ATGPN---AKSSQVLNKVLPLVIG--YFALSVPSGLSLYWFT-------
NNILSTLQQIWLQKLGGAKNPLRQVLDDNVKNVDLMQV---------QK----SVSNLNS
---TKIEEARKDSKLTSEGPRP------------------GDKFKQLMEQEAKKKQQREE
EKRKAEEAAAKA------------NNHEQTVEGGNQVVNDLVKNSQSVADDTDPSISGVI
------NGNGKDLEGNQNSTSTSDTANDEGSAHLNAVNKKNLEKESREVLSTRVTTNKQA
HGEDSDRVSKD-------------------
>Aquilegia_coerulea_gnl|BL_ORD_ID|37516 _056_00063.4|PACid:22060639
M-----------------------------------ATILSLQPQSLLQSP---IRTS--
-SNSLLLSHKSNF--------FTYNKPCVRQSIGVIRFSLKPPSSF-----------PDL
DGADAFIQ---------------------------------HLFSKTESLLYTLADA---
------------------------------------------------------------
------------------------------------------------------------
-------------------------AVSA--SSST-----------------NGVKE---
----NGDWFTGITN-IMEIVLKVLKDGLSAVNVPYSYGFAIILLTVLVKAVTFPLTKKQV
ESAMAMRSLQPQIK----AIQQEHAG-DQEKIQLKTAQLYKIAGVNPLAGCLPTVATIPV
WIGLYRALSNVANEGLL--------------------------------TEGFFWIPSLA
GPT---------------------------------------------------------
-----TVAARQNGSGVSWLFPF-VDGHPPLG--------WSDTLAYLVLPLLLIVSQYIS
VQIIQSS--Q-SNDPN---MKSSQAVTKVLPLMIG--YFALSVPSGLSLYWFT-------
NNILSTAQQIWLQKFGGAKNPVMKFTDTSIKEVQQQLQE--------------SVTKINS
TKE-----VKTKEENSSGGPRP------------------GDRFKQLKEQEARKKQQREA
EKRKLTAKVTET---LNNEKKELKSSKTENEVTLAEPYDIRNKRPQPVTDSHSSRV----
------NGDHSIQSSNEENIDMSVPKSENGGFASTSGVDEKKEILLQEKLDKDDRTEMCT
TATTTTSASGVGSSDISEHKQVEPSKRDEN
>Chlamydomonas_reinhardtii_gnl|BL_ORD_ID|9070 _17.g729800.t1.1|PACid:19867375
M---------------------------------------ALQMKQSPS-M--GVRRA--
-SQPVLPPRPIVH---------RGVGSVSRRPAVVVKASL-----------------LDA
ASAASAVD-----------------------------------AVHHATQLYTLA-----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----EGGPIDVLAQ-FFEFVLQTLDEGLESAKIPYSYGFAIIALTVLVKVATFPLTQKQV
ESTLSLQALQPRVK----ELQAKYAD-DPENLQLETARLYKEAGVNPLAGCFPTLATIPV
FIGLYNALSNAAKEGLL--------------------------------TEGFFWIPSLG
GPT---------------------------------------------------------
-----TI-----GGGLEWLVPF-ENGAPPVG--------WANAAAYLVMPVLLVASQYAS
QKIISSQ--N-NQDPS---QQQAQAILKFLPLMIG--WFSLNVPSGLTLYWFV-------
NNLLSTGQQLYLKATVKVNIPEAIKA----------------------------------
--------PATAGSSTPIVKPK------------------EERVKKVTGKELGSRKKRR-
------------------------------------------------------------
------NDDGEEVEDVEVEVVS--------SGSSSSSGSNGASGRKGEKFRALKAREAAA
KAASTVSAGAGGSEEGKDNSA---------
>Volvox_carteri_gnl|BL_ORD_ID|5658 _Vocar20010438m|PACid:23129534
M---------------------------------------ALAMKQYPSAL--GARKP--
-CQPLLPPRPSVR------RPGAGIGSGSRRAAVCVKASL-----------------LDP
STAASTVE-----------------------------------AVQHAQNLYTLA-----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----DGGPIDLLAQ-FFTSVLRTLDDGLENAHVPYSYGFAIITLTVLVKLATFPLTQKQV
ESTLSLQALQPRVK----ELQAKHAD-DPETLQLETARMYKEAGVNPLAGCLPTLATIPV
FIGLYNALSNAAKAGLL--------------------------------TEGFFWIPSLS
GPT---------------------------------------------------------
-----TI-----GGGLEWLFPF-QDGAPPVG--------WANAAAYLVMPVLLVASQYAS
QKIISTT--QNSNDPA---QQQSQAILKFLPLMIG--WFSLNVPSGLTLYWFV-------
NNLLSTAQQLYLKATVKVNVPESIKA----------------------------------
--------PVAATSAT-VVKPK------------------EERVKRITGKELGARKKRR-
------------------------------------------------------------
------NEAGEEVEEVDVEIVSTSGSNGAASASPAVNGNGSGSSRKGEKFRALKAREAAA
KAAA--------------------------
>Coccomyxa_subellipsoidea_gnl|BL_ORD_ID|1260 15426|PACid:27386896
M-----------------------------------------------------------
--------------------------------------------------------TLAD
TAASSAAQ---------------------------------AVGDKA-------ADA---
------------------------------------------------------------
------------------------------------------------------------
-------------------------IVSS--ATAVQSAT---------DAAAEAVQR---
----DNGWFGFFTG-PFETVLKVLDTGLDKLHVPYSYGFSIILLTIFVKALTFPLSKKQV
ESTVAIQALQPRVK----EIQEKYKGRDPQEAQIEVAKLYQEAKVNPLAGCLPTLITLPV
WIGLYRALSNVADEGLL--------------------------------SEGFFWIPSLA
GPT---------------------------------------------------------
-----TLAAQKAGAG-SWLFPL-VNGAPPIG--------WHDASAYLVLPVLLIVSQYVS
QKIISPP----SEDPS---QQSAQWILKFLPLMIG--WFSLNVPSGLTIYWFI-------
NNVLSTAQQLWLKKTIQPPALASAGTGTVVN-----------------------------
--------ARSSVEDLRPTGET------------------GCPFSLAASAPCK-------
------------------------------------------------------------
------------------------------------------------------------
------------------------------
>Micromonas_pusilla_CCMP1545_gnl|BL_ORD_ID|10331 52221|PACid:27348985
M--------------------------QATSATGAGAVARGAVAVAGARAS--SIRGV--
-AA--LPARRASR------ALAPRRRVAPRRAAVAARASI-GGEFP-------VFDVIND
AVINAHAS---------------------------------AMTSDALGSIFQVADA---
------------------------------------------------------------
------------------------------------------------------------
-------------------------A-AV--DVEEIP-----------------GLQ---
----KGGWLGPITD-FLEASLGVIDQGLEGLNVPYSYGYAILVLTVVVKLVTFPLTKKQV
EGSIAMQALQPRVK----ELQAMYAN-DPERLQMETARLYKEANFNPLAGCLPTFATLPV
FIGLYRALSNAATEGML--------------------------------EDGFYWIPSLG
GPT---------------------------------------------------------
-----SIAARNDGSGFSWLWPF-VDGAPPLG--------WHDTAAYLALPVLLVVSQFAS
QKIMTPDQGK-DVDPS---QASSQAILKFLPFMIG--FFSLNVPAGLTLYWFA-------
NNIFSTAQTVYLRKTTKAPDSIQNVGGGSAAM----------------------------
--------PMPGTTPAATQPVR------------------VEYVPKSQRKSGGA--APKP
PPPRVEAMPAAV----------------------------------------------AS
EFADFDDGPARVTETVEGVVVGGDGADATESAGGGGGGDARGKGSKKSKKAAGSRKRRNK
SR----------------------------
>gnl|BL_ORD_ID|4751 96326|PACid:27400020
M--------------------------AACVANLGGIARSNALTPVGARGA--SSSRT--
-AGGLLPLRRAGS------SGRAVRRV---RSSVAVRASMAGAEFP-------SFDQVQG
AVANVHAS---------------------------------FIGNDAVASLFQVADA---
------------------------------------------------------------
------------------------------------------------------------
-------------------------ADAA--APEELK-----------------GLQ---
----KGGWLGPITD-LLESILKGIDSGFVGLGVPYSYGYAILALTVLVKVVTFPLTKKQV
EGSLQMQAIQPRVK----ELQAMYAN-DPERLQMETARLYKEANFNPLAGCLPTFATLPV
FIGLYRALSNAAVEGEL--------------------------------TDGFYWIPSLG
GPT---------------------------------------------------------
-----SIEARNDGNGFAWLFPF-VDGAPPLG--------WHDTIAYLVLPVLLVASQLIS
QKVMTPDQPK-SDDPA---QQQSQAILKFLPFMIG--FFSLNVPAGLTLYWFA-------
NNIFSTAQTVYLRKTTKAPEMPAAVAGGM-------------------------------
--------PMPG-TPASAQPVR------------------VEYVPKSQRKAQGSVPAPKP
APPKVEPMPESL----------------------------------------------AA
EFGDFDDGPAKIVEPV--VVEAKVVADTTGAAAAAAAGEAGGKKGGSRKGSKGSRKRKGS
RK----------------------------
>Ostreococcus_lucimarinus_gnl|BL_ORD_ID|557 3334|PACid:27413422
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------EALK---------------AAGLQ---
----KGGWLGPITD-GLESALEGIDSVLDG-RVPYSYGFSIIVLTVLVKLATFPLSKKQV
ESSMQMQAMQPRIK----ELQAMYAN-DPERLQMEQARLYKEAGFNPLAGCLPVFATLPV
FIGLYRALSNAASEGLL--------------------------------TDGFYWIPSLG
GPT---------------------------------------------------------
-----SIASRNAGSGFAWLWPF-VDGHPPLG--------WHDTTAYLVLPVLLVASQYVS
QQIVSPQ-PK-TDDPA---QQQSQAILKFLPLMIG--FFSLNVPAGLTLYWFA-------
NNIITTAQTLILRKTTTAPEPPVAKSGAAG------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------
>Chlamydomonas_reinhardtii_gnl|BL_ORD_ID|5308 _06.g251900.t1.1|PACid:19863606
M-----------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------YVLADA---
------------------------------------------------------------
------------------------------------------------------------
-------------------------SAST--AAAAVMPTAVD------SAAGAAPQR---
----AGGWVAPVAD-ALEQVLYALQEGLDKLHVPYSYGYSIILLTLIVKLLTYPLTKQQV
ESAMAVQALKPRID----LIKDRFGE-DKDKIQKETSVLYEQAGVNPLAGCLPTLATIPI
FIGLFSSLTNVANDGLL-------------------------------DTQGFYFVPSLA
GPT---------------------------------------------------------
-----TMAMRQSGLGTSWLWPLGPDGAPPIG--------WEDAAAYLTLPLLLVAVQYAS
SSVTSPP--IDPKDEN---ANTQRALLVFLPLMVG--WFSLNVPAGLSLYYLA-------
NTVLSSAIQIYLKKLGGANVVMNEL-GPVTK-----------------------------
--------PGSGRRNGVAAGEW------SVWKPATVL-TTAEAAKARAEAEEAVERAREA
AEEAAAAAAFDN------------------------------------------------
-------------ASVSLSVDDSTAAIAGTATMAVTAGATAAAMDPSKVNRRCKRRRLTS
LVQDGSTASAAVAGASA-------------
>Volvox_carteri_gnl|BL_ORD_ID|4166 _Vocar20003543m|PACid:23128036
M-----------------------------ATLRYRPVAQRVKRNAHFRYA--IRYAA--
-RNVLVDLPCPGR------LRGSSYRAGSEITLLTSHLSAGIPDYL--------------
-----------------------------------------DRADLLPTFSFPLANA---
------------------------------------------------------------
------------------------------------------------------------
-------------------------GAAS--ESVAAAVTANI------LSASPTDQR---
----AGGWVAPLAD-VLEQVLYVLKDCLDLLHVPYSYGYSIILLTLIVKIVTYPLTKQQV
ESTLAVQALKPRVD----LIKDRFGD-DKEKIQKETSILYEQAGVNPLAGCLPTLATTPI
FIGLYSSLTNVANEGLL-------------------------------DTQGFYWIPSLA
------------------------------------------------------------
-------------------------------------------------------VQYAS
LYSTGPT--SDATDVN---ARLQRALLLGLPVMIG--WFALNVPSGLSLYYLS-------
NTILSTAQQVYLKKLGGAKVAIKKL-GPIMK-----------------------------
--------PGSGRRSGAPEAEL------KLWVSATTFKSTAERGKNSLNMEGPVELARNA
LDTDLPETTAAL------------------------------------------------
-----------------------------TDVIKSSQTDSSPLVDLSNVNRFCKRRRLSS
LVQDGANGAQIFPAATTSV-----------
>Coccomyxa_subellipsoidea_gnl|BL_ORD_ID|5045 12888|PACid:27390681
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------SRVLHHWRCSALQAAAQ---
----DDGWLAPISS-GLNYSLQQIQTGLDQLHVPYSYGWAIIVLTVGTKILTFPFTK--V
ESALAVQKLKPTID----AIKRQYGE-DKNSIQRETSALYEASGVNPAAGCLPTLATIPI
FWGLYRTLSNVASAGLL--------------------------------TEGFYWIPSLS
GPT---------------------------------------------------------
-----SLAAQRAGTGTAWLFPF-VDGAPPVG--------WEDAARYLALPIALVAAQFAS
SAVISPP--IDDEDKN---AAFSKGLLIAVPFMVG--WFALNVPSGLSLYYFS-------
NTIITSGIQIWLRKLGGAYSPLLLLTFIHWPTVRACSSFLCC------------------
--------PRQANSCASLFLVP-----------------GNHLFACWARRDFYVQLSW--
------------------------------------------------------------
------------------------------------------------------------
------------------------------
>Micromonas_pusilla_CCMP1545_gnl|BL_ORD_ID|3956 31798|PACid:27342602
M------------------------------------------TSQGCSSG--SLVCR--
-GARGLYRCGRQT------GCPRRDTSLLSRRTRPRSFDASCGAISATDIGESITIVPDV
ITAAIFAS---------------------------------EQIADLSESTFTVGAT---
------------------------------------------------------------
------------------------------------------------------------
-------------------------VVDS--SHATLFAELSA------LTEITGPQR---
----MEGILSPVSD-LLEEFVLATQRYFSDAGVRYPLGSSIIFTTFVVKALTYPFTKVQV
ESALNMQNLQPQVN----AVREKYRD-DQEQMNIEINRLYEDNQVSPLAGCGPLLLTLPV
VWGLYRAFNNASIDGSF--------------------------------DEPWFFIPSLA
GPT---------------------------------------------------------
-----------PDRSLAWLLPLDDNYQPPLG--------WHDASLYLVVPILTVASQYVS
MSILSPV--KDLNDPNTAETEQQSFLLNFLPLFIG--YISLTVPAGLTLYWLF-------
NNIFTTATQVYLRQGGGAVAKVEKIKDVKLKVPLGCAIVDQNSTDQLSVHDVFEGPYVLV
TDSGEIDLAYSGEIDLAYSALPDHDKAYGFYLSPELRSAKTDKWRLHMEKRGKRSLDPAE
RYNATPEELRLL------------------------------------------------
-----------------ISEYLKLGMVAEAEEISVELGRLGSETERSDPL----------
------------------------------
>Ostreococcus_lucimarinus_gnl|BL_ORD_ID|3977 3329|PACid:27416850
A-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------AKIA------SGEIAAPQR---
----MEGWLAPVSD-ALEDLLFAIQGQLQGLGVPYSTGNAIIIVTILVKFVTYPLTRDQV
VSSLNMKNLQPQIA----AIREKYED-DQERMNKEINRVYEENGVNPLAGCGPALLTFPV
LAGLYRAFNNAGIDGAF--------------------------------DEAWFFLPSLA
GPT---------------------------------------------------------
-----------DARDLSWLLPLDSDYAPPIG--------WEEASLYLIFPVLTTISQFVS
MEVLKPE--ETEKTDE---MKNQSVLLKLLPLFIG--YISLTVPAGLALYWFW-------
NNVFTTGIQVFLRN-GGAKATVE-------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------
>ecYidC_gi|341919621|gb|EGT69232.1| yidC [Escherichia coli O104:H4 str. C227-11]
MDSQRNLLVIALLFVSFMIWQAWEQDKNPQPQAQQTTQTTTTAAG---------------
------------S------AADQGVPASGQGKLISVKTDVLDLTINTRGGDVEQALLPAY
PKELNSTQ-PFQLLETSPQFIYQAQSGLTGRDGPDNPANGPRPLYNVEKDAYVLAEGQNE
LQVPMTYTDAAGNTFTKTFVLKRGDYAVNVNYNVQNAGEKPLEISTFGQLKQSITLPPHL
DTGSSNFALHTFRGAAYSTPDEKYEKYKFDTIADNENLNISSKGGWVAMLQQYFATAWIP
HNDGTNNFYTANLGNGIAAIGYKSQPVLV--QPGQTGAMNSTLWVGPEIQDKMAAVAPHL
DLTVDYGWLWFISQ-PLFKLLKWIHSFVG------NWGFSIIIITFIVRGIMYPLTKAQY
TSMAKMRMLQPKIQ----AMRERLGD-DKQRISQEMMALYKAEKVNPLGGCFPLLIQMPI
FLALYYMLMG--------------------------------------------------
------------------------------------------------------------
-----SVELRQA--------PF-ALWIHDLS--------AQD--PYYILPILMGVTMFFI
QK-MSPT--T-VTDPM------QQKIMTFMPVIFT--VFFLWFPSGLVLYYIV-------
SNLVTIIQQQLIYRGLEK------------------------------------------
--------------------------------------------RGLHSREKKKS-----
------------------------------------------------------------
------------------------------------------------------------
------------------------------
>pfYidC_gi|359763816|gb|AEV65895.1| YidC [Pseudomonas fluorescens F113]
MDIKRTILIVALAIVSYVMVLKWNQDYGQAALPTQNVAASNTAPSLPDVPV--GNNAA--
-SNDDIPRAASDT------SAPAEAPVAVSKDLIQIKTDVLELAIDPQGGDVAQLKLPLY
PRRQDHPEIPFQLFDNGNERTYLAQSGLIGTNGPDSDPAG-RPVYSAEKKIYQLADGQDQ
LVVDLKFS-KDGVNYIKRFTLKRGLYDVTVSYLVDNQSAQPWSGAMFAQLKRDASDDPSS
STATGT---ATYLGAALWTSSEPYKKVSMKDM-DKGQVKETVQGGWVAWLQHYFVTAWIP
QKGESNLVQTRKDSKGNYIVGYTGPALTA--APGAKVETSAILYAGPKSQAVLKELSPGL
ELTVDYGFLWFIAQ-PIFWLLQHIHSIVG------NWGWSIIFLTMLIKGIFFPLSAASY
KSMARMRAVAPKLA----ALKEQHGD-DRQKMSQAMMELYKKEKINPLGGCLPILVQMPV
FLALYWVLLE--------------------------------------------------
------------------------------------------------------------
-----SVEMRQA--------PF-MLWITDLS--------IKD--PFFILPIIMGATMFIQ
QQ-LNPT----PPDPM------QAKVMKMMPIIFT--FFFLWFPAGLVLYWVV-------
NNVLSITQQWYITRKIEAAAKKAEA-----------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------
>pmYidC_gi|124022319|ref|YP_001016626.1| inner membrane protein translocase component YidC [Prochlorococcus marinus str. MIT 9303]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------IGYISDNILLPILDFFYGLVP------SYGLAIVALTVVIRLALFPLSAGSI
RSARRMRIAQPAMKKRQDEIKSRYAK-DPQKQQEELGKVMKEFG-NPLSGCLPLLVQMPI
LFALFATLRGSPFADVPYLVNLKVLPSDQIAAIEPKPFTSSKHSIFISETKHFPVIASLQ
SGTKLGVGDKAQIKLQTLTGESFTSRLSGVEGGTKFTPTWSVTKGDDLVKVSADGTIQAL
SEGDATVQGKIPGLAAQSGFLF-IKALGQVGFYVDGEINWDIAILVGGFGLTLLVSQILS
GRGL-------PANPQ------QSTANKITPVMITGMFLFFPLPAGVLLYMVI-------
ANIFQAGQTFLLSREALPENLQ--------------------------------------
--------------------------------------------KILNEQQSKPALATEA
IGGSDRLPFEPKK---RK------------------------------------------
------------------------------------------------------------
------------------------------
