>Capsella_rubella_gnl|BL_ORD_ID|27074 _v10026454m|PACid:20912920
M-AF--RRTLSIRS--TLFARRNQPVYHIIPRPN--DHERESFCQETSQRSYHSFL-HQS
--SINNS-----DFSKILGGGL----HMPLAPASGFAF--YRYMS-SAPGVGSE-NIG--
---------VMTD----------------------------IAE-VISE-----STLQDA
--PAQ--AAAAVSEVTIAAADSF------PPIA--------ALQHCIDMVHSFTGFGWWA
SIVVATILIRSATVPLLIKQMKDTTKLALMKPRLESIREEM--QNKGMDAVTMAEGQKKM
KNLFKEYGV------TPFTPMK----GMLIQGPLFISFFLAIRNM-AEK------VPSFQ
-TGGALW------FTDLTT-PDSL-------------------------------YILPV
ITGLTFLITVECNAQE--GMEGNPM-------AGTIKNVFRGFALLTVPMTMSFPQAIFC
YWIT-------SNMFSLMYGLVIK-----------RPQVKKMLRI-PELPP-----PTP-
---GQQPSFDLFSALKK------------MKAMTQ-DHSQNQ-----------TLPPSPV
NPRA---TSTSLSPVSKRLKALESQV-------KGRKKNSSKKR----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
>Arabidopsis_lyrata_gnl|BL_ORD_ID|24484 _496379|PACid:16058231
M-AF--RRTLAIRS--TLFARRSQPSYHIIPLAN--DHERDSFSQETSQRSYHSFL-HQR
--SVNNS-----DFSKVSGGGL----YLPMAPMSAFAF--YRYMS-TAPGVGSE-KIG--
---------VMSD----------------------------IAE-VITD-----STLQDV
--PAQ--AAAAVSEVTLAAADSF------FPIA--------ALQHCIDMVHSFTGFGWWA
SIVVATILIRSSTVPLLIKQMKDTTKLALMRPRLESIREEM--QNKGMDSVTMAEGQKKM
KNLFKEYGV------TPFTPMK----GMFIQGPLFICFFLAIRNM-AEK------VPSFQ
-TGGALW------FTDLTT-PDSL-------------------------------YILPV
ITGLTFLITVECNAQE--GMEGNPM-------AGTVKNVCRGFALLTVPMTMSFPQAIFC
YWIT-------SNLFSLMYGLVIK-----------RPQVKKMLRI-PDLPP-----PPP-
---GQQPSFDLFSALKK------------MKAMTQ-DHTQNQ-----------TLPPSPV
NPRI---SSQSLSPVSKRLKALESQV-------KGRKKNSSKKK----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
>atOXA1_gi|15241690|ref|NP_201011.1| mitochondrial inner membrane protein OXA1 [Arabidopsis thaliana]
M-AF--RQTLSIRS--RLFARRNQPVYHIIPRES--DHERDSFCQETSQRSYHSFL-HQR
--SVNNS-----DFSKVSGGSL----HLPLAPTSGFAF--YRYMS-SAPGVGSE-KIG--
---------VMSD----------------------------IAE-VITD-----STLQDV
--PAQ--AAAAVSEVTLAAADSF------FPIA--------ALQQCIDMVHTFTGFEWWA
SIVVATILIRSSTVPLLIKQMKDTTKLALMRPRLESIREEM--QNKGMDSVTMAEGQKKM
KNLFKEYGV------TPFTPMK----GMFIQGPLFICFFLAIRNM-AEK------VPSFQ
-TGGALW------FTDLTT-PDSL-------------------------------YILPV
ITGLTFLITVECNAQE--GMEGNPM-------AGTVKTVCRVFALLTVPMTMSFPQAIFC
YWIT-------SNLFSLMYGLVIK-----------RPQVKKMLRI-PDLPP-----PPP-
---GQQPSFDLFSALKK------------MKAMTQ-DHTQNQ-----------IEPPSPV
NPRL---SSTSLSPVSKRLKALESQV-------KGRKKNSSKKK----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
>gi|15241690|ref|NP_201011.1| mitochondrial inner membrane protein OXA1 [Arabidopsis thaliana]
M-AF--RQTLSIRS--RLFARRNQPVYHIIPRES--DHERDSFCQETSQRSYHSFL-HQR
--SVNNS-----DFSKVSGGSL----HLPLAPTSGFAF--YRYMS-SAPGVGSE-KIG--
---------VMSD----------------------------IAE-VITD-----STLQDV
--PAQ--AAAAVSEVTLAAADSF------FPIA--------ALQQCIDMVHTFTGFEWWA
SIVVATILIRSSTVPLLIKQMKDTTKLALMRPRLESIREEM--QNKGMDSVTMAEGQKKM
KNLFKEYGV------TPFTPMK----GMFIQGPLFICFFLAIRNM-AEK------VPSFQ
-TGGALW------FTDLTT-PDSL-------------------------------YILPV
ITGLTFLITVECNAQE--GMEGNPM-------AGTVKTVCRVFALLTVPMTMSFPQAIFC
YWIT-------SNLFSLMYGLVIK-----------RPQVKKMLRI-PDLPP-----PPP-
---GQQPSFDLFSALKK------------MKAMTQ-DHTQNQ-----------IEPPSPV
NPRL---SSTSLSPVSKRLKALESQV-------KGRKKNSSKKK----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
>Prunus_persica_gnl|BL_ORD_ID|63 _ppa005941m|PACid:17640356
M-AY--WRSLSTRASFTARRRQNHPSITHILHDD--DRKHDVVSEQASSPNLNHFLSQKR
--FFGNNLGRISGFGGFAPDRRIS--NALLSSSSGFAC--SRYMS-TAIGGGSD-KVE--
---------LLSD----------------------------VSG-VVSD-----ATMEAV
--AS---QVSAMSEIAIATADSW------LPVK--------ALQYLIGSVHTYTGLNWWA
AIAITTLLIRTATVPILINQLKAMSKLALMKPQLEEYRQEM--QDKGMGREAVAEFQKKT
GKLYKEYGV------HPLSAMK----GIFVQAPVFISFFLAISNM-AEK------VPSFK
-SGGAYW------FLDLTT-PDSM-------------------------------YIFPV
LAALTFLLTVECNLQE--GMEGNPA-------AGTMKNVSRGLAVLTVPFTMSFPKAVFC
YWVT-------SNMFSLGYGLVLK-----------YSGLKKALGI-PRLPS-----TPP-
-SQRSQPAFSLLSTMKQ------------VAAVTQ-DTTSSP-----------VEQSKVQ
DGRT-----SSSSVLSQRIKTLEKQV-------KGRKRNKKR------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
>Citrus_clementina_gnl|BL_ORD_ID|25930 _0.9_010575m|PACid:19277084
M-AY--RRSLTTRA--TLIARAYNPSFNYIIYDH--DHKQKSPDETLSRTNIHSFI-QSR
--SFGSSLNNSYGLGNFFHSQRVS--QFSLVPSVGSAF--CRYMS-TTVGEGAD-KIE--
---------LISD----------------------------VAD-VFTE-----TTVQAI
--AN---QAPAVNEVAIAAADSF------LPVA--------ALQHFIDAMHNFTGFNWWA
SIIVTTLLIRTATVPLLINQLKSTSKLTLMRPRLEEIKQDM--QDKAMDPMAVADGQKQM
QNLFKEYGV------HPLTPLK----GLFIQGPVFISFFLAISNM-AEK------VPSFK
-NGGAFW------FTDLST-PDSF-------------------------------YILPI
LTGLSFLITVECNMQE--GLEGNPA-------AVTMKNISRGFAVLSIPLTMTFPKAIFC
YWIT-------SNFFSLVYGLVLK-----------VPGVKKMLGV-PEIPV-----VQQ-
-TTDPKPSFSLFSAIKQ------------ASEAKA-ARQASA--------SVTAEQPKST
EQKI-----SSSAVLSQRIRSLEKQV-------KGRKKNKKR------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
>Ricinus_communis_gnl|BL_ORD_ID|25034 _30190.m010832|PACid:16823199
M-AY--IRSLTTRS--TLLKRHCHPSFTFFLHQHSDDH------NNTSIDEFSSV--QGR
--GFHSKSSGSFDIRPFQEIRFRD--AYSLSPSIGASF--CRYMS-STVGEGSDHKIE--
---------LISD----------------------------VADVVLTD-----ASAQSV
--ATNV-TAPVVNEVAAAAADCF------APVA--------VLQHVIDAVHNLTGFNWWA
SIVLTTLIIRTMMVPLMINQLKATSKLTLMRPRLEEIKQQM--DNTAMDPAAIAEGNKRM
KMLFKEYGA------SPFTPMK----GIFVQGPVFVCFFLAIRNM-AEK------VPSFK
-NGGAFW------FVDLST-PDSL-------------------------------YIFPV
LTALTFWITVELNMQE--GLEGNPV-------AGTMKNISRVFAALTVPLTMGFPKAIFC
YWVT-------TNLFSFAYGGVLK-----------LPGVKQFLGV-PKIPV-----APA-
-SSTSQSSFSLSAAVKG------------ALSAKH-EPAASS------------------
---------SSSADLSQKIQTLEKQV-------KGRKRRTRR------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
>Ricinus_communis_gnl|BL_ORD_ID|6719 _29651.m000289|PACid:16804884
M-AY--IRSLTTRS--TLLKQQYRPAFTFSLHHQ--DHYDDHKQHNNSIDEFSYV--QER
--GFRSKSSGSFNIKSFQEIRLRD--AYSLSPSIGASF--CRYMSTTTVGEGSDHKIE--
---------LMSD----------------------------VADVVITD-----TSAQSV
--A----AASAVNEVAAAAADCF------PPVA--------VLHHIIDAVHNLTGFNWWA
SIVLTTLVIRTLMVPLMINQLKATSKLTLMRPRLEEIKQQM--QDTGMDPATIAEGNKQM
KMLFKEYGV------SPFTPMK----GLFIQGPVFVCFFLAIRNM-AEN------VPSFK
-NGGAFW------FVDLST-PDSL-------------------------------YIFPV
LTALTFWITIELNMQE--GLEGNPV-------AGTMKNISRVFAALTVPLTMGFPKAIFC
YWVT-------TNLFSFAYGGVLK-----------LHGVKKFLGV-PEIPV-----APP-
-SATSQSSFSLSSALKR------------ALAAKQ-EPATSS------------------
---------SSPSDLSQKIQTLEKQV-------KGRKRNARR------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
>Medicago_truncatula_gnl|BL_ORD_ID|1865 _AC233677_14.1|PACid:17433516
M-AY--RRCLLQRGK-NLIDRRCNPSFTYILHSD--DEGKQRDQPDSAGRISNSFT-QTR
SFGFGNSLNGSMGFSP----------SSPFAAGYYNNF--CRNMS-TTPDQGFD-KIT--
--------ELTTD----------------------------VAH-VLSD-----TAVDAI
--SSQ--AAPVVSEVAIAAADSF------LPVQ--------VLQYAIDAVHTYTGLNWWS
AIVVTTLLIRIATVPLLINQLKTTSKLTIMRPRLEELKAEM--DGKTFDPQAVAEGQEKM
KQLFKEYGV------TPFSPLK----GLLIQGPVFISFFLAITNM-AEK------MPSFK
-HGGAFW------FTDLTT-PDAL-------------------------------YVFPV
LTALSFLVVVEFNMQE--GMEGNPM-------GDTMKKFSRVLAFLSVPFTMSFPKALFC
YWLT-------SNLFSFTYGMVLK-----------VPGVKKTLGV-PDLPP-----PDP-
-TRSPPAPFSILEEIKK------------AASAAKAASAANAASAANGQTSLPVESSKQP
TKKISSSSSSSAAVISQRLKSLEKQV-------KGRKKNKK-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
>Vitis_vinifera_gnl|BL_ORD_ID|12508 _GSVIVT01019529001|PACid:17829133
M-AY--RRSVITRG--GFLARRIHPSFGYISHDE--DRKQRSADSYQSPQRISDFL-LRR
--SFGSKINTSGGFGAFFQGKGFS--PLSHQVAVGSSY--SRYMS-TAIGEGSE-NIG--
---------------------------------------------VIAE-----TPVDLI
--ANA--TVDVASEVSIAAADSF------FLVG--------ILQHLIGGVHSYTGLSWAA
SIALTTLLIRGMTVPLLVNQLKSTSKLTLMRPHLEAIREEM--QAKGMEPSAVAEGNKRM
QQIFKEYGV------TPFTPLK----GLIIQGPVFVSFFLGISNM-VQK------VPSFK
-TGGALW------FTDLTT-PDSF-------------------------------YIMPI
LAGLTFLITVEFNMQD--GMQGNPT-------AGTMKKFSRALAFLSVPFTMNFAQGIFC
YWIP-------SNLFSLAYGFAVK-----------QPAVKKMFGI-PEIPV-----PPPP
AKTSPSTSFSLSQALKN------------FKALMPKGPSSPP-----------LLPPSSP
RKPI-----SSTAVLSQRIRSLEKQV-------KGRKKNKKRHGNNASEPHREIL-----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
>Prunus_persica_gnl|BL_ORD_ID|9753 _ppa006036m|PACid:17650193
M-AC--RRSVSTTV--TFGTRRFHPAFSHILHDNNEDTKSHAPNSSLPPPVIKSTL-PRG
--SYNSTLG--FCFGSRCRERTGS--SLSWKMGLGSFH--CRYMS-TIIDDGSD-KIN--
---------DIGY----------------------------FAE-VITD-----KTVEVV
--TS---QAPAASEVAAAAADSF------FPVA--------ALQYLIDGVHSFTGCNWWA
SIALTTILIRGATIPLLINQLRATTQLNLMRPHLEELKQQM--QDMAMDPNVLQEGQKRM
KALFKEYGV------NPLSQLQ----PLFIQGPIFISFFLAVRNM-AEK------VPSFQ
-SGGALW------FTDLTT-PDSL-------------------------------LILPV
LTSLTFLITVECNMQE--GLEGNPI-------AQTMKNYSRILAAISVPVMMGFPKALFC
YWLT-------SNLFSLTYGLVIR-----------LPEVKTFLGL-PEIPM-----PPP-
-APSQPQSF-LSSAIEQ------------DTTVES-------------GPPLPTKPSKIA
DRRI-----SRTSILKQRLKSLENQI-------KERNKQKKM------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
>Capsella_rubella_gnl|BL_ORD_ID|17375 _v10023251m|PACid:20903117
M-AC--LRGITKRV--NVLQRRAYPSCGHLIPD---DRDDTRSTSSSSDTMFRKVL-ARN
--ATTSK------LSSSFEARHYQ--SFAGPLGLGLSS--CRYMS-STPPEWSE-KVD--
---------GIDF----------------------------AATEVVPD-----EIVEAV
TMTSQ--AAPAINEVAIAAADSA------FPVA--------ALQHLIDGVHSFTGLNWWA
SIALTTVIIRGVTVPILLNQLKATYKLNVLRPQLEELRREM--STKAQDPEAMAEGQRRM
QLLFKEHGV------TPFTPLK----GLIIQGPIFISFFFAIRNM-AEK------VPSFK
-TGGTLW------FTDLTT-GDTT-------------------------------YILPL
LTAVTFLIMVESNMQE--GLEGNPV-------AGTMKKFSRIIAFLSIPVLIGIEKALFC
YWLT-------SNLFTLVYGLTLR-----------RPDVRKLLNL-PDVVNSSTKQPSP-
-SSSSPLPFSFSEPKDQ------------SVT-QEKPPMCSS-----------ESSSSVP
DRRI-----SRSSVLNQRIRTLERQL-------KDQKNKK--------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
>Arabidopsis_lyrata_gnl|BL_ORD_ID|8400 _483801|PACid:16042147
MATC--LRGITKRV--NLLQRRVYPSCGHLIRD---DRDETKSDSSNSHTMIRKVL-ASN
--G-TSK------LSSMSLERHYQSFSFSGPLGLGLSS--CRYMS-STPPEWSD-KVD--
---------GIDF----------------------------VATEVVPD-----EIIEAV
TTTSQ--AVPAINEVAIAAADSA------FPVA--------ALQHLIDGVHSFTGLNWWA
SIALTTVLIRGVTIPILLNQLKATYKLNVLRPQLEELRQEM--STKAQDPEAMAEGQRRM
QLLFKEHGV------TPFTPLK----GLIIQGPIFISFFFAIRNM-AEK------VPSFK
-TGGTLW------FTDLTT-ADTT-------------------------------YILPL
LTAVTFLIMVESNMQE--GLEGNPV-------AGTMKKFSRIIAFLSIPVLIGIEKALFC
YWLT-------SNLFTLVYGLTLR-----------RPDVRKFLNL-PDVVNSSTRQPSP-
---ASPLPFSFPETKDQ------------SVVAQDKPPMSSS-----------ESSSSVP
DRRI-----SRSSVLSQRIRTLERQF-------KDRKNKK--------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
>Thellungiella_halophila_gnl|BL_ORD_ID|9619 _Thhalv10001727m|PACid:20189149
M-AC--LRGISKRV--NLLQRRVYPSCGHLIGD---DKDETRSASPNPDTMIRK---ANN
--G-ANK------LSSMFTERHYQ--SFYGPLGLGLSS--CRYMS-STPPEWSD-KVD--
---------GIDF---------------------------VAATEVVPD-----QIIESV
T-TSQ--AVPAINEVAIAAADSV------FPVA--------ALQHLIDGVHSFTGLNWWA
SIALTTVIIRGVTVPILLNQLKATYKLNALRPQLEELRQEM--STKASDPEAMAEGQRRM
QLLFKQHGV------TPFTPLK----GLIIQGPIFISFFFAIRNM-AEK------VPSFK
-TGGTLW------FTDLTS-ADTT-------------------------------YILPL
LTAVTFLIMVESNMQE--GVEGNPV-------AGTMKKFSRIIAFLSIPVLIGIEKALFC
YWLT-------SNLFTLGYGLAIR-----------RPDVRKLLNL-PDVIISSTRQPSP-
---ASPMPFSFTQPKDQ------------SDV-QENPPMPSS----------ESSSSSAP
GRRI-----SRSSVLNQRIRTLERQL-------KDRKKKN--------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
>Sorghum_bicolor_gnl|BL_ORD_ID|5142 _Sb01g049540.1|PACid:1955098
M-AFSARRSLATSLS-HHFSRRLHPSISHLIPPHHDNSDPAPSPSSSPVPPPRPQS-QQP
APPFPSA------LPWASRSRAVA--PFPLPFALHLAA--HRHFSASPPDT---------
-DVLTDAAAAAAP----------------------------VSE-LLSD--GVASAAASV
--PLP--PAPYPGEVAAAAAESF------PPVA--------ALQHLLDAVQSFTGLNWWA
TIALTTVMIRLVTVPLLINQMKSTMKLNEMRPEIEAINEEM--RN-STDPRSMEVGKQKL
GELFLRHGV------TPLTPLK----GLFIQGPIFMSFFFAISNM-VEK------VPSMK
-GGGMYW------FTDLTT-PDNL-------------------------------FILPV
LTSLTFLATVELNMQD--GMEGNPM-------AKTMKKVSRFFGVMFVPFTIGFPKAIFF
YWVT-------SNLFSLVYGAVLR-----------NPAVRLCLNL-PPLES-----HPT-
--PAQVQPLNLSRGPEA------------SPGVDSPISDKECE------QSSSVLSTGAD
SPIADKECEQSSSVLSDRIRDLEIRA-------KSRGGSQE-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
>Brachypodium_distachyon_gnl|BL_ORD_ID|20740 _1g77470.1|PACid:21823510
M-AFSARRSLASSLS-GHLTRRLHPSLSHLIPSHHDHSE---NTSSSSPPPPTQQP----
-QHFPSA-----DLRRRTRSQNLT---LPLPFGAHLAG--HRNFSTSSSGA---PEIDAA
TGVLSDGAAGDID---------------------------VAAD-VLSD-----AASSVV
--PAF--PAPFPGEVAAAAADSF------PPVA--------ALQYVIDAVHSFTGLNWWA
CIALTTVLIRTATVPLLVNQLKSTMKLNAMRPEMEAINMEM--RN---DPGSMLEGKKKL
GELFTKHGV------NPLTPLK----GLFIQGPIFMSFFFAIQNM-VEK------VPSLK
-GGGAYW------FTDLTT-PDEL-------------------------------YILPV
LTSVTFLATVELNMQD--GMEGNPM-------LQTMKKFSRVLAVMTVPFTMHFPKAIFF
YWVT-------ANLFSLGYGFALR-----------KPAVRGYLNL-PHIVP-----QPV-
--PAQLSTFNLFEGPKS------------MPAVDSPAAVKGSK-----------------
-------DEQSNSVLNSRIVDLEKKIAELERNAKSRGESQD-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
>Brachypodium_distachyon_gnl|BL_ORD_ID|24053 _3g31430.1|PACid:21826823
M-AFAARRSLASRFS-HHLTRRLHPSVPHLLSSRSNDDD---RPSPSK-PPQ--------
LPPFRSP------LPPASRAAQTL--NHLLPFSLHHSSLPRRNFSSSAPAPASAP-----
------APTGEAD---------------------------AAAG-VLAD-----AAEAAA
--ATV--PAPFPGEVAAAAADSF------FPVA--------ALQHLIDTIHTFTGLNWWA
CIALTTVLIRSATIPLLVNQLKSTHKLNAIKPEMEAIKDEM---N-SMDQKSAMEGRKKI
KALFKKHGV------SPFSPLK----GLLIQGPMFMSFYFAINNM-VEK------VPSLK
-GGGAFW------FTDLTT-PDPL-------------------------------YILPV
LTGLTFLATVEINLQE--GMETNPM-------AGKMKMFSRGMAVMTVPFTMNFAKGIFC
YWIT-------SNLFTLVYGIVIR-----------RPTVRKLFNL-HALVA------PS-
-APGQKSAFSFFGGSKA------------IPSADSPLAIMSAK------------QS-LE
--------KPDAAALGYRVKNLDKKV-------KSRGKSRKRR-----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
>Setaria_italica_gnl|BL_ORD_ID|8600 _Si035842m|PACid:19681993
M-AFAARRNIATRLS-HHLTRRVHPCVPHALTSHSSDEQ---ASSSKPLPIP--------
LPPLHTP------LQHRSGAAQTV--G-FLPFSLHLAGPTRRSFSSSAPAPAPAPDIE--
-----TAPAAEVD----------------------------AAG-VLAD-----AAE-AA
--ASV--PAPFPGEVAAAAADSF------LPVA--------ALQHFIDAIHTFTGLNWWA
CIVLTTLIIRTATVPMLVSQLKAMTKLNAIKPEMEAIKDQT---D-TMDLKSAEEGKAKM
QALFKKHGV------SPFAPMK----GLLIQGPIFMSFFFAISNM-VEK------VPSLK
-GGGTLW------FTDLTT-PDSL-------------------------------YLLPV
LTGLTALATVEFNLQQ--GMEGSPM-------TGKMKNVARGMAFMAVPFTMNFAKGIFC
YWIT-------SNIFSLAYGVVIR-----------RPAVKKLFNL-PDLPA-----QPS-
-PATQMPTFNFFGGSRA---------------AESPVAIAGAQ------------RSPLE
--------QPDAAALGYKVKNLEKKV-------KSRGKRKHR------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
>Selaginella_moellendorffii_gnl|BL_ORD_ID|6238 _73518|PACid:15407516
M-----------------------------------------------------------
------------------------------------------------------------
----SESAAESIR----------------------------FPE-TLAD-----AAQEIV
SGAAGA-TYDLSKEIVLAVSESF------PWTA--------AVQYVIYATHVVTGLPWWL
SIALTTVAVRTMVLPLVIYQVKSTARFALLRPDLEKIKVDM--EQANYDPVALAENKRKM
AELFAKHKT------DPFTPLI----GALLQGPIFMCFFFGLRTM-AEK------MDSFK
-EGGAFW------FTDLTT-PDEL-------------------------------YILPF
ITTATFLITVELNAVD--GMQGQPN-------QKTMKNILRGMGVLFLPLTAQFPKALFC
YWVT-------SNLWSMLQGALLR-----------NKKFKAYLDI-PDTSHLGTPAPPP-
-------TITSSKPPAR------------KAITPPPGVSFNP------------------
---------------------------------GDSKKARRLVH----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
>Coccomyxa_subellipsoidea_gnl|BL_ORD_ID|7951 39658|PACid:27393587
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------KLRRWL
TIIYTTIGARLLTLPLVVKQQRNTANMTMARPEMMALKDWYTEETARGNPKATTEYQQRL
ANLWQKYDC------NPFKSML----GILAQAPLFIGFFSALRALSAAK------VPSMT
-EGGVAW------FTDLTL-ADPY-------------------------------YALPI
MSSAVFLLTVELGAAD--GMQGQDE-----AMLRRMKNIFRAIGVAMVPLTASFPQGVFL
YWVT-------SNIFSLGQSVLFK-----------LPAVRKTLKL-PDLAKMRATATGLP
ITEAGKPLVTFAQPPKQ------------RKAKTT-------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
>Micromonas_pusilla_CCMP1545_gnl|BL_ORD_ID|9618 3586|PACid:27348271
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------EVIAIAADSW------ITTA--------GLMYVIEYFHLAHGMEWYA
AIAAATCVMRVCAFPLTIMQQKSAGKMHLAKPEMTALQESI-NEARRAGEHERAARLGRV
FAIWSKHDV------HPAKMLA----PLLFQAPVFISFYFAISRM-AEG------LPSMR
-DGGFAW------FQDLSI-ADPT-------------------------------FALPI
ISSLTFLAAVEFAPQN--PAVKSSQ-------REMTKWGLRALGVAMVPLTASFPSGVFV
YWIT-------SNVFSFAQTVLLR-----------VPFAKRAMGI-PEDPPP--------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
>Ostreococcus_lucimarinus_gnl|BL_ORD_ID|5645 40894|PACid:27418518
M-----------------------------------------------------------
------------------------------------------------------------
---------------------------------------------TTAG--GAAETLTSA
SDLAPV-VGSLASEVVPVASQSW------PTTA--------ALMYAMEYFHVAHGLEWWL
AIVGATVFMRTITFPLIVMQMRNTAKMQLCKPELEALQAKM-KSNPQQDPELANAYYKEM
QKVWKKYDV------NPVKSFA----PILINAPVFISFFFAISKM-AQG------VPSFE
-SGGPSM------YPDLSM-ADPT-------------------------------YSLPI
LSSLTFLASVELGAVE--GMQTSQS--------AQMKWFLRALAVAMVPLTASFPQGVFV
YWIT-------SNIFSGFQTSITR-----------TKAFKSTMGI-PDVSAVAEAPAEAA
LGRVQLDRFQ-------------------KKYGATPTLHKRP------------------
---------------------------------PTQKQRKK-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
>gnl|BL_ORD_ID|3407 69262|PACid:27398672
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------HLAHDMEWWA
AIMATTAIMRVFVMPFMVMQQRVAARMHIAKPEIEALNARI--KGMGGDQQVMAEAQKEI
FAIWKKHNC------NPAYMML----PIAVQAPLFISFYFAISEM-AKG------VPSFA
-SGGPDWPLGPISMHDLTA-ADPT-------------------------------YIMPV
LSSATFLATVEL------GGAGNPETSGAAQQTMMTKWGLRALSVALIPMTAGFSKGVFV
YWIT-------TNMFSLGQTLAFK-----------VPLIKKIVAI-PEIP----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
>Chlamydomonas_reinhardtii_gnl|BL_ORD_ID|3384 _16.g690200.t1.1|PACid:19861677
M-AQRWRALQRGAALLAHHTE-SAASTQVLSACSTSASSLLQQITLD--QRGSGGSWQQ-
------------------------------------------HQHAWGSSSHRTFFSFAR
KKPDAGAVAAASTG---DETSISGSEPVADPTPVGPPEFFPLPESA-------PDAIEVA
SAIHQACSALERASIMSAKADAF------FSAS--------WCISGLQAVHDLLDTPWFL
SIAIFNITLRLLTFPLMVVAQKGSAKMMEFNHNLIHAKKLQ---EAAMKATSQEEHQRLF
QAFRNEYNVQTAKHGDPVKTALVVPGVMILNGAIFLSIFNGVSKLMAAK------VPSLT
-TGGALW------FSDLTS-PDPY-------------------------------FGLPL
MCTAVTLAMVEYGINL--AGDAGPMPEDRAKMTNGLKNFMRVMAFMFIPAGGYVAAGTAV
LWVS-------NTAFGVVQGLTLR-----------NDRFRRRVGL-PTMQALRDMNAKVM
AANAAGTPASAGAAGASAAATLAAAADTSAPASAAPLLSNSP------------------
---------------------------------VGAKARR--------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
>Volvox_carteri_gnl|BL_ORD_ID|131 _Vocar20001462m|PACid:23123990
M-AQRWRSLQRGAALLLHHAEPSASGAPGLLSAYPSASSLILNLKSDQHQHKGGASWHQ-
------------------------------------------N-HAW---TGFIGVRHAS
TKSSSASVPSSSSGFPDDAPSNSG----MDLTP--PPEFFPLPESS---------AAEVA
TAIHQACDALERASLLGAKADAF------FAAS--------WCISGLQAVHEMLDTPWWV
SIMLFNISLRLCTFPLMVLAQRGSAKMMEFNYALLHAKKLQ---EAAMKATNRAEHDRLF
NAFRTEYTAQVSKHGDPVKTALMVPGVMIFNGFVFLSIFNGISKLMAAKVLRRCAVPSLT
-TGGALW------FSDLTQ-PDPF-------------------------------FGLPI
MCTLVTLAMVEYGINL--AGDAGPMPSERQQATKTMKWVFRVLAFMFIPAGNYVAAGTAL
LWVS-------NTAFGVVQGMLLR-----------NDGVRQRMGL-PSMQELREMNARVL
EANSANAPKPSEAPPSIFSAT-KPSLDT-APAVNVPLMSRPP------------------
----------------------------------GSKGTKGP------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
>Vitis_vinifera_gnl|BL_ORD_ID|12270 _GSVIVT01019145001|PACid:17828895
M-----------------------------------------------------------
-----------------------------ATSEKLLTHLRRRRFREISSLSNSLSFAVPP
PISHRSLINPNSHYQLHHHGLFKSRHNLYFPS--------NLISLAPFS--FSHSRSFSS
GDSDY----VGTDVAVESAIESI------PPVR--------FLVSLLDGYHDVTGWPWWI
IIASSTLALRIALFPILVLQLKKMKRIAELLPKLPPPLPPP-----LSGRSYFDQISLFR
KEKRAIGCP------SFLWFLA----SLSTQVPCFILWMMSIRWMSLDH------HPGFD
-SGGALW------FQNLTEFPNGVLG-----------------------------PIFPI
LISGLHFINVQISFST--SSVGQVP-GLLGLLAKYYKFYLEILTVPIFFTGFYIPQGSLV
YWVT-------NSSLSAIQQLTIR-----------HPTVRAKLGL-PDKQAPNAAAKEMH
T----------------------------PGEGSLGPPTKQQYISPESVSPQELPGIKSM
YPRRKQHQIPIESLSPRDLIALSVQI-------LSKGDKDGAIPFIRMAL----------
---DKDPNYVRALVVMGQTLLQKEQVEEASDYLERAVTKLFLIGHPTEDEVDLMILASQW
AGAACVR---QGKTAEGLVHLERIANLKEPDEPKSKA--HYFDGLLLLASTLYREGRNAE
------AAKHLRKAAAYNPAYKE-YLEECEREDG--------------------FVNDLV
SSRRGDY
>Arabidopsis_lyrata_gnl|BL_ORD_ID|17489 _475515|PACid:16051236
M-----------------------------------------------------------
------------------------------------------------------------
AVWRTCLRASSSSSSRHRFSTLFP---LFSSISNPPPLFSPSPSPSPPC--FPPLRRFIS
SSPEF--PIIPQEIIIPNDDSSL-------PVL--------FVVDFLDGFHEFTGLPWWM
IIASSTVAVRLALLPLLILQLKKLKTISELLPQLPMPIPET-----PTLKGSIDQFSHFL
KESRAIGCP------SFLWFFP----YLSVQLPCFFLLMASIRKMSLDG------HPGFD
-SGGALW------FQNLSDLPVGSFG-----------------------------PVFPI
LIAAFHYINIQISFDT--STIRQTT-GLTGLLMRYYKLYLEILGVPLFFVGYAIPQGSLV
YWVT-------NSSVNIFQQLSLK-----------HPRVGAKLGL-LTQGASPSVEHSME
ISES---------------------------------------------------VIKYV
DSDLKEHTLSLQTLTPEELLSLSVQV-------LSKDDKETSIQLLRLAL----------
---DKDPGYVRGLVLMGQALLQKTELSEATKYLELAISKLLDEDPSDAEDVELLMLASQW
AGAAYVQ---QGKMKSGITHLERVAKLKEPGDPKSKE--HYFEALLLLSSALYKEGQSDE
------AAKILRVVVEHNPAYKP-LLEQCEDENE--------------------LVSDLV
SRRKDHF
>Capsella_rubella_gnl|BL_ORD_ID|19818 _v10020136m|PACid:20905590
K-----------------------------------------------------------
------------------------------------------------------KKELEI
AMWRSCLRA---SSSRHRFSTLFSSQTLKPFISYPPP---PSPSPSPPC--FPSLRRFIS
TGPEL--PIGSQD-IIPSDDSSL-------PVL--------AVVNFLDGFHEFTGLPWWM
IIASSTVAVRLALLPLLILQLKKLKTISELLPQLPMPIPET-----PTLRGSIDQFSRFL
KESRAIGCP------SFLWFFP----YLSVQLPCFFLLMASIRKMSLDG------HPGFD
-SGGALW------FQNLSALPGGSFG-----------------------------PVFPI
LIAGFHYINIQISFDS--PTIRQTT-GLTGMLMRYYKLYLEILSVPLFFVGYAIPHGSLV
YWVT-------NSSVNIFQQLSLK-----------HPMVGAKLGL-LGQGASSSVGHSME
ISES---------------------------------------------------VIKYV
DSNSQEQTLSLQTLTPEELLSLSVQV-------LSNGDQETSIQLLRLAL----------
---EKDPGYVRGLVLMGQALLQKTQLAEATQYLELAISKLLDSDPSDPEDVELLMLASQW
AGAAYVQ---QGKMKSGITHLERVAKLQEPGDLKSKE--HYFEALLLLSSALYKEGQSDE
------AAKILRVVVDHNPAYKP-LLQQCEDENE--------------------LVSDLV
SRRKDHY
>Physcomitrella_patens_gnl|BL_ORD_ID|28679 _Pp1s184_10V6.1|PACid:18065215
MSFTSRGRLHVAAILRRTHKCSLLSSSPTSPSLHAQRSRSFSQLRAVSGPPFEFAQLWGG
CLYPSHGGVLGNPTWVRRFSWWRWGGVNSVP-------------DSVSNSTAQLDNGEGE
AVVEASARLPSSTFRQEDEVVAGESVHESFPSAGDDREQLGLGRGNLQL--DDGVA----
-------SVDTNGAIAEDAGGSMFWSTLQIPTD--------AIIVTLDRFQNFSGVPWWL
TIIGSTLALRAALFPLTVTQLRKASLLARLSSQLPPPVPPR-----GSGVSLASQYRIFT
KRRLELGAP------SPMWLIA----VPLIQVPLFIYWIVAVRQMAMAS------HPGFD
-TGGILW------FTDLTV-PVQGALG----------------------------ALFPV
IVAATYFTNLQF-----------------------YKWWLEAATIPAFIFGFYLPQGVFM
YWIT-------NNCCSLAQTIALR-----------QPGVRTALGL-PSLAELSKL-----
-----------------------------RGSSPTPPPAQTGLLKME-------------
---------AVENMNSDDLLVLAANC-------IAMQKENEALEVLHYTV----------
---EKFPDKVEALFALGKIYSEKQLWSKASLYHGLVLRK--------TKERELVIAASLG
AGVALFN---LGKRSEALEIMSVFTEMDVPQDPLSQH--RYFKACITLGSVLSQEGRKNE
------ALKLLKKAAKYEPMVEKVFIPQLEKELG--------------------IRS---
-------
>Ostreococcus_lucimarinus_gnl|BL_ORD_ID|1034 93298|PACid:27413900
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------SDSMTHLHAATGAPWFV
ALAASAALVRAATAPISARTIKASATVSAASALAKSRKRGN---SEHVGVRDVLDAIGEL
RGKAPGTGA------HPAWLVA----GPLAQIPFFLCAVMAVRRLAADG-----ANNGLV
-TGGALW------FQDLTV-PAVDVAMMTAPMGPYG-------------------GILPV
LTAAALFANVNANFAS--AAAQSRG-------MTIVKLVLEWMTLPMLVIGMQLPQAVHC
YWLT-------SSAWALAQNRALS-----------TTFAREALGI-NALAKVTREIAASQ
GLGGEDVAMSPEVL----------------------------------------------
-----------------ELVKAAAKE-------RAGNNNAQAVNLLLRAARGGGDVAAAL
RGEDLGKSHPTVLFALGQTYAVLKEWKKSALTYEYSARA--------EPDPLRRSRALMG
AGVARARLGDLGMASEALYEANRLNPTDASVK-------------VALASALKLNGDPER
------ALEILREAAELQPDIDERYVKPLERELA--------------------------
--SRTSA
